[댓글 기능] 안돌 미션 제출합니다.
woowacourse/jwp-blog pull request #104
Opened 2019-07-29 08:18 UTC by andole87

존경하는 제이슨 선생님, 리뷰를 요청드리며 몇 가지 여쭙고자 합니다.

1.
CommentService는 UserService, ArticleService와 의존 관계를 갖고 있습니다.
댓글 기능을 위해서 유저와 아티클에게 처리를 요청하는데요, 자연스러운 건지 의문이 생깁니다.
서비스가 복잡해지면 순환참조의 위험도 있어 보이고요... 서비스는 다른 서비스에 의존해도 괜찮을지 궁금합니다.

2.
CommentService를 테스트하기 위해 많은 필드를 주입받아야 했습니다.
CommentService는 CUD 기능만 지원합니다. 댓글 보여주는 것은 아티클 엔터티의 컬렉션으로 보여집니다.
코멘트를 확인하기 위해 CommentRepository, CommentService의 필드들이 제대로 요청을 수행하는지 알기 위해 레포지토리들... 필드가 과하게 많다는 생각이 듭니다.
이렇게 여러 레포지토리와 관계하는 서비스는 어떻게 테스트하는게 좋을지 궁급합니다.

3.
테스트클라이언트의 중복을 제거하는게 좋은 일일까요?
저는 로그인이 필요한 요청의 경우, AuthTestClient를 상속받아 로그인 세션을 담은 WebTestClient만 주도록 만들었습니다. 매번 로그인 요청하는 것보다는 **로그인 요청이 끝난** WebTestClient를 제공하는것은 의미있다고 생각했습니다.

WebTestClient는 그 자체로 API를 제공하는데요, 추상화단계를 끌어올리면 일반적 테스트는 좋아집니다.
서비스가 커지거나 테스트 요건이 다양화되면 일반화 작업이 무용지물이 될 것 같아요... API의 다양한 기능을 직접 제어하기 어려워질 것 같아요.

많은 리뷰어들이 중복 제거 피드백을 주신 걸로 알고 있습니다.
WebTestClient를 래핑하여 일반화하는 작업에 대해서 어떻게 생각하시나요?

리뷰에 감사드립니다.

2019-07-31 01:47 UTC, woowahan-pjs requested changes
지금 만나러 갑니다.

2019-07-31 01:47 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/article/Article.java
>      private String title;
`@Column`을 사용하여 데이터의 속성을 표현해 보면 어떨까요?

```suggestion
    @Column(nullable = false)
    private String title;
```

2019-07-31 01:47 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/article/Article.java
> +    @Lob
`@Lob` 👍

2019-07-31 01:47 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/article/Article.java
> +        log.debug("article Ready to Save {}", modifiedArticle.getId());
Model 내부에서 로깅을 하는 것에 대해 어떻게 생각하세요?

2019-07-31 01:47 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/comment/Comment.java
> +    @CreatedDate
`@CreatedDate` 👍 `Article`에도 적용해 보면 어떨까요?

2019-07-31 01:47 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/comment/Comment.java
> +    @LastModifiedDate
`@LastModifiedDate` 👍 `Article`에도 적용해 보면 어떨까요?

2019-07-31 01:47 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/comment/Comment.java
> +    public void setAuthor(User author) {
생성자를 통해 `author`를 전달할 수 없나요?

2019-07-31 01:47 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/user/User.java
>      @Convert(converter = UserEmailConverter.class)
`@Convert`를 사용하지 않고 구현해 보면 어떨까요?

2019-07-31 01:47 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/user/User.java
>      public void updateNameAndEmail(String name, String email) {
FACTORY 👍 어떤 객체를 생성하는 일이 복잡하다면 FACTORY를 이용해 이것을 캡슐화할 수 있어요.

2019-07-31 01:47 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +    public List<Article> findAllPage(Pageable pageable) {
`Pageable` 👍

2019-07-31 01:47 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/article/Article.java
> +        return this.comments;
새로운 컬렉션에 담아 외부에 의한 변조를 막는 것은 습관처럼 사용하는 것이 좋습니다.

2019-07-31 14:07 UTC, andole87 commented on src/main/java/techcourse/myblog/domain/user/User.java
>      public void updateNameAndEmail(String name, String email) {
사족입니다만
혹시 DDD에서 이런 User가 Aggregate가 되나요?

2019-07-31 14:08 UTC, andole87 commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +    public List<Article> findAllPage(Pageable pageable) {
😎

2019-07-31 14:42 UTC, andole87 commented on src/main/java/techcourse/myblog/domain/article/Article.java
> +        log.debug("article Ready to Save {}", modifiedArticle.getId());
너무나도 과하겠군요.. 잘못했습니다. 🙇

2019-07-31 14:43 UTC, andole87 commented on src/main/java/techcourse/myblog/domain/article/Article.java
>      private String title;
`@Column` 애너테이션은, 
DB에 매핑될 컬럼에 대해 명확히 메타정보를 남기는 것에 의미가 있습니다.
`@Column` 애너테이션을 적극적으로 사용했습니다.

2019-07-31 14:45 UTC, andole87 commented on src/main/java/techcourse/myblog/domain/article/Article.java
> +    @Lob
`@Lob` 애너테이션 javadoc:
```
Specifies that a persistent property or field should be persisted
 * as a large object to a database-supported large object type.
```

현재 맥락에서는 애너테이션 대상이 `String`이므로, 그에 맞는 컬럼 타입은 `LongText`가 됩니다.

2019-07-31 14:50 UTC, andole87 commented on src/main/java/techcourse/myblog/domain/comment/Comment.java
> +    @CreatedDate
`@CreatedDate` , `@LastModifiedDate` 애너테이션은 `AuditingEntityListener` 전처리 클래스가 만들어 줍니다.
`AuditingEntityListner`는 `@Configuration` 애너테이션이 붙는 설정 클래스에 `@EnableJpaAuditing` 애너테이션으로 활성화 할 수 있습니다.

`AuditingEntityListner`는 내부적으로 `@PrePersist`와 같이, 영속화 이전 전처리 작업을 처리할 수 있습니다.

따라서 `@Entity` 객체가 영속화 되기 전, `AuditingEntityListner`가 생성시간, 수정시간을 자동 기록하게 됩니다.

`@PrePersist` javadoc:
```
Specifies a callback method for the corresponding 
lifecycle event. This annotation may be applied to methods 
of an entity class, a mapped superclass, or a callback 
listener class.
```

2019-07-31 14:54 UTC, andole87 commented on src/main/java/techcourse/myblog/domain/comment/Comment.java
> +    public void setAuthor(User author) {
도메인에는 `setter`를 최대한 피해야 합니다. 
애플리케이션 시스템의 의존성 흐름은 항상 도메인 쪽으로 흐르고 있습니다.
도메인 레이어에서 외부에 의존성을 갖거나 불변성을 잃으면 애플리케이션 전체가 fragile 해집니다. 

`setter`는 대표적인 불변성 오염 방식이므로, `setter`를 없애고 생성자 주입 방식으로 바꾸었습니다.

2019-07-31 15:01 UTC, andole87 commented on src/main/java/techcourse/myblog/domain/user/User.java
>      @Convert(converter = UserEmailConverter.class)
`@Embedded` 를 사용했습니다.

기능적으로는 `@Convert`와 유사하지만 세부 동작은 조금 다른 것 같습니다.

`@Converter`는 애너테이션 대상이 기술하는 대로 객체를 값으로 바꾼 후 DB에 저장합니다.
그래서 `@Convert`에는 객체를 변환하는 `방법`을 기술합니다.
결론적으로 작업해야 할 클래스가 Entity, VO, Converter 총 세개가 필요합니다.

`@Embedded`는 `@Entity`의 한 필드가 임베디드 상태임을 표현합니다. 
임베드할 객체는 `@Embeddable` 애너테이션으로 임베드할 것을 표현합니다.
`@Embeddable`은 VO를 대상으로 합니다. 객체를 전환할 방법은 기술하지 않습니다.
결론적으로 작업해야 할 클래스는 Entity, VO 둘 뿐입니다.

`@Convert`가 유리할때
개념적으로는 같지만 DB에 적절한 **타입**이 없는 경우,
DB 저장 값과 애플리케이션 내 사용될 값이 매핑이 필요한 경우,
상호간 변환에 특정 연산이 필요한 경우

그외에는 간단히 `@Embedded`를 사용하는게 유리하겠습니다.

2019-07-31 15:10 UTC, andole87 commented
세션에 User를 담으면서 생각해야 할게 많았습니다...
User의 필드 중 Password는 철저히 가리고 싶었는데요,
User를 확장한 LoginUser를 만들고 `getPassword()` 메서드가 `UnSupportedMethod` 예외를 던지게 했다가... 세션 매니저와 관계, ArgumentResolver와 관계가 너무 복잡해지는 것 같았습니다.

UserSessionInfo가 User를 래핑하도록 했는데, 혹시 더 좋은 방법이 있을지 궁금합니다.
감사합니다.

2019-08-02 00:30 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/user/User.java
>      public void updateNameAndEmail(String name, String email) {
네, 맞습니다. 👍

2019-08-03 09:54 UTC, woowahan-pjs requested changes
피드백을 잘 반영해 주셨습니다. 👍 
간단한 생각거리를 남겼으니 코드에 반영해 주셔도 좋습니다.
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

2019-08-03 09:54 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/article/Article.java
>      private String getDefaultUrl(String coverUrl) {
메서드 이름은 메서드의 정확한 동작을 구체적으로 나타내는 것이 좋겠죠?

2019-08-03 09:54 UTC, woowahan-pjs commented on src/test/java/techcourse/myblog/repository/CommentRepositoryTest.java
> +    private ArticleRepository articleRepsository;
오타 발견!

```suggestion
    private ArticleRepository articleRepository;
```

2019-08-03 09:54 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/user/User.java
> +    private List<Article> aritlces = new ArrayList<>();
양방향 연관 관계는 항상 서로 참조해야 합니다. 어느 한 쪽만 참조하면 양방향 연관 관계가 성립하지 않아요. 항상 서로 참조하게 하려면 연관 관계 편의 메서드를 작성하는 것이 좋습니다. 객체 지향적인 사고로 바라보세요.

2019-08-03 09:54 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/user/UserEmail.java
> +
공백 라인을 의미 있게 사용하는 것이 좋아 보이며, 문맥을 분리하는 부분에 사용하는 것이 좋습니다. 과도한 공백은 다른 개발자에게 의문을 줄 수 있어요.

2019-08-03 09:54 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/user/converter/UserEmailConverter.java
> +@Deprecated
`@Deprecated` 👍

2019-08-03 09:54 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/service/CommentService.java
> +    public Comment addComment(Long articleId, String email, CommentDto commentDto) {
참조 자료형 대신 기본 자료형을 사용하면 어떨까요? 아래의 글을 참고하세요.
https://jaehun2841.github.io/2019/03/01/effective-jave-item61

```suggestion
    public Comment addComment(long articleId, String email, CommentDto commentDto) {
```

2019-08-03 09:54 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +    private final CommentService commentService;
사용하지 않는 멤버 변수 제거!

2019-08-03 09:54 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/web/support/ArticleControllerAdvice.java
> +    @ResponseStatus(value = HttpStatus.UNPROCESSABLE_ENTITY)
`@ResponseStatus`가 있으면 의도대로 동작하지 않아요.

2019-08-03 09:54 UTC, woowahan-pjs commented on src/main/resources/templates/article.html
공백 라인을 의미 있게 사용하는 것이 좋아 보이며, 문맥을 분리하는 부분에 사용하는 것이 좋습니다. 과도한 공백은 다른 개발자에게 의문을 줄 수 있어요.

2019-08-04 09:56 UTC, andole87 commented
1. `@SessionInfo`
ArgumentResolver에 커스텀 어노테이션 적용해보았습니다.

2. 양방향 관계
자식 엔터티가 생성될 때 부모 메서드를 부르게 했습니다. 
하지만 엔터티 생성 부분에 `@Transactional`이 붙어 있음에도,  session이 null이라는 예외가 계속 발생합니다. 😭  무엇이 문제일까요?

2019-08-05 00:10 UTC, andole87 commented
2번에대해 자문자답해봅니다.

메서드 파라미터로 받은 User 엔터티를 바로 적용하면 레이지 이니셜라이즈 예외가 발생합니다.
파라미터로 받은 User 엔터티를 영속 컨텍스트에서 가져온 후 인자로 전달하면 문제 없습니다.

영속 컨텍스트와 무관하게, 세션에 담겨 있던 User 엔터티는 detached 상태이므로 컬렉션을 로드할 수 없는 것입니다...

2019-08-05 02:26 UTC, woowahan-pjs approved these changes
수많은 피드백을 반영하고자 대단히 고생 많으셨습니다. 💯 
좋은 개발자가 되기 위한 소중한 밑거름이 되었길 바랍니다.
이만 Merge 하겠습니다.

2019-08-05 02:26 UTC, merged