[게시글 생성/조회/수정/삭제] 도넛 미션 제출합니다.
woowacourse/jwp-blog pull request #11
Opened 2019-07-11 07:21 UTC by codeanddonuts

생성 조회만 먼저 제출하는 것인가요?

2019-07-14 02:17 UTC, woowahanCU commented on src/main/java/techcourse/myblog/MyblogApplication.java
> +        System.setProperty("spring.devtools.livereload.enabled", "true");
property는 application.properties에 설정하여 적용할 수도 있습니다.
property 우선순위도 이번 기회에 한번 확인해보세요
https://engkimbs.tistory.com/765

2019-07-14 02:24 UTC, woowahanCU commented on src/main/java/techcourse/myblog/domain/Article.java
> +        this.contents = rhs.contents;
기존의 값을 업데이트 하는 것이니 update등으로 분명히 드러내는 것도 좋다고 생각합니다.
crud naming convention과도 연결되구요.
https://www.slipp.net/questions/79

2019-07-14 02:25 UTC, woowahanCU commented on src/main/java/techcourse/myblog/domain/Article.java
> +        this.contents = rhs.contents;
그리고 축약어 사용은 자제해주세요.

2019-07-14 02:30 UTC, woowahanCU commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +        if (article.getCoverUrl().length() == 0) {
디미터 원칙 위반입니다. 아래와 같이 작성하는 것은 어떨까요
https://developerfarm.wordpress.com/2012/01/30/object_calisthenics_5/

```java
        if (!article.existsCoverUrl()) {
            article.setCoverUrl(defaultBackgroundImageUrl);
        }
...
public class Article implements Comparable<Article> {
    public boolean existsCoverUrl() {
        return !StringUtils.isEmpty(coverUrl);
    }
```

2019-07-14 02:32 UTC, woowahanCU commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +        article.setNumber(++nextArticleNumber);
비즈니스 로직은 Controller보다는 Model에 있는 것이 좋다고 생각합니다.
setter 메서드를 사용하기보다 Article Class에 메시지를 보내 내부에서 해당 로직을 수행하도록 하는 것은 어떨까요

https://softwareengineering.stackexchange.com/questions/165444/where-to-put-business-logic-in-mvc-design

2019-07-14 02:35 UTC, woowahanCU commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +    public int findIndexOfArticleById(final int articleId) {
이 클래스에서만 사용하고 있으니 접근제어자를 private으로 변경하는 것이 좋다고 생각합니다. 
그래서 이 메서드는 아래에 위치하는 것이 좋다고 생각해요.

https://stackoverflow.com/questions/4668218/are-there-any-java-method-ordering-conventions

2019-07-14 02:37 UTC, woowahanCU commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +        }
articles size를 벗어나는 index로 조회 요청을 했을 경우에 exception을 던지는 것은 어떨까요

2019-07-14 02:47 UTC, woowahanCU commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +        if (index != -1) {
flag를 사용하기보다는 메서드로 분리하여 의미를 드러내는 것이 좋을거 같네요.

2019-07-14 02:51 UTC, woowahanCU commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +        return new ModelAndView("redirect:/articles/" + article.getNumber() + "/");
RedirectView를 사용하여 redirect할 수 있어요

2019-07-14 03:00 UTC, woowahanCU commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +        model.addAttribute("article", articleRepository.find(articleId).orElseThrow(IllegalArgumentException::new));
Repository 조회 결과에 대한 Exception을 Controller단에서 발생시키는 것은 적절한 위치가 아니라고 생각해요.
IllegalArgumentException도 의미를 분명히 전달하지는 않다고 생각하구요.
그리고 find에서 Optional을 사용하고 있어서 이 부분은 큰 의미가 없다고 생각해요

2019-07-14 03:03 UTC, woowahanCU commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +        model.addAttribute("method", "put");
method를 이런 방식으로 Controll하는 것은 다소 생소한데요. 혹시 어떤 이점이 있는걸까요?

2019-07-14 03:07 UTC, woowahanCU commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +    @GetMapping("/articles/{articleId}/edit/")
REST 규약에 맞게 작성해보는 것은 어떨까요. 데이터를 수정하는데에 GET 요청을 보내는 것이 다소 어색합니다.
그리고 REST설계시엔 마지막 문자로 슬래시를 사용하지 않습니다.

- URI 설계시 주의할 점
1. 슬래시 구분자(/)는 계층 관계를 나타내는데 사용
2. URI 마지막 문자로 슬래시(/)를 포함하지 않는다.
3. 하이픈(-)은 URI 가독성을 높이는데 사용
4. 밑줄(_)은 URI에 사용하지 않는다.
5. URI 경로에는 소문자가 적합하다.
6. 파일확장자는 URI에 포함하지 않는다.

2019-07-14 03:12 UTC, woowahanCU commented on src/test/java/techcourse/myblog/domain/ArticleRepositoryTest.java
> +        testArticle.setContents(contents);
생성자를 통해 값을 주입하도록 하는 것은 어떨까요
레벨2가 되었다고 해서 레벨1 에서 했던 원칙이 변경되진 않습니다.

2019-07-14 03:15 UTC, woowahanCU commented on src/test/java/techcourse/myblog/domain/ArticleRepositoryTest.java
> +        ).isFalse();
상황에 따라 미리 dummy 데이터를 넣을 수도 있는데요. 그럴 경우에 위의 테스트는 견고하지 않다고 생각합니다.
아래와 같은 구조는 어떨까요

```java
        Article persistArticle = articleRepository.save(article);
        assertThat(persistArticle).isEqualTo(article);

        Article retrieveArticle = articleRepository.findById(persistArticle.getId());
        assertThat(retrieveArticle).isEqualTo(article);
```

2019-07-14 03:22 UTC, woowahanCU commented on src/test/java/techcourse/myblog/domain/ArticleRepositoryTest.java
> +                articleRepository.find(2).map(x -> x == testArticle).orElse(false)
테스트를 위한 로직이 assert문 안에서 분명히 드러나지 않고 있어요. 아래와 같이 작성하는 것은 어떨까요
```java
int targetIndex = 2;

Article actual = articleRepository.findById(targetIndex);
assertThat(actual)..isEqualTo(expected);
```

그리고 위의 테스트는 지금 실패하고 있어요 find(1)로 작성해야 하는거 아닐까요?

2019-07-14 03:23 UTC, woowahanCU commented on src/test/java/techcourse/myblog/domain/ArticleRepositoryTest.java
> +                articleRepository.find(1).map(x -> x.getCoverUrl() == "").orElse(false)
이 테스트도 실패하고 있네요. true여야 하지 않을까요
아님 원래 목적이 coverUrl이 defaultBackgroundImageUrl과 비교하려던 것이었을까요?

2019-07-14 03:24 UTC, woowahanCU commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +    private static final String defaultBackgroundImageUrl = "images/pages/index/study.jpg";
자바 컨벤션 9.6 Constants를 확인해보세요.

https://myeonguni.tistory.com/1596

2019-07-14 03:26 UTC, woowahanCU commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +                    });
이런 형태로 body를 테스트할 수 있기는 하지만, 개인적으로는 RestControlelr에서 명확한 값을 테스트하거나,
Controller는 Status만 테스트하는 것도 유의미하다고 생각합니다. 
오히려 body의 DOM 구조가 틀어지거나 Render되는 데이터가 복잡해질 수록 이 테스트의 복잡성이 커져 테스트 코드를 분석해야 하는 상황이 온다고 생각해요.

2019-07-14 03:33 UTC, woowahanCU requested changes
안녕하세요. 리뷰어 CU 입니다. 리뷰가 많이 늦었네요. 미안해요 😭
레벨 2가 되었다고 레벨1에서 가이드했던 원칙들이 바뀌진 않다고 생각해요.
몇가지 피드백 남겼으니 확인해보시고 궁금한 점 있으면 DM 남겨주세요.
주말 잘보내요~

2019-07-14 03:38 UTC, woowahanCU commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +    private static int nextArticleNumber = 0;
article의 index를 static 변수로 관리할 경우엔 동시성 문제가 발생할 수 있어요.
현재는 List에 담고 있으니 그 사이즈를 기준으로 index를 판단하는 것이 좋지 않을까요

2019-07-15 06:50 UTC, codeanddonuts commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +        model.addAttribute("method", "put");
별도의 파일을 분리하지 않고 그러면 어떤 방식으로 할 수 있나요? 주변에 물어보았는데 다들 th:if를 이용해서 분기한 것 같습니다.

2019-07-15 12:29 UTC, woowahanCU commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public void numbering(ArticleRepository repo) {
method name은 동작을 구체적으로 드러내는 동사를 사용하시는 것이 좋다고 생각합니다.

http://www.mimul.com/pebble/default/2013/05/04/1367639300999.html

2019-07-15 12:29 UTC, woowahanCU commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public int getNumber() {
method 순서에 대해서도 한번 고민해보셔요.

https://stackoverflow.com/questions/4668218/are-there-any-java-method-ordering-conventions

2019-07-15 12:30 UTC, woowahanCU commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +    public Article write(final Article article) {
https://github.com/woowacourse/jwp-blog/pull/11#discussion_r303225342
같은 맥락입니다.

2019-07-15 12:31 UTC, woowahanCU commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +            throw new NoArticleFoundException();
아 그냥 메서드안에서 예외처리추가하라는 의미가 아니었는데, 오해가 있었군요
index를 찾는 로직이 반드시 필요한지에 대한 의문이었습니다.

2019-07-15 12:31 UTC, woowahanCU commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +//                    });
사용하지 않는 코드는 제거해주세요.

2019-07-15 12:32 UTC, woowahanCU approved these changes
피드백 반영 잘해주셨네요 👍 
이번 미션은 여기서 Merge할게요.
피드백 남긴 부분 중에 궁금한 부분이 있으면 DM 남겨주세요~

2019-07-15 12:32 UTC, merged

2019-07-15 12:37 UTC, codeanddonuts commented
> 피드백 반영 잘해주셨네요 👍
> 이번 미션은 여기서 Merge할게요.
> 피드백 남긴 부분 중에 궁금한 부분이 있으면 DM 남겨주세요~

제가 git revert 해보다가 싹 다 날리는 바람에 다시 하다가 몇 가지 빠뜨렸네요 수정해놓겠습니다