[댓글 기능] 티버 미션 제출합니다.
woowacourse/jwp-blog pull request #112
Opened 2019-07-30 07:22 UTC by yjll1019

2019-07-31 02:43 UTC, woowahan-pjs requested changes
지금 만나고 있습니다.

2019-07-31 02:43 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/Article.java
>  	private String contents;
대량의 문자열은 `@Lob`을 써보면 어떨까요? 그 후, 생성되는 데이터 타입을 확인해 보세요.

```suggestion
	@Lob
	private String contents;
```

2019-07-31 02:43 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/Article.java
>  	public Article() {
JPA가 필요로 하는 기본 생성자를 public으로 만들면 다른 개발자가 오용할 수 있어요. 아래의 글은 가볍게 참고해 주세요.
https://goodyhlee.wordpress.com/2016/06/20/177

2019-07-31 06:27 UTC, yjll1019 commented on src/main/java/techcourse/myblog/web/ArticleController.java
>  		if (!existSession(httpSession)) {
코드 중복 해결하기(O)

2019-07-31 06:27 UTC, yjll1019 commented on src/main/java/techcourse/myblog/interceptor/AuthenticationInterceptor.java
> +		if ((!path.equals("/")) && (!path.equals("/signup")) && (!path.equals("/login") && (!path.equals("/users")))) {
config에서 설정하기
Custom Annotation 사용해보기(O)

2019-07-31 06:27 UTC, yjll1019 commented on src/main/java/techcourse/myblog/domain/Comment.java
> +	@ManyToOne
Comment가 Article을 가지고 있는게 맞을까?
그렇다면 `@ManyToOne(cascade = CascadeType.ALL)` 을 이용해보기

--> Article클래스가 List<Comment> comments를 가지도록 수정했습니다.

2019-07-31 06:27 UTC, yjll1019 commented on src/main/java/techcourse/myblog/domain/Article.java
> +	public Article(Long id, ArticleDto articleDto, User user) {
dto에 의해 article객체의 값을 넣는 방법보다 vo를 이용하기(O)

2019-07-31 06:27 UTC, yjll1019 commented on src/main/java/techcourse/myblog/domain/Article.java
>  	public boolean equals(Object o) {
id를 비교하는 메소드 생성(O)

2019-07-31 06:27 UTC, yjll1019 commented on src/main/java/techcourse/myblog/domain/User.java
> +	public void setId(Long id) {
접근 제어자 수정

2019-07-31 09:08 UTC, yjll1019 commented on src/main/java/techcourse/myblog/domain/Article.java
>  	private String contents;
`@Lob`을 통해서 DB 테이블이 생성될 때 해당 필드의 타입이 **varchar** 타입에서 **longtext** 타입으로 변경되면서 생성되는 것을 확인할 수 있었습니다!

2019-08-01 00:43 UTC, yjll1019 commented on src/main/java/techcourse/myblog/domain/Article.java
>  	public Article() {
네~ 수정했습니다.
좋은 문서 감사합니다~~~

2019-08-04 02:00 UTC, woowahan-pjs requested changes
피드백을 잘 반영해 주셨습니다. 👍 
간단한 생각거리를 남겼으니 코드에 반영해 주셔도 좋습니다.
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

2019-08-04 02:00 UTC, woowahan-pjs commented on build.gradle
>  	compile("mysql:mysql-connector-java:8.0.16")
`compile` 대신 `runtimeOnly`를 사용하면 어떨까요? 왜일까요?

2019-08-04 02:00 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/article/Article.java
> +package techcourse.myblog.article;
계층 우선 패키지 구조와 기능 우선 패키지 구조가 혼재되어 있어요. 아래의 글을 읽고 계층 우선 패키지 구조로 작성해 보세요.
https://www.slipp.net/questions/36

```suggestion
package techcourse.myblog.domain.article;
```

2019-08-04 02:00 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/comment/Comment.java
> +@DynamicInsert
`@DynamicInsert`가 필요한 시점이 언제일까요?

2019-08-04 02:00 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/comment/Comment.java
> +	public Comment(Contents contents) {
`User` 없이 `Comment`가 생성될 수 있나요?

2019-08-04 02:00 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/comment/Comment.java
> +	public Comment(Contents contents, User user) {
사용하지 않는 생성자입니다. 만약 사용한다면 자기 생성자 호출하는 `this()`를 사용하면 어떨까요?

2019-08-04 02:00 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/custom/LoginUserResolver.java
> +		return parameter.getParameterType().isAssignableFrom(User.class);
`@LoginUser` 어노테이션은 아래와 같이 쓰입니다.

```suggestion
		return parameter.hasParameterAnnotation(LoginUser.class);
```

2019-08-04 02:00 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/interceptor/AuthenticationInterceptor.java
> +		if ((!path.equals("/")) && (!path.equals("/signup")) && (!path.equals("/login") && (!path.equals("/users")))) {
만약 `path`이 null이라면 어떤 위험이 발생할까요? 그 위험을 피할 수 있는 방법도 찾아보면 좋을 것 같아요. 아래의 글이 도움 될 거예요.
https://www.jpstory.net/2014/02/09/avoid-nullpointerexception

2019-08-04 02:00 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/repository/UserRepository.java
> +	Optional<User> findByInformation_Email(String email);
`findByInformationEmail(String email)`은 동작하지 않던가요? 아래의 글이 도움 될 거예요.
https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.query-methods.query-property-expressions

2019-08-04 02:00 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/user/Information.java
> +	public Information(UserSignUpInfoDto userSignUpInfoDto) {
`Information`이 `UserSignUpInfoDto`를 의존하고 있네요. View의 요구 사항(콘솔 화면과 웹 페이지에서 받고자 하는 값의 형태 등)이 바뀐다면 Model도 그것에 영향을 받지 않을까요? Model은 외부의 영향을 받지 않도록 만드는 것이 좋습니다.

2019-08-04 02:00 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/user/User.java
> +		this.information.update(information);
VALUE OBJECT는 불변이 특징입니다.

```suggestion
		this.information = information;
```

2019-08-04 23:10 UTC, yjll1019 commented on src/main/java/techcourse/myblog/user/User.java
> +		this.information.update(information);
네! 수정했습니다~!

2019-08-04 23:16 UTC, yjll1019 commented on src/main/java/techcourse/myblog/comment/Comment.java
> +	public Comment(Contents contents, User user) {
수정했습니다!

2019-08-04 23:16 UTC, yjll1019 commented on src/main/java/techcourse/myblog/comment/Comment.java
> +	public Comment(Contents contents) {
아니요... 확인해보니 테스트 코드에서만 사용하고 있어서 삭제했습니다!

2019-08-04 23:36 UTC, yjll1019 commented on src/main/java/techcourse/myblog/repository/UserRepository.java
> +	Optional<User> findByInformation_Email(String email);
수정했습니다! 좋은 문서 감사합니다!

2019-08-05 00:02 UTC, yjll1019 commented on src/main/java/techcourse/myblog/interceptor/AuthenticationInterceptor.java
> +		if ((!path.equals("/")) && (!path.equals("/signup")) && (!path.equals("/login") && (!path.equals("/users")))) {
`path.equals("url")` 인 경우 `path` 가 null일 때 equals()메소드를 호출하는 과정에서 NullPointerException 이 발생하지만 
`"url".equals(path)` 일 때 `path`가 null인 경우에도 예외가 발생하지 않고 false가 리턴되는 것을 확인했습니다! 
감사합니다!

2019-08-05 00:33 UTC, yjll1019 commented on src/main/java/techcourse/myblog/custom/LoginUserResolver.java
> +		return parameter.getParameterType().isAssignableFrom(User.class);
수정했습니다~! 감사합니다!

2019-08-05 01:21 UTC, yjll1019 commented on src/main/java/techcourse/myblog/user/Information.java
> +	public Information(UserSignUpInfoDto userSignUpInfoDto) {
네! 수정했습니다.
매개변수로 DTO를 받지 않으려다 보니 
`public Information(String email, String username, String password, String githubUrl, String facebookUrl) ` 이렇게 생성자의 매개변수가 많아졌는데요.
혹시 이 부분을 보완할 수 있을까요??
githubUrl과 facebookUrl 을 SNS 클래스로 따로 묶어서 나타내어도 될까요?

2019-08-05 04:32 UTC, yjll1019 commented on build.gradle
>  	compile("mysql:mysql-connector-java:8.0.16")
수정했습니다! 제가 알아본 결과
`compile` 은 컴파일 시에 필요한 의존성 라이브러리를 나타냅니다.
`runtime` 은 런타임 시에 필요한 의존성 라이브러리인데요. 
제가 생각하기에 runtime 시 필요한 라이브러리를 compile 로 설정한다면
프로그램 compile 시 현재 불필요한 의존성이 추가되고 컴파일 속도가 느려지지 않을까요?

2019-08-05 10:23 UTC, yjll1019 commented on src/main/java/techcourse/myblog/comment/Comment.java
> +@DynamicInsert
제가 `@DynamicInsert` 를 오용했네요 .. 
`@CreateDate`와 `@EnableJpaAuditing` 을 이용해서 코드 수정했습니다!

2019-08-05 10:37 UTC, yjll1019 commented on src/main/java/techcourse/myblog/article/Article.java
> +package techcourse.myblog.article;
네! 수정했습니다. 좋은 문서 감사합니다~~!

2019-08-05 10:49 UTC, woowahan-pjs approved these changes
수많은 피드백을 반영하고자 대단히 고생 많으셨습니다. 💯 
좋은 개발자가 되기 위한 소중한 밑거름이 되었길 바랍니다.
이만 Merge 하겠습니다.

2019-08-05 10:49 UTC, merged