[댓글 기능] 희봉 미션 제출합니다.
woowacourse/jwp-blog pull request #115
Opened 2019-07-30 07:34 UTC by heebong

안녕하세요~ 이번에 리뷰를 받게된 희봉입니다!
부족한 코드 피드백 미리 감사드립니다 😄

2019-07-30 14:12 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
짧은 시간내에 구현하시느라 고생 많으셨습니다. 👍 
테스트 및 트랜잭션 관리, 연관관계 등 피드백 몇가지 피드백 추가했습니다.
확인 부탁드리고 궁금하신 점 있으시면 연락주세요. :)

2019-07-30 14:12 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/ArticleController.java
> +        User user = (User) httpSession.getAttribute("user");
User user = (User) httpSession.getAttribute("user"); 
Argument Resolver를 공부해서 적용해보면 어떨까요?

2019-07-30 14:12 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/ArticleController.java
> +        if (article.getAuthor().getId() != author.getId()) {
getter를 통한 비교가 아닌 메시지 전달을 통해 비교할 수 있지 않을까요?

ex) article.isAuthor(user)

2019-07-30 14:12 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/ArticleController.java
> +        Article article = articleRepository.findById(articleId).get();
article이 null인 경우에 대해서는  NPE가 발생 할 것 같습니다.
get()을 직접적인 획득 말고 orElseThrow등으로 null에 대한 예외 처리를 해보면 어떨까요?
(Optional.get은 일반적으로 지양하도록 하시는게 좋아요. :)  get을 쓴다면 Optional을 쓰는 이유가 없거든요.)

2019-07-30 14:12 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/ArticleController.java
> +        Article preArticle = articleRepository.findById(articleDto.getId()).get();
각 비즈니스 로직에 대해서 서비스를 분리하고, 트랜잭션을 관리해보면 어떨까요?
그럴 경우 굳이 save를 하지 않아도 영속성에 의해 변경이 반영 될 수 있어요.

또한 엔티티를 새로 생성하는 것이 아닌 preArticle.update(dto, user)등과 같이 메시지를 통해서 변경을 해보면 어떨까요?

2019-07-30 14:12 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +        Article article = articleRepository.findById(commentDto.getArticleId()).get();
서비스 레이어 분리 및 트랜잭션을 관리해서 조금 더 객체지향적으로 풀어보면 어떨까요?
ex) article.addComment(comment)

2019-07-30 14:12 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +    @DeleteMapping
CommentDTO를 받을 이유가 없어보여요 :)
 @DeleteMapping("/{commentId}")를 통해 ID 기반으로 삭제해도 충분하지 않을까요?
또한 현재 아무 user나 코멘트를 삭제할 수있을것같네요. :)

2019-07-30 14:12 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +        Comment comment = commentDto.toComment(user, article);
수정시에도 권한에 대한 관리가 없어보입니다. :)

2019-07-30 14:12 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +    @PutMapping
마찬가지로 굳이 Comment 엔티티를 새로 만들지 않고
 @PutMapping("/{commentId}")를 통해 Comment를 영속성으로 가져와서 변경하도록 해보면 어떨까요?
서비스레이어를 분리할 경우 굳이 save를 하지 않아도 변경 반영이 가능합니다. :)

2019-07-30 14:12 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/dto/ArticleDto.java
> +            return new Article(id, title, contents, coverUrl, author);
id를 통한 직접 생성 할 일은 없을 것 같아요. :) 앞에 피드백 반영해보고 id에 대한 부분은 지워도 좋을 것 같네요!

2019-07-30 14:12 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/User.java
> +    @Size(max = 20)
password, email에 대한 validation도 추가해야하지 않을까요?

2019-07-30 14:12 UTC, phs1116 commented on src/test/java/techcourse/myblog/controller/ArticleControllerTests.java
> +    void deleteArticleByIdTest() {
작성자가 아닐 경우 삭제 및 수정 불가능 케이스에 대한 테스트도 추가하면 좋을 것 같습니다. :)

2019-07-30 14:12 UTC, phs1116 commented on src/test/java/techcourse/myblog/controller/CommentControllerTests.java
> +    void comment삭제() throws Exception {
삭제 및 수정에 대한 예외케이스 테스트도 작성해보면 좋을것같네요. :)

2019-07-30 14:12 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/ArticleController.java
> +    @Transactional
@Transactional을 Controller에 쓰는것보다 Service에서 유지하는것이 일반적인 권장 사항입니다.
https://stackoverflow.com/questions/23118789/why-we-shouldnt-make-a-spring-mvc-controller-transactional

서비스 레이어를 분리하고 거기서 작업해보면 어떨까요? :)

2019-07-30 14:12 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/Comment.java
> +    private Article article;
각 엔티티들의 역할이 없는 것 같습니다. 
각 연관관계 및 엔티티들을 좀 더 활용해보면 어떨까요?

2019-07-31 08:33 UTC, heebong commented on src/main/java/techcourse/myblog/controller/ArticleController.java
> +        User user = (User) httpSession.getAttribute("user");
Argument Resolver를 적용했는데 제대로 한 것인지 모르겠습니다ㅠ 따로 interceptor도 추가했는데, 아무래도 불필요한 작업을 한 것 같아 interceptor없이 할 수 없는지 궁금합니다!

2019-07-31 08:33 UTC, heebong commented on src/main/java/techcourse/myblog/controller/ArticleController.java
> +        if (article.getAuthor().getId() != author.getId()) {
변경했습니다!

2019-07-31 08:34 UTC, heebong commented on src/main/java/techcourse/myblog/controller/ArticleController.java
> +        Article article = articleRepository.findById(articleId).get();
optional에서 get 대신 orElseThrow로 변경했습니다!

2019-07-31 09:13 UTC, heebong commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +    @DeleteMapping
comment를 delete할 때 id만 받는걸로 수정했습니다! 또한 comment에서 수정페이지접근/수정/삭제시 user를 확인하는 로직을 추가했습니다!

2019-07-31 09:14 UTC, heebong commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +        Comment comment = commentDto.toComment(user, article);
comment에서 수정페이지접근/수정/삭제시 user를 확인하는 로직을 추가했습니다!

2019-07-31 09:15 UTC, heebong commented on src/main/java/techcourse/myblog/controller/ArticleController.java
> +    @Transactional
서비스 레이어를 분리했습니다! 확인 부탁드립니다!

2019-07-31 09:29 UTC, heebong commented on src/main/java/techcourse/myblog/controller/ArticleController.java
> +        Article preArticle = articleRepository.findById(articleDto.getId()).get();
서비스를 만들어서 컨트롤러에선 repository를 사용하지 않도록 변경했습니다.
하지만 엔티티를 불변의 객체로 만들고싶어서 + 엔티티에서 dto를 사용하고 싶지 않아서 영속성을 사용하지 않고 새로운 엔티티를 만들어서 저장하는 방법을 선택했습니다. 

엔티티를 불변으로 유지하고 싶은데 다른 방법이 있는지, 계속 새로 생성하는것 보단 변경하는 것이 더 좋은 방법인지 질문 드립니다ㅠ

2019-07-31 09:31 UTC, heebong commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +    @PutMapping
위와 동일하게 질문 드립니다!

2019-07-31 09:31 UTC, heebong commented on src/main/java/techcourse/myblog/controller/dto/ArticleDto.java
> +            return new Article(id, title, contents, coverUrl, author);
엔티티를 불변으로 만들고 엔티티에선 dto를 모르게 하고싶어서 만들었는데 더 좋은 방법이 있는지 질문드립니다! (위와 동일한 질문입니다!)

2019-07-31 09:54 UTC, heebong commented on src/main/java/techcourse/myblog/domain/User.java
> +    @Size(max = 20)
@Pattern 을 이용해서 추가했습니다. 확인 부탁드립니다!

2019-07-31 10:43 UTC, heebong commented on src/test/java/techcourse/myblog/controller/ArticleControllerTests.java
> +    void deleteArticleByIdTest() {
테스트 추가했습니다! 확인 부탁드립니다!

2019-07-31 10:43 UTC, heebong commented on src/test/java/techcourse/myblog/controller/CommentControllerTests.java
> +    void comment삭제() throws Exception {
테스트 추가했습니다. 확인 부탁드립니다!

2019-07-31 10:56 UTC, heebong commented on src/main/java/techcourse/myblog/domain/Comment.java
> +    private Article article;
어떤 말씀이신지 잘 이해가 가지 않습니다ㅠㅠ 혹시 예를 들어 설명해주실 수 있으신가요..??

2019-07-31 10:58 UTC, heebong commented
안녕하세요 화투님! 자세한 피드백 감사드립니다 😄 
피드백을 반영하다보니 기본적인 것을 많이 못지켜서 반성을 하게되었습니다...ㅠ
우선 하면서 궁금했던 부분은 다음과 같습니다.

1. 위에도 적었는데 entity를 불변으로 사용하려고 영속성을 사용한 update를 하지 않고 새로운 entity를 생성하는것으로 진행했습니다. 혹시 이런 방법이 더 안좋은것인지, 더 좋은 방법이 있는지 궁금합니다.

2. 서비스를 분리했는데 지금 제 코드에선 db와 관련된 부분만 서비스로 분리했습니다. 아직 어떤 기능들을 서비스로 분리해야할지 모르겠어서 혹시 지금 코드에서 더 많은 기능들을 서비스로 분리할 수 있는지 궁금합니다.

3. CommentController와 관련된 테스트코드는MockMvc로 진행했는데 인수테스트는 webTestClient로 하는게 더 좋다는 이야기를 듣고 webTestClient로 만든 테스트를 추가했습니다. 그래서 CommentController와 관련된 테스트 파일이 두개가 생겼는데 이름을 어떻게 지어야할지 모르겠습니다... webTestClient로 구현한 테스트 파일은 CommentControllerTestWebClientTest로 지었는데 더 좋은 방법이 있을지 궁금합니다!

피드백을 잘 반영한것인지 모르겠습니다ㅠㅠ 확인 및 재피드백 부탁드립니다. 감사합니다!

2019-08-01 18:31 UTC, phs1116 requested changes
안녕하세요. 리뷰어 화투입니다.
전체적으로 피드백 반영 👍 
많이 고민 하신 것 같아요.
질문하신 사항과 몇가지 피드백 추가했는데 참고 부탁드립니다.
궁금하신 사항 있으시면 언제든지 연락주세요 :)

2019-08-01 18:31 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/dto/ArticleDto.java
> +            return new Article(id, title, contents, coverUrl, author);
영속성을 활용하지 않으면 JPA를 사용하는 의미가 없습니다.
엔티티는 상태의 변경이 필수불가결한 객체이구요.
물론 이뮤터블은 좋지만 이뮤터블로 유지해야되는 부분과, 뮤터블한 부분에 대해서 구분해서 사용하면 좋을 것 같습니다. :)

2019-08-01 18:31 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/ArticleController.java
> +        log.debug(">>> put article ArticleDto : {}, user : {}", articleDto, user);
Transactional 및 영속성을 활용하여 기존 article을 변경해보면 어떨까요?
articleDto에 ID가 굳이 필요한지도 의문이 드네요.

2019-08-01 18:31 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/ArticleController.java
> +        Article article = articleService.saveArticle(articleDto.toArticle(user));
article의 update에서 유저에 대한 체크를 해야 도메인 로직이 더욱 드러나지 않을까요?
(article은 올바른 사용자가 아니면 수정하지 못한다)
현재 구조면 entity는 그저 구조체 이상의 역할을 못하는 것 같습니다.
서비스 혹은 컨트롤러가 아니라 도메인 객체가 무겁게 가져가는게 좋은 방향으로 보입니다.

2019-08-01 18:31 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +        commentService.saveComment(comment);
마찬가지로 서비스 레이어 및 영속성을 활용하도록 권해드려요.

2019-08-01 18:31 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/Comment.java
> +    private Article article;
JPA를 쓴다는것 자체가 객체지향적인 프로그래밍을 한다는 이야기 입니다.
현재 Article 및 User라는 연관관계를 가지고 있지만 이를 활용하지 못하고 있어서 말씀드렸습니다.

예: comment.isAuthor(user) 등등

2019-08-01 18:31 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +        if (user.isNotMatch(comment.getUser())) {
getter를 통한 통신이 아닌 메시지를 통해서 작성하도록 연습하면 좋을 것 같아요.

2019-08-01 18:31 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +        commentService.deleteComment(comment);
비즈니스 로직이 너무 컨트롤러에 드러나있는 것 같습니다.
Comment를 찾고 권한을 체크하며 이를 지우는 행위 자체는 컨트롤러가 아니라 서비스가 책임져야하지 않을까요?

2019-08-01 18:31 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/User.java
> +    @Size(max = 20)
👍

2019-08-01 18:31 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/CommentService.java
> +public class CommentService {
서비스가 그저 Repository의 릴레이 말고 역할이 없는 것 같아요.
레이어드 아키텍쳐에서 각 레이어가 어떤 역할을 가지고있는지 고민해보고
서비스를 조금 더 무겁게 가져가보면 어떨까요?

2019-08-01 18:31 UTC, phs1116 commented on src/test/java/techcourse/myblog/controller/CommentControllerTests.java
> +public class CommentControllerTests extends MyblogApplicationTests {
MockMvc를 통한 테스트는 그냥 컨트롤러 테스트로,
인수테스트는 AcceptanceTest로 이름 지으면 될 것 같네요. :)

2019-08-03 09:39 UTC, heebong commented on src/main/java/techcourse/myblog/controller/ArticleController.java
> +        log.debug(">>> put article ArticleDto : {}, user : {}", articleDto, user);
각 dto에서 id필드를 삭제했습니다. 확인 부탁드립니다!

2019-08-03 09:52 UTC, heebong commented on src/main/java/techcourse/myblog/controller/ArticleController.java
> +        Article article = articleService.saveArticle(articleDto.toArticle(user));
도메인에게 가도록 변경했습니다. 확인 부탁드립니다!

2019-08-03 09:52 UTC, heebong commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +        commentService.saveComment(comment);
영속성을 사용하도록 변경했습니다. 확인 부탁드립니다!

2019-08-03 09:53 UTC, heebong commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +        if (user.isNotMatch(comment.getUser())) {
변경했습니다. 확인 부탁드립니다!

2019-08-03 09:53 UTC, heebong commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +        commentService.deleteComment(comment);
변경했습니다. 확인 부탁드립니다!

2019-08-03 09:54 UTC, heebong commented on src/main/java/techcourse/myblog/service/CommentService.java
> +public class CommentService {
변경했습니다. 확인 부탁드립니다!

2019-08-03 09:55 UTC, heebong commented on src/test/java/techcourse/myblog/controller/CommentControllerTests.java
> +public class CommentControllerTests extends MyblogApplicationTests {
피드백 감사드립니다! 지금은 전부 인수테스트만 만들어서 이름을 모두 AcceptanceTest로 바꿔야 할거같은데 우선 Comment만 변경했습니다ㅠ 다음에 더 변경하겠습니다!

2019-08-03 10:09 UTC, heebong commented
안녕하세요 화투님! 자세한 피드백 감사드립니다 😄 
피드백을 반영하다보니 제가 레벨1때 배웠던 객체지향의 특징 및 지향점들을 전혀 고려하지 않았다는걸 깨달았습니다...ㅠ
새로운 프레임워크와 기술을 적용하는데 집중해서 기본적인 중요한 것들을 놓쳤네요.. 아직 고칠부분이 더 많아보이지만 우선 리뷰요청을 드립니다.
(특히 jpa는 단순히 테이블이 아니라 객체로 생각해야 한다는걸 이제 알았네요..)
아직 부족한점이 많지만.. 피드백 부탁드립니다! 미리 감사드립니다~!

2019-08-04 11:08 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
전체적인 피드백 반영 👍 
마지막으로 예외에 관한 간단한 피드백 몇가지 추가했습니다.
참고 부탁드리고 궁금하신 점 있으시면 언제든지 DM주세요 :)

2019-08-04 11:08 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/AccountController.java
> +        } catch (RuntimeException e) {
RuntimeException으로 예외를 처리하는것이 아닌 ControllerAdvice 및 Exception Handler를 공부해서 적용해보면 어떨까요?
그리고 RuntimeException으로 예외를 처리할 경우 이메일 중복 케이스가 아닌 경우에도 중복으로 내려갈 것 같습니다. :)

2019-08-04 11:08 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/AccountController.java
> +        } catch (RuntimeException e) {
어떤 상황에 대한 예외케이스인지도 로그로 출력을 하는게 좋지 않을까요?
예외를 발생하고 그대로 무시하고 넘겨버리기 때문에 문제 발생시 파악이 어려울 수도 있을것 같습니다. :)

2019-08-04 11:08 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/CommentService.java
> +    public boolean isSuccessUpdate(long id, CommentDto commentDto, User user) {
메서드의 이름은 isSuccessUpdated으로 상태 여부를 파악하는 메서드로 보이지만 실제로는 update를 실행하고 있네요.
실제 구현과 시그너쳐가 일치하지 않은 것 같습니다.
CQS에 대해서 공부해보고 적용해보면 좋을 것 같아요.
https://martinfowler.com/bliki/CommandQuerySeparation.html

실패 케이스에 대한 경우는 true/false의 결과가 아닌 예외를 통해 핸들링하는게 더 좋지 않을까요?

2019-08-04 11:08 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/CommentService.java
> +        return commentRepository.findById(id).orElseThrow(RuntimeException::new);
RuntimeException, IllegalArgumentException을 그대로 사용하지 않고 비즈니스를 명확하게 담고있는 예외를 사용해보면 어떨까요?

2019-08-04 11:08 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/Comment.java
> +        checkUpdateCondition(commentDto, user);
this.user로 체크하게 되는 것 같은데 맞나요? :)

2019-08-05 12:37 UTC, heebong commented
안녕하세요 화투님! 희봉입니다
우선 늦게 리뷰요청을 드려 죄송합니다ㅠ
말씀해주신 ControllerAdvice를 사용했습니다.
피드백 미리 감사드립니다!

2019-08-05 12:48 UTC, heebong commented on src/main/java/techcourse/myblog/controller/AccountController.java
>              return "signup";
이부분도 ControllerAdvice로 빼고싶은데 AccountController의 기본 로직을 변경하지 않는 방법을 모르겠습니다ㅠ (Errors를 response에 함께 보냄) UserDuplicateEmailException을 BindException을 상속받는것으로 변경했을 때도 안돼서... 좀 더 확인해야할거같습니다!ㅠㅠ

2019-08-05 12:48 UTC, heebong commented on src/main/java/techcourse/myblog/service/LoginService.java
> +        return user;
로그인 기능에서 비밀번호가 다르면 예외를 던지는 부분을 지금은 서비스에서 하는데 이걸 도메인에서 해야하는지 궁금합니다! 도메인에선 true/false만 제공하고 서비스에서 예외를 던지는게 맞아보이는데.. 어떤게 더 좋을지 궁금합니다!

2019-08-05 19:10 UTC, phs1116 approved these changes
안녕하세요! 리뷰어 화투입니다.
전체적인 예외정리 👍 
이번 단계 머지하도록 하겠습니다.
간단한 피드백 추가했는데 참고 부탁드릴게요.
지금까지 개발 하시느라 정말 수고 많으셨습니다. :)

2019-08-05 19:10 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/LoginService.java
> +        return user;
케이스마다 많이 다를 것 같아요.
isNotMatchedPassword와 같이 '비밀번호를 비교한다'라는 기능 자체가
특정 예외에 국한된 기능이 아니기 때문에 해당 케이스의 같은 경우에는 서비스에서 처리하는게 적절해 보입니다.

2019-08-05 19:10 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/ExceptionAdvice.java
> +    @ExceptionHandler(CommentNotMatchedException.class)
핸들링 과정이 똑같다면 모아서 처리하셔도 됩니다.
ExceptionHandler가 받는 예외 인자는 배열로 받습니다. :)

2019-08-05 19:10 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/AccountController.java
>              return "signup";
BindException 자체는 Validation Exception이기 때문에
Business Exception인 UserDuplicateEmailException와는 적합하지 않을 수 있을 것 같습니다.
별도의 커스텀 Validator를 만들어 중복을 검증하는 형태로 가거나 현재 방법 외에는 저도 크게 떠오르지 않네요. :)

2019-08-05 19:10 UTC, merged