[댓글 기능] 아이크 미션 제출합니다.
woowacourse/jwp-blog pull request #119
Opened 2019-07-30 07:52 UTC by ike5923

기한 내에 최대한 제출하기 위해 빠르게 기능 구현 위주로 진행했습니다.
미흡한 테스트 코드에 대해서는 계속해서 수정해서 반영하도록 하겠습니다.

이번 미션을 진행하면서 궁금했던 점이 몇가지 있었는데요
@transactional을 사용하면서 db에 접근하는 모든 method에 annotation을 적용했는데
어떤 기준으로 @transactional을 사용하는 지 궁금합니다!!

많은 피드백 부탁드립니다ㅎㅎ

2019-07-31 00:39 UTC, woowahanCU commented on src/main/java/techcourse/myblog/domain/Comment.java
> +    @Length(max = MAX_CONTENTS_LENGTH)
현재 구조에서는 contents는 varchar(200)으로 세팅될텐데요. 더 긴 문자열을 받을 수 있도록 데이터타입을 바꿔주는 것은 어떨까요
지금과 같이 데이터 크기를 결정하기 힘든 큰 크기의 데이터는 @lob을 쓰는 것도 한번 고려해보세요.

2019-07-31 00:40 UTC, woowahanCU commented on src/main/java/techcourse/myblog/domain/Comment.java
> +    @JoinColumn(name = "articleId")
👍

2019-07-31 00:43 UTC, woowahanCU commented on src/main/java/techcourse/myblog/domain/User.java
> +    public void updateNameAndEmail(UserRequestDto userRequestDto) {
Dto와 Domain model이 직접 연관관계가 있어 결합도가 증가하네요.
이 경우엔 Presentation Layer의 변경사항이 도메인 모델에까지 전파될 거 같아요.
그럼 Dto를 따로 분리하는 의미도 퇴색될 거 같구요.

2019-07-31 00:45 UTC, woowahanCU commented on src/main/java/techcourse/myblog/interceptor/login/LoginInterceptor.java
> +            log.info("uri : {} ", request.getRequestURI());
config에서 pathPattern을 세팅해준 것과 별도로 검사하는 이유가 있을까요?

2019-07-31 00:46 UTC, woowahanCU commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +    public Article save(ArticleRequestDto articleRequestDto, UserResponseDto userResponseDto) {
질문하신 부분에 답하자면, Transactional은 트랜잭션이 묶여야 하는 단위별로 붙여주시면 된다고 생각합니다.
지금처럼 모든 method가 사용된다면 Class에 붙여두고 readOnly만 별도로 설정해줘도 되겠네요.

2019-07-31 00:48 UTC, woowahanCU commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +    private final CommentRepository commentRepository;
CommentService가 있는데 CommentRepository의 의존성을 직접 주입한 이유가 따로 있을까요

2019-07-31 00:49 UTC, woowahanCU commented on src/main/java/techcourse/myblog/service/CommentService.java
> +                .orElseThrow(UserException::new);
각 Serviced간의 역할이 모호한 것 같습니다. 이런 부분은 CommentService가 직접 userRepository에 접근하기 보다는 UserService에게 메시지를 보내는 것은 어떨까요

2019-07-31 00:49 UTC, woowahanCU commented on src/main/java/techcourse/myblog/service/UserService.java
> +    public UserResponseDto addUser(UserRequestDto userRequestDto) {
👍

2019-07-31 00:50 UTC, woowahanCU commented on src/main/java/techcourse/myblog/service/UserService.java
> +        User user = userRepository.save(DtoConverter.convert(userRequestDto));
DtoConverter를 두기보다는 각각의 Dto에 대한 변환로직을 따로 관리하는것이 좋다고 생각합니다.
현재 구조에서는 한 도메인의 표현영역의 변경이 DtoConverter에 영향을 미치게 되어 방대한 클래스가 될 가능성이 높아보입니다.

2019-07-31 00:50 UTC, woowahanCU commented on src/main/java/techcourse/myblog/service/UserService.java
>      @Transactional()
()는 지워주셔도 됩니다.

2019-07-31 00:52 UTC, woowahanCU commented on src/main/java/techcourse/myblog/utils/page/PageRequest.java
>          this.orderby = orderby;
SpringData의 pageable을 활용하는 것은 어떨까요

2019-07-31 00:54 UTC, woowahanCU commented on src/main/java/techcourse/myblog/web/CommentController.java
> +    @PostMapping("/comment/{articleId}")
/comment가 공통적으로 사용되고 있는데요.
상수 처리하여 중복을 제거할 수 있지 않을까요
RequestMapping 등을 활용해보세요.
그리고 추가적으로 Rest에서는 복수형을 사용합니다.

https://blog.mwaysolutions.com/2014/06/05/10-best-practices-for-better-restful-api/

2019-07-31 00:55 UTC, woowahanCU commented on src/main/java/techcourse/myblog/web/CommentController.java
> +        commentService.checkAuthentication(userResponseDto, commentId);
권한체크는 어느부분에서 체크하는 것이 좋을까요?
추가적으로 관련한 단위 테스트 코드도 같이 작성해보는 것도 좋겠네요.

2019-07-31 00:56 UTC, woowahanCU commented on src/main/java/techcourse/myblog/web/ControllerExceptionHandler.java
> +    @ExceptionHandler(CommentAuthenticationException.class)
http status 는 몇번으로 응답하는 것이 좋을까요?

2019-07-31 00:56 UTC, woowahanCU reviewed
테스트코드는 말씀하신대로 에러가 많이 발생하고 있어서 수정 반영하시면 다시 확인해볼게요

2019-07-31 00:57 UTC, woowahanCU requested changes
안녕하세요! 리뷰어 CU 입니다.
짧은 시간인데 깔끔하게 잘 구현하셨네요. 👍 
몇가지 피드백 남겼으니 확인해보시고 궁금한점 있으면 DM 남겨주세요~

2019-07-31 01:59 UTC, ike5923 commented on src/main/java/techcourse/myblog/domain/Comment.java
> +    @Length(max = MAX_CONTENTS_LENGTH)
LOB에 대해 찾아보았습니다.

상당한 양의 데이터를 가지는 객체(lob)가 메모리에 그대로 올라갈 경우 성능에 문제가 생길 수 있습니다. hibernate에서는 이러한 lob객체를 스트림으로 바로 넣어서 처리하기 때문에 메모리 사용이 없고 속도도 빠릅니다.

Comment의 contents와 Article의 contents에 @Lob을 적용했습니다!

2019-07-31 02:08 UTC, ike5923 commented on src/main/java/techcourse/myblog/interceptor/login/LoginInterceptor.java
> +            log.info("uri : {} ", request.getRequestURI());
불필요하다고 생각해서 지웠습니다!

2019-08-03 13:29 UTC, ike5923 commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +    public Article save(ArticleRequestDto articleRequestDto, UserResponseDto userResponseDto) {
수업을 듣고 나서 transaction에 대해서 잘못 이해하고 있었다는 것을 알았습니다. 트랜잭션이 묶여야 하는 곳에 @transactional을 붙였습니다!

2019-08-04 17:13 UTC, ike5923 commented on src/main/java/techcourse/myblog/domain/User.java
> +    public void updateNameAndEmail(UserRequestDto userRequestDto) {
dto대신 entity로 변환하여 전달하는 방식으로 domain model과의 의존관계를 끊어주었습니다.

2019-08-04 17:22 UTC, ike5923 commented on src/main/java/techcourse/myblog/service/CommentService.java
> +                .orElseThrow(UserException::new);
service layer에 대한 이해가 부족했던 것 같습니다. 각각의 service들이 무분별하게 repository를 지니고 있어서 각각의 service를 나누는 의미가 사라졌네요. 각각의 service들이 해당 repository와 다른 service를 참조하도록 변경했습니다!

2019-08-04 17:24 UTC, ike5923 commented on src/main/java/techcourse/myblog/service/UserService.java
> +        User user = userRepository.save(DtoConverter.convert(userRequestDto));
domain 내의 각각의 model에 대한 assembler를 만들어 관리하도록 변경했습니다.

추가적으로 각각의 dto의 역할을 세분화하였습니다.(valid 검증을 위해)

2019-08-04 17:24 UTC, ike5923 commented on src/main/java/techcourse/myblog/service/UserService.java
>      @Transactional()
수정했습니다!

2019-08-04 17:28 UTC, ike5923 commented on src/main/java/techcourse/myblog/utils/page/PageRequest.java
>          this.orderby = orderby;
지난 미션때, pagable로 구현했다가 page size에 대한 limit나 시작 page 등 page에 대한 세부정보를 class로 관리하기 위해 pageRequest를 사용했습니다. pageRequset를 사용하는 경우와의 큰 차이가 있을까요?

2019-08-04 17:31 UTC, ike5923 commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +    private final CommentRepository commentRepository;
service에 의존하기 보다는 repository에 의존하는 것이 더 안정성있다고 생각했습니다. 하지만 이렇게 모든 model의 repository를 주입하게 될 경우 service에 역할이 모호해질 것 같네요.

2019-08-04 18:05 UTC, ike5923 commented on src/main/java/techcourse/myblog/web/CommentController.java
> +    @PostMapping("/comment/{articleId}")
/comment와 더불어 ArticleController와 UserController의 url들을 관리하기 위해 URL 이라는 constant class를 생성하여 관리하도록 변경했습니다.

2019-08-04 18:17 UTC, ike5923 commented on src/main/java/techcourse/myblog/web/ControllerExceptionHandler.java
> +    @ExceptionHandler(CommentAuthenticationException.class)
클라이언트의 권한에 관한 응답으로 401입니다!

exception handler에 각각의 http status 응답형태에 대해 명시했습니다!

2019-08-04 21:06 UTC, ike5923 commented on src/main/java/techcourse/myblog/web/CommentController.java
> +        commentService.checkAuthentication(userResponseDto, commentId);
service layer에서 권한 체크하도록 변경했습니다. 권한에 관한 테스트 코드도 추가했습니다!

2019-08-05 06:16 UTC, brainbackdoor commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +    private final CommentRepository commentRepository;
엇 어떤 의미인지 잘 이해가 되지 않습니다. 
ArticleService에서 모든 Repository와 연관관계를 가지는 것이 더 안정성있다고 생각한다는 의미이실까요?

2019-08-05 06:22 UTC, woowahanCU commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +    private final CommentRepository commentRepository;
어라, 이건 어떤 의미이려나요? ArticleService가 모든 Repository와 연관관계를 맺는 것이 더 안정성있다는 의미이신걸까요? 👀

2019-08-05 08:12 UTC, woowahanCU commented on src/main/java/techcourse/myblog/web/CommentController.java
> +        UserResponse userResponse = (UserResponse) SessionUtil.getAttribute(session, USER);
Reponse가 일반적으로 사용되던 방식과 달라서 좀 생소하네요. SimpleUserInfo 등의 이름은 어떤까요

2019-08-05 08:13 UTC, woowahanCU commented on src/main/java/techcourse/myblog/domain/User.java
>      private String email;
java bean validator를 사용하여 email 등 포맷의 유효성 검증을 할 수 있어요

https://www.baeldung.com/javax-validation

2019-08-05 08:42 UTC, woowahanCU commented on src/main/java/techcourse/myblog/domain/article/ArticleAssembler.java
> +package techcourse.myblog.domain.article;
이렇게 package를 나눌거면 도메인별로 구성하는 것은 어떨까요

2019-08-05 08:43 UTC, woowahanCU approved these changes
피드백 반영 잘해주셨네요! 💯 미션 진행하느라 수고하셨습니다! 😀

2019-08-05 08:43 UTC, merged