[댓글 기능] 이바 미션 제출합니다.
woowacourse/jwp-blog pull request #124
Opened 2019-07-30 08:03 UTC by seonghun127

안녕하세요. 쏘쏘! 리뷰이 이바입니다.

다른 때보다 미션 수행 기간이 짧았던 만큼 만족스럽지 않은 상태에서 PR을 보내게됐습니다.

이전과 마찬가지로 테스트 코드 작성이 정말 어려웠습니다.
상속, Mockito 등을 사용하면 어떠냐는 피드백을 받았지만 적용하는데 실패하여 
결국 저만의 방법(?)으로 테스트 코드를 작성했습니다.

현재 테스트 코드 전체를 돌리면 무수히 깨지는 상황이고 Test 클래스 별로 테스트 코드가 바르게 돌아가게끔까지
코드를 짰습니다. 이렇게 PR을 보내고 리펙토링을 진행하려 합니다.

부족한 부분이 많을테니 거침없이 지적해주시면 감사하겠습니다.

2019-07-30 13:17 UTC, ssosso requested changes
안녕하세요, 이바~ 쏘쏘입니다:) (저와의 코드리뷰에서는 '님' 어미를 사용하지 않으셔도 됩니다)
만족스럽지 않으셨다고 했는데 정갈한 코드네요. 고생하셨습니다.
전체 테스트 코드를 실행하면 실패하는 부분은 확인해서 반드시 고치면 좋을 것 같습니다.
피드백 드린 부분 외에 궁금한 부분이 있으시면 말씀주세요:)

2019-07-30 13:17 UTC, ssosso commented on src/main/java/techcourse/myblog/article/controller/ArticleController.java
>          return "redirect:/articles/" + newArticleId;
다른곳에서도 RedirectView를 사용하셨네요. redirect관련하여 통일해 주시면 좋을 것 같습니다.

2019-07-30 13:17 UTC, ssosso commented on src/main/java/techcourse/myblog/article/controller/ArticleController.java
> +        articleService.deleteById(articleId, userSession.getId());
삭제가 성공했는지 실패했는지는 exception이 발생유무로만 체크되는 듯 하네요. deleteById의 반환값에 따라서도 성공유무를 체크하여 결과를 반환해 주는게 좋아보입니다.

2019-07-30 13:17 UTC, ssosso commented on src/main/java/techcourse/myblog/article/service/ArticleService.java
> +        User author = userRepository.findById(authorId).orElseThrow(NotFoundUserException::new);
잘 작성해 주셨네요. 👍 
만약 실무적으로 접근한다면 예외상황 발생 시 NotFoundUserException에 authorId를 함께 전달하여 로그를 기록 & 실패시 해당값을 함께 전달 등으로 처리해야 합니다. 키값을 기록하는 것은 매우 큰 차이가 있습니다.

2019-07-30 13:17 UTC, ssosso commented on src/main/java/techcourse/myblog/comment/dto/CommentDto.java
> +public class CommentDto {
하나의 클래스에 이너 클래스를 여러개 선언하셨네요. 동작하는데는 문제 없지만 좋은 습관은 아닙니다. 차라리 comment 페키지를 만들어 3개의 클래스를 각각 선언해 주는 것이 명시적으로 사용하기 훨씬 용이해 보입니다. 지금은 간단한 dto지만 확장되어 길어진다면 점점 가독성이 떨어질 것입니다.

2019-07-30 13:17 UTC, ssosso commented on src/main/java/techcourse/myblog/comment/dto/CommentDto.java
> +public class CommentDto {
`@Data` 어노테이션의 사용은 지양하는 편이 좋습니다. 롬복 어노테이션과 관련하여 주의 사항을 적은 블로그를 공유합니다.
https://kwonnam.pe.kr/wiki/java/lombok/pitfall

2019-07-30 13:17 UTC, ssosso commented on src/main/java/techcourse/myblog/comment/service/CommentService.java
> +public class CommentService {
RequiredArgsConstructor 사용은 지양
필요한 Field로 Constructor 를 직접 만들면 어떨까요~?
같은 타입의 필드 선언 순서를 나중에 바꿀 경우 문제가 발생 소지가 있습니다. 개인적으로 생성자를 명시적으로 놓고 사용한다면 DI이후 필드값에 대한 추가적인 설정 또한 용이합니다.

2019-07-30 13:17 UTC, ssosso commented on src/test/java/techcourse/myblog/comment/CommentDataForTest.java
> +    public static final String UPDATED_CONTENTS = "쏘쏘 더멋져";
감사합니다:)

2019-07-30 13:17 UTC, ssosso commented on src/main/java/techcourse/myblog/comment/domain/Comment.java
> +    public void updateComment(String contents) {
void로 선언한 메서드는 모두 반환값이 있도록 변경하면 어떨까요~?

2019-07-30 13:17 UTC, ssosso commented on src/test/java/techcourse/myblog/comment/controller/CommentControllerTest.java
> +                .exchange()
webTestClient.~.exchange() 까지 반복되는 코드를 몇 가지 종류로 나누어서 메서드를 만들면 재활용성이 높아지지 않을까요~?

2019-07-31 02:06 UTC, seonghun127 commented on src/main/java/techcourse/myblog/article/controller/ArticleController.java
>          return "redirect:/articles/" + newArticleId;
수정했습니다! 👍

2019-07-31 07:45 UTC, seonghun127 commented on src/test/java/techcourse/myblog/comment/controller/CommentControllerTest.java
> +                .exchange()
반영했습니다!! 👍

2019-07-31 08:10 UTC, seonghun127 commented on src/main/java/techcourse/myblog/article/service/ArticleService.java
> +        User author = userRepository.findById(authorId).orElseThrow(NotFoundUserException::new);
반영했습니다!! 👍

2019-07-31 08:29 UTC, seonghun127 commented on src/main/java/techcourse/myblog/comment/service/CommentService.java
> +public class CommentService {
질문 있습니다!

자바는 기본적으로 같은 타입(인터페이스, 클래스)의 인스턴스라도 인스턴스의 이름으로 구별한다고 알고 있습니다. 다시 말해 하나의 인터페이스의 구현체가 여럿 있어도 해당 인터페이스를 의존 주입될 인스턴스 이름을 보고 알맞게 주입될 것입니다.

그렇다면 필드 순서 변경에 따른 `@RequiredArgsConstructor` 와 생성자 주입의 차이를 잘 모르겠습니다. 쏘쏘가 말씀해주신 문제가 일어날 수 있는 경우는 어떤 경우인가요?

2019-07-31 08:43 UTC, seonghun127 commented on src/main/java/techcourse/myblog/comment/domain/Comment.java
> +    public void updateComment(String contents) {
질문 있습니다!

메서드에 void 반환을 두는 것이 좋은 것은 아니라고 들었습니다.
그렇지만 현재 코드에서 update가 진행될 때, 어떤 값을 반환 받아야할 필요가 없다고 
판단되어 void로 두었습니다. 

해당 메서드를 반환값이 있도록 변경한다면 얻을 수 있는 이점이 무엇일까 고민해봤을 때,
테스트 코드 작성이 조금더 쉬워질 거 같다는 생각이 들었습니다. 테스트 코드 작성이 수월해지면 좋겠지만
단지 그 이유만을 위해 프로덕션 코드를 바꾼다는 것에 대해 살짝 이질감(?)이 듭니다.

쏘쏘의 말처럼 변경했을 경우 어떠한 이점이 있는지 궁금합니다.

2019-08-01 06:26 UTC, seonghun127 commented on src/main/java/techcourse/myblog/comment/dto/CommentDto.java
> +public class CommentDto {
반영했습니다!

그동안 dto 클래스 내부에 중첩 클래스를 두면서 `UserDto.`을 입력할 시 사용할 수 있는 여러 dto 클래스를 바로 확인할 수 있고 중첩 클래스의 이름에 따라 적절하게 사용하는데 용이하여 이와같이 프로그래밍했습니다.

그렇지만 단순히 CRUD 기능만 있을 시에는 상관 없겠지만 그 외 다양한 dto 클래스가 요구될 경우 이를 어느 dto 내부에 중첩클래스로 둬야할지 애매할 수 있고 앞서 언급해주신바와 같이 가독성이 떨어질 수 있다는 생각이 들었습니다.

이전 리뷰어 분들께서도 같은 피드백을 주셨지만 그에 대해 저의 생각을 이야기하면서 잘못된 점이라 여기지 않았는데 미션을 진행할수록 이를 관리하기 어렵겠다는 생각이 커졌습니다. 클래스의 부피가 커짐에 따라 단일 책임 원칙 또한 어긋남을 느꼈구요.

2019-08-01 07:12 UTC, seonghun127 commented on src/main/java/techcourse/myblog/article/controller/ArticleController.java
> +        articleService.deleteById(articleId, userSession.getId());
질문 있습니다!

exception 발생 유무로 해당 메서드 실행의 성공, 실패 여부만으로 판단하는 것이 왜 부족한지 잘 이해되지 않습니다. Service 계층에서 예외가 발생한다면 이는 Controller로 넘어오고 이를 `@ControllerAdvice` 어노테이션이 붙은 클래스에서 처리해주기때문에 해당 메서드의 실패를 잘 처리해주고 있다고 생각합니다!

2019-08-01 07:19 UTC, seonghun127 commented on src/main/java/techcourse/myblog/comment/service/CommentService.java
> +public class CommentService {
질문 있습니다!

우선 쏘쏘가 보내준 링크를 보고 `RequiredArgsConstructor` 어노테이션의 위험성을 잘 이해할 수 있었습니다. 해당 링크에서 말하는 문제는 DI가 이뤄져야하는 클래스의 객체를 생성자로 직접 생성할 시에 주로 발생한다고 생각합니다.

`@Repository` `@Service` `@Controller` 가 붙은 클래스는 기본적으로 제가 직접 생성자로 객체를 생성할 일이 없습니다. domain에 있는 클래스를 보면(User, Article, Comment) 전부 빌더 패턴(`@Builder`)을 제가 직접 생성한 생성자에 적용시킴으로써 위 링크에서 이야기하고 있는 문제점을 충분히 예방하고 있다고 생각합니다!

어떻게 생각하시나요?

2019-08-01 07:29 UTC, seonghun127 commented
쏘쏘 안녕하세요. 리뷰이 이바입니다.

유용한 정보와 함께 피드백 주신 점에 대해 진심으로 감사합니다.
쏘쏘 언급한 내용을 최대한 반영하려고 노력했습니다.

하지만 테스트 코드에 대해서는 아직 부족한 부분이 너무 많네요.
```
webTestClient.~ .exchange()
```
위 코드의 중복을 http method에 따라 만들어 놓고 재사용하는 방식까진 적용했지만
전체 테스트 코드를 돌릴 시 테스트 코드가 깨지는 문제는 아직 해결하지 못했습니다.

인수 테스트 시 각각의 도메인 객체에 접근하기 위한 id 값 추출에 어려움을 겪고 있습니다. 임시방편으로 
`public static long userId = 1` 과 같이 전역 변수를 두어 도메인 생성시 마다 1씩 증가 시켜주는 방식을 통해
오류 코드를 해결했지만 전체 테스트 코드 수행시, 다른 클래스에서 생성되어 id가 몇인지 모르는 상태에서
무작정 id를 1로 접근하려하니 테스트 코드가 무수히 깨져버리고 있습니다.

물론 인수 테스트 코드에서 Repository를 필드로 두어 현재 id의 값이 몇인지 조회해보는 방법도 있겠지만
인수 테스트에 Repository에 의존하기 싫어 이 방법을 피하고 다른 방법을 계속 고민해보고 있습니다.
테스트 코드가 정말 어렵네요 ㅠ

부족한 부분이 많다고 생각하기에 다시 한번 많은 지적 부탁드리겠습니다. 감사합니다.

2019-08-01 23:52 UTC, ssosso commented on src/main/java/techcourse/myblog/article/controller/ArticleController.java
> +        articleService.deleteById(articleId, userSession.getId());
네~ 이바의 의견에 동의합니다:)
그렇다면 controller 구현과 service 구현을 조금 나누어 생각해보면 어떨까요~?
삭제가 성공했는지 실패했는지에 따른 controller 구현은 이바의 생각처럼 잘 구현되었다고 생각해요~
그것과 별개로 deleteById 구현에서 void가 아니라 반환값이 있는 것이 좋을 것으로 생각하는데, 이바의 의견은 어떠신가요~?

2019-08-01 23:54 UTC, ssosso commented on src/main/java/techcourse/myblog/comment/dto/CommentDto.java
> +public class CommentDto {
경험으로써 얻은 생각이네요, 좋습니다:)
프로그래밍에 딱떨어지는 정답이 없기에 항상 어떤 방식에도 장점과 단점이 있을 거라는 전재하에 생각하면 좋겠네요

2019-08-02 04:57 UTC, ssosso commented on src/main/java/techcourse/myblog/comment/domain/Comment.java
> +    public void updateComment(String contents) {
설명 감사드립니다~ 이바의 고민포인트가 무엇인지 잘 전달받았습니다:)
메서드는 기본적으로 반환값이 있도록 설계하는 것이 좋은데요, 
같이 몇 가지 살펴보시죠~

1. 테스트 코드 작성이 수월하다는 이유만으로 프로덕션 코드를 바꾸는 것이 이질감이 든다..라는 부분은 관점에 따라 다르게 생각할 수 있습니다. 제 의견을 말씀드리자면, 메서드를 반환값이 있도록 만드는 것이 프로덕션 코드에 리스크를 야기하는 프로그래밍이 아니라고 생각합니다. 예를 들어 테스트 코드 작성을 쉽게 하기 위해 프로덕션 코드에는 필요없는 필드를 추가한다던가, 상속구조를 변경한다던가, 하는 등의 수준이라면 테스트 코드 작성을 위해 프로덕션 코드를 수정하는 것이 과하다라는 생각을 할 수 있다고 생각하고 있습니다.

2. 그렇다면 왜 굳이 반환값이 있는 메서드를 작성하는 습관을 들여야 하는걸까,
이바도 왜 그래야 할까 에 대한 질문해오신 것으로 생각하고 있습니다.
말씀하신 것과 같이 테스트 코드 작성에 용이한 면이 있습니다.
그 외 어떤 점이 좋을까요~? 
다수의 사람이 한 프로젝트를 개발할 때 이렇게 간단한 소스가 아닌 복잡한 소스 구조를 띄고 있다고 가정하면 메서드는 기본적으로 반환값이 있도록 설계하는 편이 좋습니다.
- 첫 째, 메서드를 사용하는 측에서 메서드의 반환값을 통해 메서드를 작성한 의도를 더 잘 이해할 수 있습니다.
- 둘 째, 메서드를 사용하는 측에서 반환값을 통해 진행할 수 있는 로직의 범위가 늘어납니다.
```java
if(updateComment) // 성공 시 action
else // 실패 시 action
```

2019-08-02 05:59 UTC, ssosso approved these changes
이바~ 정말 많은 고민을 하셨네요:) 보기 좋습니다~
테스트 코드 전체 실행 시 문제가 되는 부분에 대해서 말씀주셨는데,
전반적인 테스트 코드에서 사용할 수 있는 임의 데이터 삽입 메서드를 만들어 두고 이를 통해 테스트 전에 임의 데이터 생성하고 그에 대한 id를 받아와 처리하는 것이 좋습니다.
그렇지 않으면 병렬 테스트 처리 과정에서 당연히 실패할 수 밖에 없어요~
그 외 댓글로 질문주신 내용도 각각 답변 달아두었습니다:)~
모두 반영했다는 생각이 드시면 말씀주세요 머지하겠습니다.

2019-08-02 06:13 UTC, ssosso commented on src/main/java/techcourse/myblog/comment/service/CommentService.java
> +public class CommentService {
앗 제가 요 부분을 까먹었네요 지금 바로 답변달겠습니다. 잠시만요~

2019-08-02 06:19 UTC, ssosso commented on src/main/java/techcourse/myblog/comment/service/CommentService.java
> +public class CommentService {
좋은 의견 감사합니다. 이바 생각에 동의합니다:) 
현재는 불필요하게 느껴지실 수도 있어요, 그렇다면 시스템이 좀 더 복잡해져서 injection이 필요치 않은 필드를 만들게 되면 어떨까요~? 그렇게 되면 특정 클래스는 롬복을 사용하여 생성자를 만들어주는 곳이 있고 어떤곳은 직접 생성하는 곳이 있겠죠~ 직접 생성자를 선언하면 일관적이면서 좀 더 명시적인 선언으로 코드를 놓치는 부분이 줄어들 수 있다는 생각입니다:) 해당 내용은 참고만 해주세요:)

2019-08-02 08:05 UTC, seonghun127 commented on src/main/java/techcourse/myblog/comment/service/CommentService.java
> +public class CommentService {
Injection이 필요치 않는 필드가 추가될 경우는 생각하지 못했네요!
더불어 생성자를 직접 선언해주는 것이 다른 코드에 영향을 주거나 코드를 더럽힌다고 생각하지 않기 때문에 
말씀해주신대로 생성자를 직접 선언해주었습니다! 👍

2019-08-03 09:39 UTC, seonghun127 commented
안녕하세요 쏘쏘! 리뷰이 이바입니다.

테스트 코드를 전폭 수정했습니다. .sql 파일로 데이터 주입을 임의로 하여 인수 테스트를 진행하고 mockito를 사용하여 service 레이어 테스트 코드를 수정했습니다. 이제는 전체 실행 시 전부 통과합니다 👍 

반환값에 대해 고민하면서 update에 대해서는 반환값을 두었지만 아직 delete를 할 때 적절하게 반환값을 두고 처리하는 방법에 대해 마음에 드는 로직을 구현하지 못해 반영하진 못했습니다 ㅠㅠ

그렇지만 반환값을 두는 중요성을 알고 향후 프로젝트에는 적극적으로 쏘쏘의 피드백을 따르려고 합니다 ㅎㅎㅎ
수정사항에 대해 부족한 부분이 있다면 거침없이 지적해주시면 감사하겠습니다! (물론 머지도 감사하겠습니다 ㅎ_ㅎ)

2019-08-03 11:38 UTC, ssosso approved these changes
좋네요:) 열정 이바ㅋㅋㅋ  정말 고생많으셨습니다.
제가 드린 피드백에서 혹시 더 좋은 피드백을 받거나 공유해주실 내용이 있다면 언제든지 공유해주세요:)
화이팅~

2019-08-03 11:38 UTC, merged