[댓글 기능] 에헴 미션 제출합니다.
woowacourse/jwp-blog pull request #127
Opened 2019-07-30 08:12 UTC by dasistHYOJIN

안녕하세요 에헴입니다.
짧은 기한 내에 미션을 진행하느라 부족한 점이 많습니다.

피드백 부탁드립니다. 감사합니다~

2019-07-30 13:50 UTC, phs1116 requested changes
안녕하세요. 리뷰어 화투입니다. :)
짧은시간 내에 정말 구현 잘 하셨어요. 👍 
다만 Comment에 대한 인수테스트 및 예외케이스,
몇가지 연관관계를 활용하면 좋을것 같은점들 피드백 추가했습니다.
확인 부탁드리고 궁금하신 점 있으시면 연락주세요. :)

2019-07-30 13:50 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/Article.java
> +        return Objects.equals(id, article.id) &&
엔티티에서 동등성 검사는 보통 id만으로 식별 합니다. :)

2019-07-30 13:50 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/User.java
> +    private String validateName(String name) {
Name, Email, Password 를 별도 VO로 분리하여 거기서 validation check를 하도록 해보면 어떨까요?
AttributeConverter 공부해도 좋을 것 같아요. :)

2019-07-30 13:50 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +        article.setAuthor(user);
setter가 아닌 생성과 동시에 설정 할 수 있지 않을까요?

2019-07-30 13:50 UTC, phs1116 commented on src/main/java/techcourse/myblog/utils/converter/DtoConverter.java
> +public class DtoConverter {
앞으로 어떤 엔티티가 추가되더라도 DtoConverter에 수정이 일어 날 것 같네요.
이러한 전역적인 객체가 아닌 각 DTO가 책임을 가지도록 해보면 어떨까요?

ex) UserRequestDto.toEntity

2019-07-30 13:50 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +        Article originArticle = findArticle(articleId);
작성자가 아닌 사용자도 글을 수정 및 삭제 할 수 있을 것 같네요.
article에 user를 전달하여 확인하는 등 권한 관리를 추가해보면 어떨까요?

2019-07-30 13:50 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/UserService.java
> +    private static final String REGISTERED_EMAIL = "이미 등록된 이메일 입니다.";
예외 메시지를 서비스가 가지도록 하지말고
해당 메시지를 가지고있는 새로운 예외를 만들면 어떨까요?
예외 상속을 활용해도 좋을 것 같아요.

2019-07-30 13:50 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/CommentService.java
> +        if (!userEmail.equals(commenterEmail)) {
Comment와 User의 연관관계 기반으로 체크하도록 해보면 어떨까요?
ex) comment.isAuthor(user)

2019-07-30 13:50 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/Comment.java
> +        this.contents = commentRequestDto.getContents();
update시에 user 정보도 같이 받아서 권한을 체크해보면 어떨까요?

2019-07-30 13:50 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/Article.java
> +        this.title = modifiedArticle.title;
여기도 update 시에 user를 전달받아 권한 체크를 같이 하도록 수정해보면 좋을 것 같습니다. :)

2019-07-30 13:50 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +        Article article = articleRepository.findById(articleId).orElseThrow(() -> new ArticleException());
양방향 연관관계를 가져간다면 article.getComments로도 풀 수 있을 것 같네요. :)

2019-07-30 13:50 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/CommentService.java
> +        Article article = findArticleByArticleId(articleId);
article.addComment(comment)와 같은 방식으로 조금 더 객체지향적으로 풀어갈 수도 있을것 같아요. :)

2019-07-30 13:50 UTC, phs1116 commented on src/test/java/techcourse/myblog/repository/UserRepositoryTest2.java
> +public class UserRepositoryTest2 {
테스트가 두개인데 확인 부탁드려요 :)

2019-07-30 13:50 UTC, phs1116 commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +    void updateArticle() {
작성자가 아닌 사람이 수정 및 삭제 요청을 하는 경우에 대한 테스트도 추가해보면 어떨까요? :)

2019-07-30 13:50 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/CommentController.java
> +public class CommentController {
CommentController에 대한 인수테스트가 없는 것 같습니다. :)

2019-07-30 16:04 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/domain/Article.java
> +        return Objects.equals(id, article.id) &&
몰랐던 부분인데 알려주셔서 감사합니다!

2019-07-31 03:29 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/utils/converter/DtoConverter.java
> +public class DtoConverter {
주신 리뷰에 대한 의문점이 드는 게 있습니다.
데이터를 전달하는 역할을 맡고 있는 DTO가 엔티티 객체를 생성하는 기능까지 담당하는 게 맞는 일인지 궁금합니다.

우선은 엔티티별로 DTO converter를 나누어 사용하도록 변경해보았습니다.
이렇게 하면 엔티티가 추가될 때마다 converter가 변경되는 문제를 방지할 수 있지 않을까요?

2019-07-31 07:13 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +        article.setAuthor(user);
충분히 가능한 일이었네요!
막연하게 고쳐야겠다는 생각만 하고 있었는데 지적해주셔서 감사합니다!

2019-07-31 10:51 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/web/CommentController.java
> +public class CommentController {
급하게 한다고 진행하려다가 테스트를 추가를 안했네요ㅠㅠ
테스트 추가했습니다!

2019-08-01 00:44 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +        Article originArticle = findArticle(articleId);
댓글에 권한 관리를 추가할 때 같이 추가 했었어야 했는데 미처 생각하지 못했던 부분이네요...!
추가했습니다!

2019-08-01 00:51 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/service/UserService.java
> +    private static final String REGISTERED_EMAIL = "이미 등록된 이메일 입니다.";
User 객체의 유효하지 않은 Name이나 Password 등에 대한 예외를 말씀해주신 것처럼 SignupException 예외를 상속하도록 바꾸어 보았는데요,
이렇게 변경하니 예외가 어느 종류의 예외에 속하는지 파악하기가 훨씬 수월해졌네요!

다음 미션 때도 이 피드백을 계속 적용해보겠습니다~

2019-08-01 06:36 UTC, dasistHYOJIN commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +    void updateArticle() {
넵 프로덕션 코드와 함께 추가했습니다!

2019-08-01 11:19 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/service/CommentService.java
> +        Article article = findArticleByArticleId(articleId);
오...!!
양방향으로 매핑하면 이런 식으로 구현할 수 있네요.
변경해보았습니다!

2019-08-01 11:50 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/service/CommentService.java
> +        if (!userEmail.equals(commenterEmail)) {
레벨 1에서 배운 것들을 적용할 수 있겠네요.
감사합니다!

2019-08-01 16:42 UTC, dasistHYOJIN commented
안녕하세요 화투님!

JPA를 처음 사용해보는 거라 단방향과 양방향이 사용하기 적절한 경우에 대한 기준이 명확하지 않아서 엔티티간 연관관계를 지정해주는 게 많이 헷갈리고 어려웠습니다.

피드백 주신대로 `Article`과 `Comment`의 관계를 양방향으로 변경해보았는데 fk를 갖고 있지 않은 자식 엔티티인 `Article` 객체에서 댓글을 탐색하고 추가하는 게 훨씬 간편하다고 느꼈습니다.
하지만 테스트를 작성하다보니 부딪힌 어려움이 있어서 추가적으로 질문을 드리고 싶은데요,

**게시글이 삭제되면 댓글도 함께 삭제되는지에 대한 테스트**를 진행할 때
1. `ArticleRepositoryTest`에서 확인하려고 해도 해당 게시글이 지워졌기 때문에 댓글 삭제 여부를 확인하려면 `CommentRepository`가 필요하고
2. 똑같이 `CommentRepositoryTest`에서도 게시글을 삭제하기 위해 `ArticleRepository`를 호출해야 했습니다.

편리한 테스트를 위해서 다른 빈 객체를 가져다 사용하는 건 한 빈 객체에 대한 순수한(?) 테스트가 아닌 것 같아서 곤란했습니다.

그래서 `CommentRepositoryTest`에서 Persistence Context와 동기화하기 전에 `testEntityManager`의 `remove()` 메서드를 사용해서 Article 객체를 삭제하도록 짜기는 했는데 적절한 방법이었는지 궁금합니다.
리뷰와 함께 이런 경우에는 어떻게 해야 할 지 추가적인 방향이나 힌트를 제시해주셨으면 합니다.

감사합니다!

2019-08-01 17:10 UTC, dasistHYOJIN commented on src/test/java/techcourse/myblog/repository/UserRepositoryTest2.java
> +public class UserRepositoryTest2 {
앗 수업 때 진행했던 부분이 같이 커밋됐네요....
Repository 테스트를 수정하면서 삭제했습니다!

2019-08-01 17:20 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/domain/Comment.java
> +        this.contents = commentRequestDto.getContents();
변경했습니다!

권한을 체크하는 것은 컨트롤러에서 서비스의 `checkAuthentication()` 메서드를 통해서 이미 검증했다고 생각했는데 엔티티에서도 해줘야 하는 건지 궁금합니다.
객체가 직접적으로 변경되는 위치에서 데이터의 신뢰성을 한 번 더 보장하기 위한 의도로 말씀하신 게 맞나요??

2019-08-01 18:11 UTC, dasistHYOJIN commented
안녕하세요 화투님!
피드백을 반영하면서 참고해야 하는 것들이 많아 리뷰 요청이 예상보다도 늦은 것 같습니다...!

아직 DTO의 사용이 익숙치 않고 사용할 만한 경우를 구분하는 것이 어려워서 제가 봐도 얼룩덜룩한 부분들이 많습니다.
주신 피드백에 대해 나름대로의 생각을 적긴 했는데 크루들과 이야기를 나눌 때마다 생각이 달라져서 느낀 바를 토대로 다시 수정을 해야 할 것 같습니다ㅜㅜ
제가 달은 댓글에 대해 어떻게 생각하시는지 의견을 달아주시면 수정할 때 많은 도움이 될 것 같아요! 👀 

JPA는 처음 사용해보는 거라 단방향과 양방향이 사용하기 적절한 경우에 대한 기준이 명확하지 않아서 엔티티간 연관관계를 지정해주는 게 많이 헷갈리고 어려웠습니다.

피드백 주신대로 `Article`과 `Comment`의 관계를 양방향으로 변경해보았는데 fk를 갖고 있지 않은 자식 엔티티인 `Article` 객체에서 댓글을 탐색하고 추가하는 게 훨씬 간편하다고 느꼈습니다.
하지만 테스트를 작성하다보니 부딪힌 어려움이 있어서 추가적으로 질문을 드리고 싶은데요,

**게시글이 삭제되면 댓글도 함께 삭제되는지에 대한 테스트**를 진행할 때
1. `ArticleRepositoryTest`에서 확인하려고 해도 해당 게시글이 지워졌기 때문에 댓글 삭제 여부를 확인하려면 `CommentRepository`가 필요하고
2. 똑같이 `CommentRepositoryTest`에서도 게시글을 삭제하기 위해 `ArticleRepository`를 호출해야 했습니다.

편리한 테스트를 위해서 다른 빈 객체를 가져다 사용하는 건 한 빈 객체에 대한 순수한(?) 테스트가 아닌 것 같아서 곤란했습니다.

그래서 `CommentRepositoryTest`에서 Persistence Context와 동기화하기 전에 `testEntityManager`의 `remove()` 메서드를 사용해서 Article 객체를 삭제하도록 짜기는 했는데 적절한 방법이었는지 궁금합니다.
리뷰와 함께 이런 경우에는 어떻게 해야 할 지 추가적인 방향이나 힌트를 제시해주셨으면 합니다.

감사합니다!

2019-08-03 10:34 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
전체적으로 매우 잘 작성해주셨어요. 개선 👍 
질문주신 사항 및 몇가지 피드백 추가했습니다.
참고 부탁드리구요 궁금하신 점 있으시면 DM 주세요 :)

2019-08-03 10:34 UTC, phs1116 commented on src/main/java/techcourse/myblog/article/service/ArticleService.java
> +    private final UserService userService;
각 서비스에서 다른 서비스를 참조하기때문에 말씀하신대로 순환참조 문제가 발생할 수도 있을 것 같아요.
그렇다면 레이어를 분리해보세요.
일반적으로 레이어드 아키텍쳐에선
표현 영역 -> 응용 서비스 영역 -> 도메인 서비스 영역 -> 인프라 스트럭쳐 영역으로 나뉘어지고있고
현재 비즈니스가 워낙 간단하다보니 응용 서비스 영역은 생략된 상태인데요. (혹은 도메인 서비스와 합쳐짐)
다른 서비스들을 Facade 해주는 역할을 응용 영역에서 해주고 있습니다.
관련해서 많은 글들이 있을텐데요, 참고해보시고 반영해보세요 :)
혹은 구글에서 DDD Layered Architecture를 검색하시면 많이 나올거에요 :)

https://archfirst.org/domain-driven-design-6-layered-architecture/
http://uniknow.github.io/AgileDev/site/0.1.9-SNAPSHOT/parent/ddd/core/layered_architecture.html

2019-08-03 10:34 UTC, phs1116 commented on src/main/java/techcourse/myblog/article/service/ArticleService.java
> +        if (!article.getAuthor().getEmail().equals(userResponseDto.getEmail())) {
getter가 아니라 메시지를 통해서 권한 체크가 가능하지 않을까요?
그리고 유저에 대한 엔티티 식별은 Email이 아닌 PK로 하는것이 더 적합하지 않을까요? :)

참고) 일반적으로 엔티티의 동등성 검사(equals, hashcode)는 PK를 기반으로 작성합니다.

2019-08-03 10:34 UTC, phs1116 commented on src/main/java/techcourse/myblog/article/service/ArticleService.java
> +        articleRepository.deleteById(articleId);
`게시글 및 댓글은 작성자만 삭제할 수 있다`라는 비즈니스는 서비스에서 책임져야하지 않을까요 :)

2019-08-03 10:34 UTC, phs1116 commented on src/main/java/techcourse/myblog/comment/controller/CommentController.java
> +        UserResponseDto userResponseDto = (UserResponseDto) SessionUtil.getAttribute(httpSession, USER);
UserResponseDto userResponseDto = (UserResponseDto) SessionUtil.getAttribute(httpSession, USER);
이 부분을 Argument Resolver, 혹은 ThreadLocal을 통해서 추상화해보면 어떨까요?

2019-08-03 10:34 UTC, phs1116 commented on src/main/java/techcourse/myblog/comment/service/CommentService.java
> +        commentRepository.delete(comment);
삭제에 대한 부분도 도메인에서 확인하면 좋을 것 같습니다. :)

2019-08-03 10:34 UTC, phs1116 commented on src/main/java/techcourse/myblog/comment/service/CommentService.java
> +        System.out.println(comment.getCommenter().getEmail());
System.out.println은 성능 문제로 안티패턴으로 간주됩니다. :0
Slf4j를 이용해서 로그로 수정해보면 좋을것 같아요!

2019-08-03 10:34 UTC, phs1116 commented on src/test/java/techcourse/myblog/comment/repository/CommentRepositoryTest.java
> +    public void 게시글이_삭제되면_댓글도_함께_삭제되는지_테스트() {
먼저 실무에 비추어서 말씀드리자면 실무에서는 데이터를 실제로 hard delete 하지 않습니다. :)
deleted라는 boolean 속성을 통해서 soft delete를 하여 삭제하는 경우가 많습니다.
(이벤트 리스너 활용 혹은 객체 자체에서 delete 매서드를 만들어 연관을 갖는 코멘트들을 순회하며 delete 호출 등)
따라서 cascade 속성을 통한 삭제 같은 경우는 하지 않기 때문에 이런 형태의 테스트를 작성할 일이 많지 않아요 :) 

Repository 테스트에서 해당 경우 외에는 저도 더 좋은 방법이 떠오르지 않네요. :)
현재 테스트로도 충분히 무방하다고 생각합니다.

2019-08-03 10:34 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/Comment.java
> +        this.contents = commentRequestDto.getContents();
신뢰성을 한번 더 보장한다는 점도 있지만
도메인 관점에서 해당 객체가 동일한 사용자에 의해서 삭제 및 수정이 가능하다는 점이
모델만, 혹은 도메인 영역만 보고 판단 가능하다는 장점이 있습니다. :)
해당 사실을 모른다면 컨트롤러라는 최앞단 영역까지 보고나서야 판단이 가능하겠죠?
도메인 비즈니스는 도메인이 책임지도록 하는게 나중에 도메인을 파악하는데 용이해요 :)

2019-08-03 10:34 UTC, phs1116 commented on src/main/java/techcourse/myblog/utils/converter/DtoConverter.java
> +public class DtoConverter {
1. 넵. 말씀하신대로 Entity를 생성하는걸 DTO에서 책임지도록 하는것은 별로 선호되지 않습니다. 현재는 아직 영역이 크게 분리되지 않아서 말씀드렸습니다. :) 
2. 또한 개인적으로는 말씀하신대로 DTO가 책임지는 것이 아닌, 각 서비스에서 생성자로 직접 생성하는것을 선호합니다. :)

네. DTO별로 Converter 분리 잘 하신것 같습니다 👍  
실제로 DDD에서는  DTO Asembler라는 객체로 말씀하신 역할을 책임지는 영역이 있습니다. :)
https://buildplease.com/pages/repositories-dto/

다만 해당 객체는 도메인 및 응용 영의 객체를 표현 영역에 맞도록 변경해주는 역할만 (Entity -> DTO) 가지고 있지 반대의 역할은 가지고 있지 않습니다.

또 현재 사용되고 있는 부분이 DTO로 변환하는 과정에 복잡한 비즈니스가 없는 상태라 굳이 필요한가? 라는 생각도 들기도 하네요. :)
사용하신다면 현재 Entity -> DTO, DTO -> Entity에 대해서 메서드 이름은 명확하게 구분해주시는게 좋을 것 같아요 :)
둘다 convert로 어떤 역할인지 명확하게 드러나지 않아 코드만 볼 경우 혼동할 수도 있을 것 같습니다.

2019-08-03 10:34 UTC, phs1116 commented on src/main/java/techcourse/myblog/utils/converter/CommentConverter.java
> +public class CommentConverter {
클래스만 있고 사용되고 있지 않은 것 같습니다. :)

2019-08-04 05:12 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/article/service/ArticleService.java
> +        if (!article.getAuthor().getEmail().equals(userResponseDto.getEmail())) {
아 그렇네요...!
실컷 만들어놓고 꼼꼼함이 부족했네요.... 수정했습니당

2019-08-04 05:26 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/comment/service/CommentService.java
> +        System.out.println(comment.getCommenter().getEmail());
넵!
습관적으로 sout을 계속 사용하게 되는데 이번 기회에 고쳐야겠습니다..!

2019-08-04 09:28 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/comment/controller/CommentController.java
> +        UserResponseDto userResponseDto = (UserResponseDto) SessionUtil.getAttribute(httpSession, USER);
ArgumentResolver를 이용해서 코드 중복을 줄여봤습니다~
사용법에 비해 중복 코드를 줄이는 데에 큰 도움이 되네요..!

2019-08-04 09:44 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/article/service/ArticleService.java
> +    private final UserService userService;
이번에 발생한 순환참조 문제는 Article과 Comment 엔티티가 양방향 매핑이 되어 있다는 점을 이용해서 충분히 해결할 수 있었습니다!
피드백 주신 내용은 지금 구조에서는 굳이 적용하지 않아도 된다고 생각해서 적용하지 않았지만
숙지하고 있다가 다음에 올 미션에서 적용해보도록 하겠습니다~

몰랐던 내용인데 알려주셔서 감사합니당

2019-08-04 13:02 UTC, phs1116 approved these changes
안녕하세요! 리뷰어 화투입니다.
구현 매우 잘 해주셨습니다 👍 
이번 단계 머지하도록 하겠습니다.
개발 하시느라 수고 많으셨어요 :)

2019-08-04 13:02 UTC, merged