[댓글 기능] 루피 미션 제출합니다
woowacourse/jwp-blog pull request #131
Opened 2019-07-30 08:28 UTC by MrKwon

안녕하세요 쏘쏘! 루피입니다. 🤠

레벨1, 1주차에 리뷰를 받고 다시 받게 되어 느낌이 색다르네요.
1주차에 우아한 테크코스를 왜 끝까지 해야되는지 의문이 들었었는데 (아무것도 몰랐으므로,,) 쏘쏘의 피드백이 왜 우아한 테크코스를 계속 해야되는지 알게 된 큰 이유 중에 하나였기 때문에 항상 감사하게 생각하고 있습니다 !

지난주 미션 피드백에서 워낙 많은 내용을 받아 그 피드백을 바탕으로 이번 주 미션도 구현해보았습니다.

indent depth 나 if 문, try-catch 문을 줄이려고 노력했으나 그래도 없애지 못한 부분이 아직 service 로직에 남아있는데 지금 구현한 코드가 최선이 아닐 것 같은 느낌이라(스프링이 처음인데,, 상당히 충격적인 기능(?)들이 많더라구요.. 그래서 가능하지 않을까.. 라는 느낌) service 에서 가능한 방법이 없을지도 추가적으로 코멘트 남겨주시면 더 좋을 것 같아요 ! 😁

양방향 매핑을 하지 않는 게 좋다고 수업에서 포비가 이야기 했지만 article 로 comment 의 수에 접근하는 경우가 생겨 필요성을 양방향 매핑을 했습니다. 이 부분에 대해서도 어떻게 생각하시는지 피드백에 이야기 해주시면 좋겠습니다.

감사합니다 !

2019-07-30 15:43 UTC, ssosso requested changes
안녕하세요, 루피~ 반가워요:) 쏘쏘입니다.
몇 가지 피드백 드렸는데 service에 추가적으로 피드백 받고 싶으신 부분이 있으시면 말씀부탁드려요:)
양방향 매핑은 괜찮아요~ 그런데 매핑 시 lazy 로딩하는 것에 대해 공부해보고 적용하면 좋습니다:)
지금은 하나의 객체를 find하면 매핑되어 있는 객체들까지 무조건 로딩하고 있어요~

2019-07-30 15:43 UTC, ssosso commented on src/main/java/techcourse/myblog/service/ArticleService.java
>  @RequiredArgsConstructor
RequiredArgsConstructor 사용은 지양
필요한 Field로 Constructor 를 직접 만들면 어떨까요~?
같은 타입의 필드 선언 순서를 나중에 바꿀 경우 문제가 발생 소지가 있습니다. 개인적으로 생성자를 명시적으로 놓고 사용한다면 DI이후 필드값에 대한 추가적인 설정 또한 용이합니다.

2019-07-30 15:43 UTC, ssosso commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +                .orElseThrow(() -> new UnFoundArticleException("해당 게시글이 존재하지 않습니다."));
참고> find 시도했던 article의 id를 exception에 포함해서 로그를 남길 때 사용하면 좋습니다.

2019-07-30 15:43 UTC, ssosso commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +            throw new InvalidUserSessionException("권한이 없습니다.");
반복되는 부분은 메서드로 별도 분리합니다.

2019-07-30 15:43 UTC, ssosso commented on src/main/java/techcourse/myblog/dto/DtoUtils.java
> +public interface DtoUtils<T> {
DtoUtil보다 더 좋은 인터페이스명이 있을까요~?

2019-07-30 15:43 UTC, ssosso commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +        return new RedirectView("/articles/" + articleId);
`new RedirectView("/articles/"` 반복 제거

2019-07-30 15:43 UTC, ssosso commented on src/main/java/techcourse/myblog/controller/IndexController.java
> +@AllArgsConstructor
AllArgsConstructor 사용은 지양
필요한 Field로 Constructor 를 직접 만들면 어떨까요~?
같은 타입의 필드 선언 순서를 나중에 바꿀 경우 문제가 발생 소지가 있습니다. 개인적으로 생성자를 명시적으로 놓고 사용한다면 DI이후 필드값에 대한 추가적인 설정 또한 용이합니다.

2019-07-30 15:43 UTC, ssosso commented on src/main/java/techcourse/myblog/controller/IndexController.java
> +    private final ArticleRepository articleRepository;
controller에서는 service 레이어를 호출하는 것이 좋습니다.

2019-07-30 15:43 UTC, ssosso commented on src/main/java/techcourse/myblog/controller/IndexController.java
> +    private final UserSessionManager userSessionManager;
👍 
UserSessionManager를 이해하기 위해 SessionManagerInterface 를 살펴봤어요~
명명에서 Interface를 사용하지 않고 구현체명명 시 구현체의 특징에 따라 구현체명을 작성하면 어떨까요~?

2019-07-30 15:43 UTC, ssosso commented on src/main/java/techcourse/myblog/controller/argumentresolver/SessionArgumentResolver.java
> +        return new UserSession(user);
👍

2019-07-30 15:43 UTC, ssosso commented on src/main/java/techcourse/myblog/domain/Article.java
>  @RequiredArgsConstructor
RequiredArgsConstructor 사용은 지양
필요한 Field로 Constructor 를 직접 만들면 어떨까요~?
같은 타입의 필드 선언 순서를 나중에 바꿀 경우 문제가 발생 소지가 있습니다. 개인적으로 생성자를 명시적으로 놓고 사용한다면 DI이후 필드값에 대한 추가적인 설정 또한 용이합니다.

2019-07-30 15:43 UTC, ssosso commented on src/main/java/techcourse/myblog/domain/Article.java
> +@Setter
setter제거할 수 있을까요~?

2019-07-30 15:43 UTC, ssosso commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public void remove(Comment comment) {
add, remove시 반환값이 있으면 어떨까요~?

2019-07-30 15:43 UTC, ssosso commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public void remove(Comment comment) {
다른 void 메서드도 모두 반환값이 있도록 만들면 어떨까요~?

2019-07-30 15:43 UTC, ssosso commented on src/main/java/techcourse/myblog/interceptor/ArticleViewInterceptor.java
> +//        }
주석 제거

2019-07-30 15:43 UTC, ssosso commented on src/main/java/techcourse/myblog/service/CommentService.java
> +        }
반복문 별도 메서드로 분리

2019-07-31 03:51 UTC, MrKwon commented on src/main/java/techcourse/myblog/service/ArticleService.java
>  @RequiredArgsConstructor
감사합니다 ! 피드백 반영하였습니다.

2019-07-31 04:18 UTC, MrKwon commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +            throw new InvalidUserSessionException("권한이 없습니다.");
이 부분은 제가 놓쳤네요.. 감사합니다 !

2019-07-31 07:29 UTC, MrKwon commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +        return new RedirectView("/articles/" + articleId);
반복 제거 하였습니다 !

2019-07-31 07:48 UTC, MrKwon commented on src/main/java/techcourse/myblog/service/CommentService.java
> +        }
반복문이 아니라 반복되는 부분이겠죠..?

2019-08-01 00:38 UTC, MrKwon commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public void remove(Comment comment) {
add 나 remove 는 boolean 을 반환하도록 하고 객체를 수정하는 경우에는 자기 자신을 반환하도록 수정해보았습니다.

2019-08-01 00:39 UTC, MrKwon commented on src/main/java/techcourse/myblog/domain/Article.java
>  @RequiredArgsConstructor
피드백 반영하였습니다 !

2019-08-01 00:40 UTC, MrKwon commented on src/main/java/techcourse/myblog/domain/Article.java
> +@Setter
넵, ArticleDto 의 toDomain 메서드를 오버로딩하여 제거했습니다 !

2019-08-01 05:40 UTC, MrKwon commented on src/main/java/techcourse/myblog/dto/DtoUtils.java
> +public interface DtoUtils<T> {
DomainDto 라고 바꿔보았습니다. 괜찮을까요?

2019-08-01 08:31 UTC, MrKwon commented on src/main/java/techcourse/myblog/controller/IndexController.java
> +    private final UserSessionManager userSessionManager;
이름을 짓는건 언제나 어렵네요 ㅠ

2019-08-01 08:41 UTC, MrKwon commented
안녕하세요 쏘쏘 피드백 감사합니다 !
피드백 반영하면서 궁금증 생겼던 부분들에 대해서는 댓글 남겨두었습니다 !

그리고 지연 로딩 관련해서는 OneToMany 매핑에 되어 있는 부분에 대해서만 추가하였습니다.
ManyToOne 관계를 가지고 있는 Article 객체의 comments 는 추가하지 않고 그대로 두었습니다.
그 이유는 Article 객체를 사용할 때마다 comments 를 같이 사용하기 때문에 그렇게 하였는데 괜찮은 것인지 궁긍합니다.

2019-08-02 06:36 UTC, ssosso commented on src/main/java/techcourse/myblog/service/ArticleService.java
>  @RequiredArgsConstructor
참고> https://github.com/woowacourse/jwp-blog/pull/124#discussion_r309995146

2019-08-02 06:36 UTC, ssosso commented on src/main/java/techcourse/myblog/controller/IndexController.java
> +@AllArgsConstructor
참고> https://github.com/woowacourse/jwp-blog/pull/124#discussion_r309995146

2019-08-02 06:37 UTC, ssosso commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public void remove(Comment comment) {
참고> https://github.com/woowacourse/jwp-blog/pull/124#discussion_r309981462

2019-08-02 06:38 UTC, ssosso commented on src/main/java/techcourse/myblog/service/CommentService.java
> +        }
맞습니다~ 반복되는 부분:)ㅎㅎ

2019-08-02 06:43 UTC, ssosso commented on src/main/java/techcourse/myblog/controller/IndexController.java
> +    private final UserSessionManager userSessionManager;
제 경우에는 Impl, Util과 같은 단어가 클래스명에 들어가는 것을 지양하는 편입니다. 특히나 인터페이스를 만들고 이를 구현하는 객체를 만들 때, 'Impl'이라는 Postfix를 사용하지 않을 것을 제안드리고 싶습니다:)
이는 구현체에 명확한 이름을 지을 수 없는 것이라고 볼 수 있습니다.
SessionManager 인터페이스를 구현하는 구현체가 여러 개가 된다면 각 클래스의 특징은 manage하는 도메인 또는 manage하는 방식으로 구분될 수 있을 것 같은데, 이 특징을 클래스명에 녹여 명확한 구현체명을 지어보는 건 어떨까요~?

2019-08-02 06:47 UTC, ssosso approved these changes
좋습니다:) 기본은 lazy 로딩을 지향하는데, 특수 관계에서는 eager를 사용하면 됩니다.
댓글에 질문 달아주신 부분에 답변도 달아두었습니다, 확인 부탁드립니다:)

2019-08-02 06:54 UTC, ssosso commented
아이고, 루피 잘못 말씀드렸네요, eager이면 Article 목록을 가져올 때도 comment테이블을 매핑할텐데 괜찮을까요?

2019-08-02 10:28 UTC, MrKwon commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public void remove(Comment comment) {
설명 감사드립니다~ 이바의 고민포인트가 무엇인지 잘 전달받았습니다:)
메서드는 기본적으로 반환값이 있도록 설계하는 것이 좋은데요,
같이 몇 가지 살펴보시죠~

1. 테스트 코드 작성이 수월하다는 이유만으로 프로덕션 코드를 바꾸는 것이 이질감이 든다..라는 부분은 관점에 따라 다르게 생각할 수 있습니다. 제 의견을 말씀드리자면, 메서드를 반환값이 있도록 만드는 것이 프로덕션 코드에 리스크를 야기하는 프로그래밍이 아니라고 생각합니다. 예를 들어 테스트 코드 작성을 쉽게 하기 위해 프로덕션 코드에는 필요없는 필드를 추가한다던가, 상속구조를 변경한다던가, 하는 등의 수준이라면 테스트 코드 작성을 위해 프로덕션 코드를 수정하는 것이 과하다라는 생각을 할 수 있다고 생각하고 있습니다.

2. 그렇다면 왜 굳이 반환값이 있는 메서드를 작성하는 습관을 들여야 하는걸까,
이바도 왜 그래야 할까 에 대한 질문해오신 것으로 생각하고 있습니다.
말씀하신 것과 같이 테스트 코드 작성에 용이한 면이 있습니다.
그 외 어떤 점이 좋을까요~?
다수의 사람이 한 프로젝트를 개발할 때 이렇게 간단한 소스가 아닌 복잡한 소스 구조를 띄고 있다고 가정하면 메서드는 기본적으로 반환값이 있도록 설계하는 편이 좋습니다.

* 첫 째, 메서드를 사용하는 측에서 메서드의 반환값을 통해 메서드를 작성한 의도를 더 잘 이해할 수 있습니다.
* 둘 째, 메서드를 사용하는 측에서 반환값을 통해 진행할 수 있는 로직의 범위가 늘어납니다.
```
if(updateComment) // 성공 시 action
else // 실패 시 action
```
```
// updateComment가 Comment 객체를 반환한다면
updateComment(commentGiven).getContents()
```

2019-08-02 11:06 UTC, MrKwon commented on src/main/java/techcourse/myblog/controller/IndexController.java
> +    private final UserSessionManager userSessionManager;
key 스트링으로 넣어 세션 직접 set get remove 하지 않고 상속 받은 클래스를 만들어 세션을 관리하도록 하게 하고 싶어 작성된 코드여서 

그러지 않게 하기 위해 ``SessionManagerImpl``를 abstract 클래스로 만들고 이름을 ``AbstractSessionManager`` 클래스로 바꾸어 보았습니다.

다만, abstract 메서드가 없는 abstract 클래스가 있어도 되는지 좀 찝찝한 것 같습니다..

이름 짓기가 참 어렵네요 ㅠㅠ

2019-08-02 11:49 UTC, MrKwon commented
괜찮을 것 같다고 생각해요... article 목록을 가져와서 해당 article 에 달려있는 댓글 수를 보여줘야 하는데 지연 로딩을 꼭 해야되는지 의문입니다...

지연로딩을 하면 List<Comment> 의 size 메서드를 호출할 때 결국 Comment 들이 로딩되는 것이 아닌가요?
만약 Comment 들이 로딩되지 않고 Comment 의 개수만 알아올 수 있다면 지연로딩을 사용하는 것이 이해가 될 것 같습니다.

근데 일단 지금까지 학습한 바로는 모든 Fetch를 Lazy로 수행하며, 애플리케이션의 상황을보며 EAGER로 전환할 수 있는 부분을 찾는게 좋을 것이라고 한다고 하므로 고쳤는데 몇 일 두고 공부하며 생각을 더 해보아야 될 것 같습니다 !

2019-08-02 15:06 UTC, ssosso commented
루피의 의견에 동의해요:) eager 로딩은 꼭, 무조건 그 매핑관계를 함께 불러오는 경우만 있다는 가정이 되어야 성능면에서 문제가 없을 것으로 생각합니다. 그리고 만약 이 블로그 시스템이 실 서비스이고 제가 구현을 담당했다면, count를 가져오는 기능에 대해서는 mapping 관계를 이용하기보다는 count 쿼리를 통해 값을 가져오도록 구현했을 것 같아요~ 그리고 article 상세페이지에서 comment를 볼 때도 paging을 구현하거나 mapping 관계에 limit 속성을 지정했을 것 같습니다:) 참고만 해주세요:)~ 고생많으셨습니다~

2019-08-02 15:06 UTC, ssosso approved these changes
루피의 의견에 동의해요:) eager 로딩은 꼭, 무조건 그 매핑관계를 함께 불러오는 경우만 있다는 가정이 되어야 성능면에서 문제가 없을 것으로 생각합니다. 그리고 만약 이 블로그 시스템이 실 서비스이고 제가 구현을 담당했다면, count를 가져오는 기능에 대해서는 mapping 관계를 이용하기보다는 count 쿼리를 통해 값을 가져오도록 구현했을 것 같아요~ 그리고 article 상세페이지에서 comment를 볼 때도 paging을 구현하거나 mapping 관계에 limit 속성을 지정했을 것 같습니다:) 참고만 해주세요:)~ 고생많으셨습니다~

2019-08-02 15:07 UTC, merged