[댓글 기능] 지노 미션 제출합니다
woowacourse/jwp-blog pull request #152
Opened 2019-07-30 09:36 UTC by hyunssooo

2019-07-31 00:35 UTC, pobiconan requested changes
짧은 시간에 기능 구현하느라 수고했네요. 👍 
Controller에 대한 테스트와 도메인 객체에 대한 단위 테스트 코드도 구현해 보면 좋겠네요.
중복 제거, 새로운 기술 적용, 생각할 꺼리에 대한 피드백 남겼으니 반영해 보면 좋겠어요.

2019-07-31 00:35 UTC, pobiconan commented on src/main/java/techcourse/myblog/application/dto/CommentDto.java
> +public class CommentDto {
이와 같은 단순 코드를 제거하기 위해 lombok을 적용해 본다.

2019-07-31 00:35 UTC, pobiconan commented on src/main/java/techcourse/myblog/application/service/ArticleService.java
> +                user);
`Article article = articleDto.toArticle(user);`와 같이 구현해 보는 것은 어떨까?

2019-07-31 00:35 UTC, pobiconan commented on src/main/java/techcourse/myblog/application/service/CommentService.java
> +public class CommentService {
ArticleService와 CommentService를 분리하는 것이 좋을까?
Service를 어떤 기준으로 분리하는 것이 좋을까?
각 Entity 마다 Service를 추가하는 것이 좋을까?

2019-07-31 00:35 UTC, pobiconan commented on src/main/java/techcourse/myblog/domain/Article.java
>      private String coverUrl;
@Column 애노테이션을 활용해 null 유무, 칼럼 크기와 같은 부분에 대해 구체적으로 설정한다.
@Entity 매핑을 한 모든 객체에 대한 설정한다.

2019-07-31 00:35 UTC, pobiconan commented on src/main/java/techcourse/myblog/domain/Article.java
>      private String contents;
이와 같이 데이터 크기를 결정하기 힘든 큰 크기의 데이터는 @Lob을 쓰는 것을 고려해 본다.
@Lob 설정을 한 후 생성되는 데이터 타입을 확인해 본다.

2019-07-31 00:35 UTC, pobiconan commented on src/main/java/techcourse/myblog/domain/Article.java
Article이 Comment의 목록을 가져 bi-direction 관계를 가지는 것은 어떨까?
만약 uni-direction로 구현하고 싶다면 Article -> Comment로 가지는 것은 어떨까?
지금 구현과 같이 Comment -> Article로 uni-direction 관계를 유지해야 하는 이유는 무엇인가?

2019-07-31 00:35 UTC, pobiconan commented on src/main/java/techcourse/myblog/domain/Article.java
>      public void modify(Article article) {
로그인 사용자에 한해 수정 가능하도록 권한 체크해야하지 않을까?
수정을 담당하는 이 메소드가 권한 체크를 하도록 구현하는 것은 어떨까?
이에 대한 단위 테스트 코드도 구현할 수 있지 않을까?
이와 같이 권한 처리가 필요한 부분이 있는지 확인하고 추가 구현한다.

2019-07-31 00:35 UTC, pobiconan commented on src/main/java/techcourse/myblog/domain/Comment.java
> +    private LocalTime localTime;
https://springbootdev.com/2018/03/13/spring-data-jpa-auditing-with-createdby-createddate-lastmodifiedby-and-lastmodifieddate/

위 문서를 참고해 Entity가 생성, 수정될 때 생성일과 수정일이 자동으로 추가되도록 구현해 본다.

2019-07-31 00:35 UTC, pobiconan commented on src/main/java/techcourse/myblog/domain/Comment.java
> +    private LocalDate localDate;
LocalDateTime을 사용해 하나로 구현한다.
이름도 생성일인데 다른 이름을 사용할 것을 추천

2019-07-31 00:35 UTC, pobiconan commented on src/main/java/techcourse/myblog/domain/UserRepository.java
> +    int countUserByEmail(String email);
굳이 이 메소드가 필요한가?
이 메소드 없이 구현해 본다.

2019-07-31 00:35 UTC, pobiconan commented on src/main/java/techcourse/myblog/presentation/controller/ArticleController.java
>      @PostMapping("/articles")
https://blog.mwaysolutions.com/2014/06/05/10-best-practices-for-better-restful-api/
위 문서를 참고해 url convention을 적용하고 url path의 중복을 제거해 본다.

2019-07-31 00:35 UTC, pobiconan commented on src/main/java/techcourse/myblog/presentation/controller/ArticleController.java
> +        modelAndView.addObject("method", "put");
이와 같이 인자를 넘기기보다 article의 id가 존재하는지 여부에 따라 구분하는 것은 어떨까?

2019-07-31 00:35 UTC, pobiconan commented on src/test/java/techcourse/myblog/application/service/CommentServiceTest.java
> +        comment = new Comment("빵가워요", user, article);
각각의 테스트 데이터를 각 도메인 객체의 Test에서 생성하도록 하는 것은 어떨까?
User는 UserTest, Comment는 CommentTest

2019-07-31 00:35 UTC, pobiconan commented on src/test/java/techcourse/myblog/domain/CommentTest.java
> +}
Controller에 대한 클라이언트 테스트도 구현하는 것이 어떨까?

2019-08-01 05:41 UTC, hyunssooo commented on src/main/java/techcourse/myblog/domain/Article.java
>      private String contents;
longtext로 생성되는것 확인했습니다! 감사해요 포비!

2019-08-01 05:43 UTC, hyunssooo commented on src/main/java/techcourse/myblog/domain/Comment.java
> +    private LocalDate localDate;
```java
@CreationTimestamp
private LocalDateTime createDateTime;

@UpdateTimestamp
private LocalDateTime updateDateTime;

```

으로 변경하여 생성, 수정 시간을 나타내주도록 했습니다!

2019-08-01 05:44 UTC, hyunssooo commented on src/main/java/techcourse/myblog/domain/UserRepository.java
> +    int countUserByEmail(String email);
메소드 제거 하였고 Optional을 사용하여 처리했습니다!

2019-08-01 05:47 UTC, hyunssooo commented on src/main/java/techcourse/myblog/application/dto/CommentDto.java
> +public class CommentDto {
lombok으로 Getter, Setter를 구현하였습니다. lombok은 사용하기는 편하지만 주의점들이 많은 거 같아요.

2019-08-01 05:50 UTC, hyunssooo commented on src/main/java/techcourse/myblog/application/service/ArticleService.java
> +                user);
dto와 domain model은 서로 다른 레이어에 속해서 toEntity 같은 메소드는 좋지 않다고 생각합니다. 또한 제가 생각하는 Dto는 단순히 데이터 전달용 객체라고 생각하여 별도의 로직을 가지게 하고 싶지 않았습니다. 지금 제가 생각하는 최선의 방법은 dto와 domain model 사이에 서로를 맵핑 클래스를 두는 것이 가장 최선이라고 생각합니다 :)

2019-08-03 22:15 UTC, pobiconan approved these changes
피드백 반영 잘 했네요. 💯 
특히 테스트 코드의 중복을 제거하기 위해 구현한 코드 좋네요. 
마지막 미션도 마무리 잘 하세요.

2019-08-03 22:15 UTC, merged