[댓글 기능] 쿠기 미션 제출합니다.
woowacourse/jwp-blog pull request #153
Opened 2019-07-30 09:40 UTC by men7627

안녕하세요 제이슨 !

프로덕션 코드를 리팩토링하는데에 집중을 하여 테스트 코드 작성이 완료되지 못하였습니다.
PR을 보낸 후 바로 작성할 예정입니다.

이번 미션을 진행하면서 전체적으로 중복을 제거하고 리팩토링에 집중을 해보았습니다.
전체 적인 구조나, Controller, Service를 역할에 맞게 나눈 것인지, 더 수정할 부분이 있는지에 대해 피드백을 많이 받고 싶습니다!

감사합니다 !

2019-07-30 20:20 UTC, men7627 commented
dsad

2019-08-01 01:43 UTC, woowahan-pjs requested changes
오프라인 코드 리뷰로 대신하였습니다. 👍

2019-08-04 11:17 UTC, men7627 commented
VO를 통한 중복 된 DTO 사용을 제거해 보았고, test 코드의 중복을 줄여보았습니다.
현재는 Article만 적용해 보았는데 추후에 User, Comment도 적용해 보겠습니다.

공통 피드백 시간에 받았던 피드백들을 적용해보았습니다.
Interceptor의 if문들을 제거해보려고 시도를 했었는데, 잘 되지않아 아직 반영을 못했습니다.
이 부분은 계속 진행해보도록 하겠습니다.

감사합니다 !

2019-08-05 00:07 UTC, woowahan-pjs requested changes
피드백을 잘 반영해 주셨습니다. 👍 
간단한 생각거리를 남겼으니 코드에 반영해 주셔도 좋습니다.
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

2019-08-05 00:07 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/article/Article.java
> +@AllArgsConstructor(access = AccessLevel.PRIVATE)
`AccessLevel.PRIVATE` 👍

2019-08-05 00:07 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/article/Article.java
> +    private ArticleVo articleVo;
`ArticleVo`보다 의미 있는 클래스 이름을 찾아보세요.

2019-08-05 00:07 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/article/ArticleVo.java
> +@NoArgsConstructor
`AccessLevel`을 지정해 주세요.

2019-08-05 00:07 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/comment/Comment.java
> +//    @JoinColumn(name = "user_id")
주석 제거!

2019-08-05 00:07 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/comment/Comment.java
> +    public void update(CommentDto.Update commentDto) {
의미 있는 VALUE OBJECT를 찾아봐요.

2019-08-05 00:07 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/comment/Comment.java
> +        modfiedDate = commentDto.getModifiedDate(); //TODO : 자동
`@LastModifiedDate`가 있으니 필요 없겠죠?

2019-08-05 00:07 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/dto/ArticleDto.java
> +//    @Data
주석 제거!

2019-08-05 00:07 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +        UserDto.Response user = (UserDto.Response) httpSession.getAttribute("user");
`HandlerMethodArgumentResolver`를 구현하여 중복 코드를 제거해 보면 어떨까요?

2019-08-05 00:07 UTC, woowahan-pjs commented on src/test/java/techcourse/myblog/service/ArticleServiceTest.java
> +class ArticleServiceTest extends ServiceTest {
`ArticleService`에 대한 통합 테스트가 아닌 단위 테스트를 해보면 어떨까요? 아래의 글이 도움 될 거예요.
https://jdm.kr/blog/222

2019-08-05 16:52 UTC, men7627 commented on src/main/java/techcourse/myblog/domain/article/ArticleVo.java
> +@NoArgsConstructor
꼭 필요한 것들을 제외하고는 모두 AccessLevel.PRIVATE으로 지정하였습니다 !

2019-08-05 18:25 UTC, men7627 commented on src/main/java/techcourse/myblog/domain/article/Article.java
> +    private ArticleVo articleVo;
Contents라는 이름으로 하기에는 인스턴스와 일치되어 고민 끝에 ArticleDetails라고 이름을 지어보았습니다 !

2019-08-05 18:29 UTC, men7627 commented on src/main/java/techcourse/myblog/domain/comment/Comment.java
> +//    @JoinColumn(name = "user_id")
불필요한 주석을 제거하였습니다 !

2019-08-05 18:38 UTC, men7627 commented on src/main/java/techcourse/myblog/domain/comment/Comment.java
> +        modfiedDate = commentDto.getModifiedDate(); //TODO : 자동
제거하였습니다 !

2019-08-05 18:39 UTC, men7627 commented on src/main/java/techcourse/myblog/dto/ArticleDto.java
> +//    @Data
제거하였습니다 !

2019-08-05 19:53 UTC, men7627 commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +        UserDto.Response user = (UserDto.Response) httpSession.getAttribute("user");
ArgumentResolver를 이용해 Controller에 세션을 가져오는 중복을 제거하였습니다 !
추가적으로 custom parameter annotation을 이용하여 사용해보았습니다.

2019-08-05 22:07 UTC, men7627 commented
Argument Resolver를 통해 Controller의 세션에 관한 중복을 제거하는 것은 어렵지 않았으나,
Mockito를 통해 Service를 단위 테스트하는 것이 쉽지 않아 시간도 오래걸리고 아직 정확하지 않은 것 같습니다. 공부를 좀 더 해보고 좀 더 정확한 방법으로 수정하겠습니다.

2019-08-05 22:08 UTC, men7627 commented on src/test/java/techcourse/myblog/service/ArticleServiceTest.java
> +class ArticleServiceTest extends ServiceTest {
현재는 아직 부족한 부분이 많은 것 같아 CommentServiceTest에만 적용했습니다. 공부를 좀 더한 후에 수정하고, 모두 적용하도록 하겠습니다.

2019-08-06 00:20 UTC, woowahan-pjs approved these changes
수많은 피드백을 반영하고자 대단히 고생 많으셨습니다. 💯 
좋은 개발자가 되기 위한 소중한 밑거름이 되었길 바랍니다.
이만 Merge 하겠습니다.

2019-08-06 00:20 UTC, merged