[비동기 댓글 기능] 닉 미션 제출합니다.
woowacourse/jwp-blog pull request #159
Opened 2019-08-06 05:11 UTC by wbluke

안녕하세요 ssosso-! ajax 리뷰이를 맡은 닉입니다 :)
step1에서도 마지막 미션인 chess에서 만나뵈었는데, (그 땐 모두가 급해서 아쉬웠던 것 같아요ㅜㅜ)
step2에서도 마지막 미션에서 만나뵙네요ㅎㅎ 잘 부탁드립니다. :)

이번 미션은 백엔드 로직이 거의 없고 프론트와 배포 쉘스크립트, 로그 관련 부분이라 진행하면서도 이렇게 하는게 맞을까 많이 갸우뚱하면서 진행했던 것 같습니다.
기존 백엔드 로직 쪽에서 추가로 피드백 주셔도 감사히 받겠습니다.ㅎㅎ 많은 가르침 부탁드려요-! :)

2019-08-06 12:30 UTC, ssosso requested changes
안녕하세요, 닉~ 쏘쏘입니다:)
또 뵙네요:) 몇 가지 피드백 남겼습니다, 확인 부탁드립니다~

2019-08-06 12:30 UTC, ssosso commented on src/main/java/techcourse/myblog/exception/UserControllerAdvice.java
> +        return "redirect:/login";
redirectView 사용할 수 있을까요~?

2019-08-06 12:30 UTC, ssosso commented on src/main/java/techcourse/myblog/web/CommentController.java
> +        return "{\"commentId\":\"" + id + "\"}";
더 좋은 방법이 있을까요~?

2019-08-06 12:30 UTC, ssosso commented on src/main/java/techcourse/myblog/dto/CommentSaveResponseDto.java
> +@AllArgsConstructor
참고> AllArgsConstructor 사용은 지양
필요한 Field로 Constructor 를 직접 만들면 어떨까요~?
같은 타입의 필드 선언 순서를 나중에 바꿀 경우 문제가 발생 소지가 있습니다.

2019-08-06 12:30 UTC, ssosso commented on src/main/resources/templates/article.html
> +                    '</form>';
메서드를 분리하는 것이 어떨까요~?
수기로 작성하는 방법 외에 좋은 방법이 있을까요~?

2019-08-07 12:03 UTC, wbluke commented
1. `article.html` 에서 comment generate 부분을 함수로 분리하고, 백틱(`)을 사용하여 편리하게 json으로 넘어온 데이터를 추가해 주었습니다! 기존에 json 데이터를 추가하려고 계속 +로 문자열들을 이어주면서 올바르지 않은 방법 같다고 생각했는데, 조금 더 편하고 가독성있는 방법을 알게 되었습니다. ㅎㅎ 혹여나 더 좋은 방법이 있을까 싶네요.

2. lombok의 allArgsConstructor를 지양하라는 이야기를 들은 것 같았는데, 정확한 이유를 알게 되었습니다. 그렇다면 같은 이유로 requiredArgsConstructor도 지양해야 하는 걸까요-? 저는 required-를 의존성 주입할 때 즐겨서 써왔거든요ㅠㅠ

3. 급하게 구현하다 보니 json을 하드코딩했네요... 막상 구현할 때는 신경을 못썼습니다ㅠㅠ DTO로 반환하도록 변경하였습니다. 다른 크루들 코드를 보니 ResponseEntity를 쓰기도 했던데, 아직 잘 와닿지 않아서 사용해보지는 않았습니다. 

4. 기존에 redirect로 하드코딩되어있던 부분들을 RedirectView를 사용하여 전부 변경하였습니다! redirect로 반환한다는 것을 훨씬 가독성있고 명확하게 표현해 줄 수 있어서 좋은 듯 싶습니다. 혹시 명시적으로 표시해줄 수 있다는이러한 장점 외에 또다른 장점이 있을까요...?

감사합니다! 다시 한 번 피드백 부탁드립니다 :)

2019-08-07 14:36 UTC, ssosso approved these changes
닉~ 고생많으셨습니다:) 질문주신 내용에 대해서는 아래 답변을 작성했습니다.
이번 미션은 마무리하도록 하겠습니다. 고생많으셨습니다:)~

1. article.html 에서 comment generate 부분을 함수로 분리하고, 백틱(`)을 사용하여 편리하게 json으로 넘어온 데이터를 추가해 주었습니다! 기존에 json 데이터를 추가하려고 계속 +로 문자열들을 이어주면서 올바르지 않은 방법 같다고 생각했는데, 조금 더 편하고 가독성있는 방법을 알게 되었습니다. ㅎㅎ 혹여나 더 좋은 방법이 있을까 싶네요.
  - 좋습니다:) handlebar를 사용하면 아예 태그를 다룰 수 있는 파일로 분리해낼 수 있습니다.
     하지만 handlebar를 사용하지 않는다면 닉이 작성해주신 내용대로 분리하면 좋다고 생각합니다.

2. lombok의 allArgsConstructor를 지양하라는 이야기를 들은 것 같았는데, 정확한 이유를 알게 되었습니다. 그렇다면 같은 이유로 requiredArgsConstructor도 지양해야 하는 걸까요-? 저는 required-를 의존성 주입할 때 즐겨서 써왔거든요ㅠㅠ
  - allArgsConstructor를 지양하라는 관점으로 보자면 requiredArgsConstructor도 같은 이유로 지양해야 함을 이야기 하곤 합니다. 지양해야 하는 이유를 충분히 보완할 수 있다면 사용하는 것에는 문제 없다는 입장도 있다는 것도 참고해주세요~

3. 급하게 구현하다 보니 json을 하드코딩했네요... 막상 구현할 때는 신경을 못썼습니다ㅠㅠ DTO로 반환하도록 변경하였습니다. 다른 크루들 코드를 보니 ResponseEntity를 쓰기도 했던데, 아직 잘 와닿지 않아서 사용해보지는 않았습니다.
  - 그렇군요:) 지금도 충분히 좋습니다. ResponseEntity를 적용하는 것은 ResponseEntity라는 객체가 어떤 이유로 생겼을지를 생각해보고, 객체가 개발된 이유에 부합하는 경우를 겪는다면 그 때 적용해볼 수 있겠네요.

4. 기존에 redirect로 하드코딩되어있던 부분들을 RedirectView를 사용하여 전부 변경하였습니다! redirect로 반환한다는 것을 훨씬 가독성있고 명확하게 표현해 줄 수 있어서 좋은 듯 싶습니다. 혹시 명시적으로 표시해줄 수 있다는이러한 장점 외에 또다른 장점이 있을까요...?
  - redirect를 사용할 수 있는 부분은 RedirectView로 바꾸어도 크게 이점을 못느낄 수 있습니다. 말씀하신 것처럼 가독성 측면에서의 이점이 있지만 미비하다고 생각하는 분은 그대로 redirect를 사용할 수 있어요. 다만, RedirectView가 만들어진 이유를 살펴보면 분명히 redirect로 하려면 여러가지 챙겨줘야 하는 것이 있기 때문에 그런 로직을 한곳에서 처리하고 싶어 만들었지 않을까 싶은데요, 실제로 안을 들여다보면 다양한 기능을 제공하고 있어요. 제가 피드백을 한 이유는 꼭 RedirectView를 써야만하는 이유가 있다기 보다는 다양한 옵션을 제공하는 RedirectView라는 객체가 있고 이를 사용해보는 경험이 있으면 좋겠다는 생각에서였습니다:)

2019-08-07 14:36 UTC, merged