[비동기 댓글 기능] 쉐이크반 미션 제출합니다!
woowacourse/jwp-blog pull request #160
Opened 2019-08-06 05:24 UTC by vsh123

안녕하세요 쏘쏘 :)

level 1에 이어 두번째리뷰를 받게되었습니다.
이번 미션에서 구현한 주요사항은 다음과 같습니다.

1. 비동기 구현
 - 댓글의 생성, 수정, 삭제를 fetch api를 이용하여 구현하였습니다.

2. log 저장
 - RollingFileAppender를 이용하여 log를 파일로 저장하였습니다.

3. build.sh 작성
 - build.sh을 실행하면 git pull -> build -> 기존 서버 down -> 새로운 서버 on을 실행합니다.

이번 미션을 진행하면서 RestController 어노테이션을 처음사용해 봤는데 해당 어노테이션을 사용하니, @RequestBody를 붙여주지 않으면 매개변수인 CommentRequestDto가 정상적으로 매핑이 되지 않는 현상을 발견하였습니다. 많이 고민을 해봤지만 해당 이유를 잘 모르겠어서 이렇게 질문을 남깁니다ㅠㅠㅠ 
혹시 조그마한 가이드라도 주시면 정말 감사하겠습니다!

이번 리뷰도 잘 부탁드리겠습니다 :)

2019-08-06 13:35 UTC, ssosso requested changes
잘 구현해주셨네요~ 👍
구현해주신 내용은 모두 확인하였고 그 외 몇 가지 추가적인 피드백드렸습니다
file change가 너무 많아서 확인해보니 이전 변경분이 그대로 pr에 포함되어있네요
덕분에 추가적인 피드백을 드릴 기회가 있었습니다.
페어변경으로 인해 변경분이 많아진걸까요?

2019-08-06 13:35 UTC, ssosso commented on src/main/java/techcourse/myblog/domain/article/Article.java
> +	public void updateArticle(Article article) {
참고 > 모든 void 함수는 반환값이 있는 함수로 변경하면 어떨까요?

2019-08-06 13:35 UTC, ssosso commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +		List<CommentResponseDto> commentResponses = commentService.findCommentsByArticleId(id);
jpa 매핑관계를 통해서 가져올 수 있지 않을까요~?

2019-08-06 13:35 UTC, ssosso commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +			return "redirect:/articles/" + articleId;
advice를 적용해보는건 어떨까요?

2019-08-06 13:35 UTC, ssosso commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +		return "redirect:/articles/" + savedArticleDto.getId();
redirectView를 사용해보는건 어떨까요~?

2019-08-06 13:35 UTC, ssosso commented on src/main/java/techcourse/myblog/web/util/LoginChecker.java
> +		return user;
optional을 반환하면 어떨까요~?

2019-08-06 13:35 UTC, ssosso commented on src/test/java/techcourse/myblog/web/rest/CommentRestControllerTest.java
> +                .exchange()
반복을 제거할수 있을까요?

2019-08-06 14:03 UTC, vsh123 commented
페어가 변경됨으로 인해서 페어의 코드와 제 코드 중에 하나를 선택하여 진행을 해야했는데 이 과정에서 페어코드로 진행을 하다보니 거의 대부분의 파일이 변경되었습니다..!!
이렇게 다른 크루들이 짠 코드를 토대로 새로운 기능을 추가하는 것이 색다른 경험으로 느껴지더라구요! 물론 쏘쏘가 많은 양의 코드를 리뷰하셔야했다는 점은 죄송합니다..하핳ㅎㅎ
이번 기능 구현 부분뿐만 아니라 기존 코드에 대한 피드백을 남겨주셔서 정말 감사합니다 :)

2019-08-07 04:51 UTC, vsh123 commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +		List<CommentResponseDto> commentResponses = commentService.findCommentsByArticleId(id);
jpa 매핑관계로 가져오려면 양방향 매핑으로만 가능하다고 알고있는데, 매핑을 단방향으로 변경하였습니다!
혹시 제가 잘못 이해하고 있는 것이라면 다시한번 말씀 부탁드리겠습니다 :)

2019-08-07 08:35 UTC, vsh123 commented
쏘쏘 안녕하세요!
어제 보내주신 피드백 반영하여 다시한번 리뷰요청드립니다 :)

궁금한 내용이 있어서 DM 보냈는데 확인 부탁드리겠습니다~!!!
부족한 내용이 있다면 아낌없는 피드백 부탁드립니다!!

2019-08-07 13:54 UTC, ssosso commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +		return "redirect:/articles/" + savedArticleDto.getId();
DM주신 질문에 대한 답변드립니다:)
여러 리뷰어분들이 두 가지 방법에 대한 의견을 주셨던 것 같네요,
RedirectView는 redirect를 하는 여러가지 방식을 지원해주기 때문에 사용하기에 용이합니다.
제가 피드백했던 이유는 RedirectView를 사용해볼 수도 있다 라는 취지로 이해해주시면 좋을 것 같아요:)
현재 쉐이크반이 작성하신 코드에서는 RedirectView를 특별히 사용해야 할 이유는 없습니다.
RedirectView가 여러가지 방식을 지원하여 많은 다양한 경우를 해결할 수 있다는 것은 아래 링크를 통해 확인하실 수 있습니다:)
https://www.baeldung.com/spring-redirect-and-forward

2019-08-07 13:55 UTC, ssosso approved these changes
쉐이크반~ DM 주셨는데 이제서야 피드백 드리네요ㅠ
댓글로 DM에 대한 답변 달아두었습니다:)
고생많으셨습니다~ merge할게요~

2019-08-07 13:55 UTC, merged