[비동기 댓글 기능] 희봉 미션 제출합니다.
woowacourse/jwp-blog pull request #167
Opened 2019-08-06 07:12 UTC by heebong

안녕하세요 현구님! 리뷰를 받게된 희봉입니다.
이번엔 도메인 로직을 수정하기 보단 AJAX와 로그를 추가하는 것에 중심을 두었습니다.

AJAX를 적용한 부분은 아래 3가지 입니다.
1. 댓글 생성
2. 회원가입
3. 로그인

서버 배포 스크립트는 서버가 느려서ㅠ 웹서버를 죽이고 자바를 재빌드하는 순서로 적었습니다.
(start.sh 파일입니다.)

코드를 합치는 과정에서 이전 과제의 커밋까지 가져와 커밋의 양이 많은데 8월 4일 커밋부터가 이번 과제입니다. 참고 부탁드립니다.

피드백 미리 감사드립니다! 😄

2019-08-07 13:51 UTC, kang-hyungu requested changes
안녕하세요 희봉님
몇 가지 피드백 남겼으니 확인해보세요!
그리고 서버 배포 스크립트에 대한 간단한 설명은 README에 적어두면 코드 보시는분들께 도움이 될거에요
궁금한 점 생기면 언제든 DM 주세요

2019-08-07 13:51 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/MyblogApplication.java
> +    public ModelMapper modelMapper() {
스프링 빈은 따로 config 패키지에 추가해주세요!

2019-08-07 13:51 UTC, kang-hyungu commented on src/main/resources/templates/article.html
> +        const commentTemplate =
javascript multiline string 검색해보고 적용해보세요!

2019-08-07 13:51 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/utils/Error.java
> +package techcourse.myblog.utils;
Error 클래스인데 util 패키지로 두는건 적절해보이지 않네요

2019-08-07 13:51 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/article/controller/ArticleExceptionAdvice.java
> +package techcourse.myblog.article.controller;
컨트롤러와 동일한 패키지에 두지 말고 따로 분리하는게 어떨까요?

2019-08-07 13:51 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/article/domain/Article.java
> +    private String title;
Column 어노테이션을 추가해보세요!

2019-08-07 13:51 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/article/domain/Article.java
> +    @ManyToOne
지연 로딩으로 변경해보세요!
즉시 로딩과 지연 로딩의 차이점은 무엇일까요?

2019-08-07 13:51 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/article/dto/ArticleResponseDto.java
> +    public boolean matchAuthorId(long authorId) {
작성자 아이디가 동일한지 체크하는건 비즈니스 로직이에요
dto에서 처리할 기능이 아닙니다

2019-08-07 13:51 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/comment/controller/CommentController.java
> +    public CommentResponseDto createComment(@PathVariable long articleId, UserSession userSession, @RequestBody CommentCreateDto commentDto) {
이 메서드는 RestController로 분리해보는게 어떨까요?
mvc용과 rest용 컨트롤러가 섞여있네요

2019-08-07 13:51 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/comment/domain/Comment.java
> +    @ManyToOne
관계 매핑은 모두 지연 로딩으로 바꿔주시고 성능 이슈가 생기는 부분만 즉시로딩으로 변경해보세요

2019-08-07 13:51 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/comment/service/CommentService.java
> +        Article article = articleRepository.findById(articleId).orElseThrow(() -> new NotFoundArticleException(articleId));
CommentService와 ArticleService에서 articleRepository.findById(articleId).orElseThrow(() -> new NotFoundArticleException(articleId));가 계속 반복되고 있네요
아마 순환 참조 때문에 서비스가 아닌 repository를 직접 사용하면서 중복 기능이 생긴걸로 보이네요
서비스도 응용 서비스, 도메인 서비스로 나눠보는건 어떨까요?
도메인 서비스는 CommentService라면 comment 도메인과 관련된 기본 기능만, ArticleService는 article 도메인과 관련된 기본 기능만 제공하고 응용 서비스에서 CommentService, ArticleService를 조합해서 컨트롤러에 기능을 제공하면 순환 참조를 피하면서 중복 기능을 제거할 수 있을거에요

2019-08-07 13:51 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/comment/service/CommentService.java
> +    private Comment checkAuthority(long commentId, long authorId) {
사용자 인증 기능이 CommentService, ArticleService에서 중복해서 나타나고 있네요.
중복되는 checkAuthorizedUser 메서드를 각 서비스에서 처리하지 말고 UserService에 기능을 추가해서 인증해보는건 어떨까요?

2019-08-07 13:51 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/user/domain/User.java
> +    @Convert(converter = EmailConverter.class)
컨버터를 써야할 이유가 없어보이네요
db와 엔티티 간에 데이터를 컨버팅할 필요는 없어보여요
대신 embedded 어노테이션을 활용하는게 어떨까요?

2019-08-07 13:51 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/user/domain/vo/Email.java
> +public class Email {
이 클래스는 embeddable을 붙여보면 어떨까요

2019-08-08 01:36 UTC, heebong commented on src/main/java/techcourse/myblog/article/controller/ArticleExceptionAdvice.java
> +package techcourse.myblog.article.controller;
exception 패키지로 옮기는 것이 아닌 새로운 패키지로 분리하는게 더 좋을까요? 왜 패키지를 다르게 분리해야 하는지 잘 모르겠습니다ㅠ

2019-08-08 01:44 UTC, heebong commented on src/main/java/techcourse/myblog/comment/service/CommentService.java
> +        Article article = articleRepository.findById(articleId).orElseThrow(() -> new NotFoundArticleException(articleId));
새로운 서비스를 만든다면, 도메인별로 나누어진 지금의 패키지 구조에서 어느 패키지에 넣어야 할지 모르겠습니다. 두 패키지의 서비스를 모두 사용하는건데.. 어느 구조로 만들어야 할지 모르겠습니다ㅠ 패키지 구조를 변경해야할까요?

2019-08-08 01:49 UTC, heebong commented on src/main/java/techcourse/myblog/MyblogApplication.java
> +    public ModelMapper modelMapper() {
변경했습니다. config 패키지 밑에 AppConfig 클래스를 새로 만들었는데 확인 부탁드립니다!

2019-08-08 02:06 UTC, heebong commented on src/main/resources/templates/article.html
> +        const commentTemplate =
변경했습니다. 확인 부탁드립니다!

2019-08-08 02:10 UTC, heebong commented on src/main/java/techcourse/myblog/utils/Error.java
> +package techcourse.myblog.utils;
애초에 Error class위해 만든 패키지라 패키지 이름을 utils에서 errors로 변경했는데 적절한건지 모르겠습니다. 확인 부탁드립니다!

2019-08-08 02:16 UTC, heebong commented on src/main/java/techcourse/myblog/article/controller/ArticleExceptionAdvice.java
> +package techcourse.myblog.article.controller;
우선 각각 handler 패키지를 생성해 이동시켰습니다. 확인 부탁드립니다!

2019-08-08 04:25 UTC, heebong commented on src/main/java/techcourse/myblog/article/domain/Article.java
> +    private String title;
추가했습니다! 길이만 제한하면 될거같아 length만 제한했습니다. (contents는 기본값이라 추가하지 않았습니다.) 확인 부탁드립니다!

2019-08-08 04:25 UTC, heebong commented on src/main/java/techcourse/myblog/user/domain/User.java
> +    @Convert(converter = EmailConverter.class)
변경했습니다. 확인 부탁드립니다!

2019-08-08 04:28 UTC, heebong commented on src/main/java/techcourse/myblog/user/domain/vo/Email.java
> +public class Email {
변경했습니다! 그런데 embeddable로 사용하려면 기본 생성자가 존재해야해서 필드 타입을 final이 아닌 것으로 변경했습니다. 그런데 계속 vo 패키지 안에 두어도 괜찮을지 질문드립니다. 지금 로직에선 여전히 vo로 사용되는거같은데... 계속 vo 패키지에 두어도 괜찮을까요?

2019-08-08 04:48 UTC, heebong commented on src/main/java/techcourse/myblog/article/domain/Article.java
> +    @ManyToOne
즉시 로딩은 쿼리를 조회했을 때 연관된 엔티티도 함께 조회되는 것이고 (`FetchType.EAGER`)
지연 로딩은 연관된 엔티티는 조회되지 않고 실제 사용되는 구문이 나올 때 쿼리를 날려 조회하는 것이며 (`FetchType.LAZY`) 디폴트는 `FetchType.EAGER` 라고 되어있네요.
(또한 쿼리 조회시 실제 사용하지 않는 엔티티까지 영속성 컨텍스트에 올려두는건 비효율적이라고 하네요)
여태까지 기본값을 반대로 알고있었네요. 성능에 무리가 가지 않는 한으로 로딩 방법을 변경하였습니다!

2019-08-08 04:49 UTC, heebong commented on src/main/java/techcourse/myblog/comment/domain/Comment.java
> +    @ManyToOne
변경했습니다. 확인 부탁드립니다!

2019-08-08 05:12 UTC, heebong commented on src/main/java/techcourse/myblog/article/dto/ArticleResponseDto.java
> +    public boolean matchAuthorId(long authorId) {
변경했습니다. 확인 부탁드립니다!

2019-08-08 05:24 UTC, heebong commented on src/main/java/techcourse/myblog/comment/controller/CommentController.java
> +    public CommentResponseDto createComment(@PathVariable long articleId, UserSession userSession, @RequestBody CommentCreateDto commentDto) {
분리했습니다. 확인 부탁드립니다!

2019-08-08 06:03 UTC, heebong commented on src/main/java/techcourse/myblog/comment/service/CommentService.java
> +        Article article = articleRepository.findById(articleId).orElseThrow(() -> new NotFoundArticleException(articleId));
우선 repository가 아닌 service를 참조하는걸로 변경했습니다. 두개의 서비스를 같이 사용하는 부분만 다시 서비스를 나누어 만드는게 좋을까요??

2019-08-08 06:29 UTC, heebong commented on src/main/java/techcourse/myblog/comment/service/CommentService.java
> +    private Comment checkAuthority(long commentId, long authorId) {
❓ UserService에 기능을 추가했는데... 이렇게 하는게 맞는지 모르겠습니다. 더 좋은 방법이 있을거같은데ㅠㅠ 제가 의도를 잘 이해한걸까요?

2019-08-10 01:24 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/article/controller/ArticleExceptionAdvice.java
> +package techcourse.myblog.article.controller;
controller와 advice의 관심사가 다르니 패키지도 분리해서 관리하자는 의미였어요
희봉님께서는 분리할 필요가 없다고 느끼시거나 컨트롤러와 연관이 강한 객체라 생각하시면 컨트롤러 밑에 패키지를 추가하는 방법도 있을거에요

2019-08-10 01:27 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/article/domain/Article.java
> +    private String title;
Column 어노테이션은 db와 어떻게 매핑되는지 알려주는 메타 데이터 역할도 있어요
contents가 테이블에서 어떤 타입, 길이, nullable한지 직접 db 조회하지 않고도 알게 해주죠.
contents는 Lob이라는 어노테이션도 고려해보세요

2019-08-10 01:29 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/article/dto/ArticleResponseDto.java
> +    public boolean matchAuthorId(long authorId) {
dto 코드에서 삭제도 해주세요 ㅎㅎ

2019-08-10 01:33 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/comment/service/CommentService.java
> +        Article article = articleRepository.findById(articleId).orElseThrow(() -> new NotFoundArticleException(articleId));
ArticleService는 CommentService를 사용하는 부분이 없어서 문제가 없네요
지금 구조로 가도 좋습니다 👍

2019-08-10 01:42 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/comment/service/CommentService.java
> +    private Comment checkAuthority(long commentId, long authorId) {
인증 로직을 user 객체로 넘기셨네요 👍 
지금 방법도 나쁘지 않습니다만 도메인에서 처리하게 된다면 이런 방법도 가능하겠죠

```java
    public void delete(long commentId, long authorId) {
        Comment comment = findById(commentId);

        User found = Optional.ofNullable(comment.getAuthor())
                .orElseThrow(() -> new NotFoundUserException("존재하지 않는 사용자입니다."));

        found.checkMatchUser(authorId);

        commentRepository.delete(comment);
    }
```

2019-08-10 01:49 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/user/domain/vo/Email.java
> +public class Email {
vo가 무엇일까요?
email, name, password 모두 변경 가능하거나 기능이 필요하지 않을까요? (name 객체는 이미 updateName라는 기능이 있네요.)
희봉님이 고민해보시고 결정해보세요!

2019-08-10 01:50 UTC, kang-hyungu approved these changes
희봉님 작업하신 내용 확인했어요
질문 주신 내용들은 코멘트 남겼으니 참고하세요!
코드 구현하느라 수고하셨어요! 👍

2019-08-10 01:50 UTC, merged