[비동기 댓글 기능] 무민 미션 제출합니다.
woowacourse/jwp-blog pull request #170
Opened 2019-08-06 07:31 UTC by green4469

2019-08-07 03:10 UTC, woowahan-pjs requested changes
전체적인 설계와 깔끔한 코드 구현이 좋았습니다. 👍 
간단한 생각거리를 남겼으니 코드에 반영해 주셔도 좋습니다.
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

2019-08-07 03:10 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/presentation/RestCommentController.java
> +    @PostMapping("/articles/{articleId}/comments/rest")
URL 뒤에 'rest'를 붙이는 것보다 'rest/articles/...', 'api/articles/...' 등은 어떨까요?

2019-08-07 03:10 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/presentation/RestCommentController.java
> +        User commenter = (User) httpSession.getAttribute(LOGGED_IN_USER_SESSION_KEY);
`HandlerMethodArgumentResolver`를 구현하여 중복 코드를 제거해 보면 어떨까요?

2019-08-07 03:10 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/presentation/RestCommentController.java
> +        if (!comment.getCommenter().equals(httpSession.getAttribute(LOGGED_IN_USER_SESSION_KEY))) {
객체에 메시지를 던지도록!

2019-08-07 03:10 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/service/CommentService.java
> +    public List<CommentResponseDto> findByArticleId(long articleId) {
메서드 이름은 메서드의 정확한 동작을 구체적으로 나타내는 것이 좋겠죠?

```suggestion
    public List<CommentResponseDto> findAllByArticleId(long articleId) {
```

2019-08-07 08:09 UTC, green4469 commented on src/main/java/techcourse/myblog/presentation/RestCommentController.java
> +        User commenter = (User) httpSession.getAttribute(LOGGED_IN_USER_SESSION_KEY);
반영했습니다! HttpSession 에서 유저를 가져오는 로직을 Argument Resolver에 넣어놓고 재사용했습니다.

2019-08-07 08:28 UTC, green4469 commented on src/main/java/techcourse/myblog/presentation/RestCommentController.java
> +    @PostMapping("/articles/{articleId}/comments/rest")
반영했습니다!

2019-08-07 08:31 UTC, green4469 commented on src/main/java/techcourse/myblog/presentation/RestCommentController.java
> +        if (!comment.getCommenter().equals(httpSession.getAttribute(LOGGED_IN_USER_SESSION_KEY))) {
... 부끄럽네요. 반영했습니다~

2019-08-07 08:33 UTC, green4469 commented on src/main/java/techcourse/myblog/service/CommentService.java
> +    public List<CommentResponseDto> findByArticleId(long articleId) {
반영했습니다!

2019-08-09 00:50 UTC, woowahan-pjs requested changes
간단한 생각거리를 남겼으니 코드에 반영해 주셔도 좋습니다.
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

2019-08-09 00:50 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/presentation/RestCommentController.java
> +        return commentService.makeResponseWithCommentsOf(articleId);
아래의 코드는 `CommentService`에서 하나의 메서드로 관리하면 어떨까요?

```java
long articleId = commentService.getArticleIdOf(commentId);
commentService.validateCommenter(commentId, user);
commentService.update(commentId, commentRequestDto);
return commentService.makeResponseWithCommentsOf(articleId);
```

2019-08-09 00:50 UTC, woowahan-pjs commented on src/main/resources/static/js/comment.js
> +    "<li class=\"comment-item border bottom mrg-btm-30\">\n"+
ES6의 템플릿 문자열(template string)을 써보면 어떨까요? 아래의 글이 도움 될 거예요.
http://hacks.mozilla.or.kr/2015/08/es6-in-depth-template-strings-2

2019-08-09 01:43 UTC, green4469 commented on src/main/java/techcourse/myblog/presentation/RestCommentController.java
> +        return commentService.makeResponseWithCommentsOf(articleId);
반영했습니다 :D

2019-08-09 02:08 UTC, green4469 commented on src/main/resources/static/js/comment.js
> +    "<li class=\"comment-item border bottom mrg-btm-30\">\n"+
반영하였습니다. :D

2019-08-09 08:35 UTC, woowahan-pjs approved these changes
블로그 미션을 수행하느라 대단히 고생 많으셨습니다. 💯 
좋은 개발자가 되기 위한 소중한 밑거름이 되었길 바랍니다.
이만 Merge 하겠습니다.

2019-08-09 08:35 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/presentation/CommentController.java
> +//    @PutMapping("/{commentId}")
주석 제거!

2019-08-09 08:35 UTC, merged