[비동기 댓글 기능] 코맥 미션 제출합니다.
woowacourse/jwp-blog pull request #171
Opened 2019-08-06 07:51 UTC by CODEMCD

ajax를 처음 사용하여 미션을 수행하면서 부족한 점이 많습니다. 그리고 배포 및 로깅은 시간이 부족하여 아직 제대로 이해하지 못하였는데 계속해서 공부해나가겠습니다. 많은 지적 부탁드립니다! 감사합니다!

2019-08-07 14:49 UTC, woowahanCU reviewed
TitleConstraintValidator, EmailConstraintValidator가 repository와 연관관계를 가지고 있던데요.
필수 값, 값의 형식, 범위 등은 [Presentation Layer](https://stackoverflow.com/questions/12429729/controller-belongs-to-the-presentation-layer)에서 담당하는 것도 좋다고 생각합니다만,
Dto와 Repository가 연관관계가 형성되는 것이 좋은 구조인지는 의문이 드네요.
Presentation Layer에서의 값 검증과 Service Layer, Domain Layer에서 각각에서의 유효성 검증은 다르다고 생각해요. 유효성 체크가 도메인 모델의 속성에 대한 특징인지, 입력 값에 대한 검증인지를 분리하는 것도 유의미하다고 생각해요.
Dto에서는 값의 형식 등을 테스트하는 것이 좋다고 생각합니다.

https://jojoldu.tistory.com/129
https://stackoverflow.com/questions/21073878/validation-in-3-tier-architecture

추가적으로, java bean validator를 사용하여 email 등 포맷의 유효성 검증을 할 수 있어요

https://www.baeldung.com/javax-validation

2019-08-07 14:49 UTC, woowahanCU commented on deploy.sh
> +    echo "> 현재 구동중인 애플리케이션이 없으므로 종료하지 않습니다."
이 시점에서 스크립트를 종료해야 하지 않을까요

2019-08-07 14:49 UTC, woowahanCU commented on src/main/java/techcourse/myblog/web/CommentController.java
> +//        return "redirect:/articles/" + articleId;
사용하지 않는 코드는 제거해주세요.

2019-08-07 14:49 UTC, woowahanCU commented on src/main/java/techcourse/myblog/web/CommentController.java
> +                                       BindingResult bindingResult, HttpSession httpSession) {
사용하지 않는 파라미터도 제거해주세요.

2019-08-07 14:49 UTC, woowahanCU commented on src/test/java/techcourse/myblog/web/CommentControllerTests.java
> +import techcourse.myblog.application.dto.CommentRequest;
DirtiesContext를 사용하셨네요. 이번에 서버에 배포 실습하면서 빌드하는데 너무 오래걸린다는 생각이 들지는 않았나요?

2019-08-07 14:49 UTC, woowahanCU commented on src/main/java/techcourse/myblog/application/CommentService.java
> +        commentResponse.setAuthor(modelMapper.map(author, UserResponse.class));
VO 이름이 왜 UserResponse인걸까요? Service Layer에서 갑자기 Reponse가 suffix인 class가 보이니 다소 어색하네요. ArticleDto와는 다른 목적인걸까요?

2019-08-07 14:49 UTC, woowahanCU commented on src/main/java/techcourse/myblog/application/CommentService.java
>          Article article = articleRepository.findById(articleId)
Service를 별도로 구성했다면 해당 Service에 메시지를 보내는 것은 어떨까요.
CommentService와 ArticleRepository, UserRepository가 연관관계를 맺고 있는데요. 
금일 공통피드백 중에 이야기되었던 Facade패턴 관점에서도 한번 생각해보는 것도 의미가 있을 거 같네요.

2019-08-07 14:49 UTC, woowahanCU commented on src/main/java/techcourse/myblog/application/CommentService.java
> +        commentResponse.setAuthor(modelMapper.map(author, UserResponse.class));
ModelMapper를 사용했군요! 
nested 구조를 mapping 할 때 코드복잡도도 증가하고 성능 이슈도 있는걸로 알고 있어요.
이번 미션 진행하는데는 별다른 이슈는 없을 거 같지만, 같이 한번 참고해보세요.
https://stackoverflow.com/questions/36717365/how-to-use-modelmapper-to-convert-nested-classes
https://www.baeldung.com/java-performance-mapping-frameworks

그리고 현재 패턴대로면 중첩 구조가 늘어날 수록 Dto 변환로직이 Service Layer에 계속 증가하게 될텐데요. 
이 구조를 개선하려면 어떻게 하는 것이 좋을까요

2019-08-07 14:49 UTC, woowahanCU commented on src/main/java/techcourse/myblog/web/CommentController.java
> +    public CommentController(CommentService commentService, ObjectMapper objectMapper) {
ObjectMapper는 사용하려다 만걸까요?

2019-08-07 14:49 UTC, woowahanCU commented on src/main/java/techcourse/myblog/application/CommentService.java
>      public List<Comment> findCommentsByArticle(Article article) {
CommentService의 메서드이니 findByArticle이라고 해도 의미가 전달될거 같아요. 
이런 부분도 중복이라고 생각되거든요.
팀에 따라서는 인자로 Article을 넣어주니 findBy(Article article)이라고만 해도 괜찮다는 곳들도 있습니다. 

추가적으로, JpaRepository와 Controller Naming convention을 고려해서 각 Service, Controller들의 메서드 이름이 적절한지도 한번 생각해보는 게 좋을거 같아요. 
현재는 작은 애플리케이션이라 문제가 없어보이지만, 조금만 규모가 커져도 Naming convention, 혹은 operator의 시그니처가 통일되지 않으면 코드를 파악하는데 불필요한 에너지가 들어가게 되는 거 같아요.

2019-08-07 14:55 UTC, woowahanCU commented on deploy.sh
> +JAR_NAME=$(ls $REPOSITORY/jwp-blog/ | grep 'myblog' | tail -n 1)
이 부분은 버그 가능성을 내포하고 있다고 생각해요. 배포버전이 시간순인지, version 정보를 나타내는지는 모르겠지만 버그가능성을 내포하고 있다고 생각해요. ls 명령어를 사용해야겠다면 실제 파일 생성일자를 기준으로 체크하는 것은 어떨까요

https://zetawiki.com/wiki/%EB%A6%AC%EB%88%85%EC%8A%A4_%ED%8C%8C%EC%9D%BC_%EB%82%A0%EC%A7%9C%EC%88%9C_%EB%B3%B4%EA%B8%B0

2019-08-07 15:04 UTC, woowahanCU commented on src/main/java/techcourse/myblog/web/CommentController.java
> +        return commentService.save(commentRequest, articleId, user.getId());
이번 미션 진행하면서 ResponseEntity를 사용해보는 경험을 해봤어도 좋았을 텐데요..

https://stackoverflow.com/questions/26549379/when-use-responseentityt-and-restcontroller-for-spring-restful-applications

2019-08-07 15:06 UTC, woowahanCU requested changes
안녕하세요! 리뷰어 CU입니다.
몇가지 피드백 남겨두었으니 확인해보시고 궁금한 점 있으면 DM 남겨주세요~

2019-08-09 00:32 UTC, CODEMCD commented on src/main/java/techcourse/myblog/web/CommentController.java
> +//        return "redirect:/articles/" + articleId;
피드백 감사합니다! 반영하였습니다.

2019-08-09 00:37 UTC, CODEMCD commented on src/main/java/techcourse/myblog/web/CommentController.java
> +                                       BindingResult bindingResult, HttpSession httpSession) {
피드백 감사합니다! 반영하였습니다.

2019-08-09 00:44 UTC, CODEMCD commented on src/main/java/techcourse/myblog/application/CommentService.java
> +        commentResponse.setAuthor(modelMapper.map(author, UserResponse.class));
피드백 감사합니다!

현재 사용하고 있는 ```UserResponse```는 DTO로 사용하고 있는 클래스입니다. ```CommentResponse``` DTO 클래스를 view로 보내줄 때 USER를 같이 전달해야 하는데 비밀번호가 있는 ```User``` 클래스보다 비밀번호가 없는 ```USerResponse``` DTO 클래스를 보내주는 것이 좋다고 판단하여 위와 같이 구현하였습니다.

추가로 이전의 피드백에서 Response와 Request는 보통 DTO로 사용하므로 'Dto'라는 접미사를 제거해도 좋다고 하여 이를 반영한 클래스 이름입니다. ```ArticleDto```는 response와 request 모두 같은 DTO 클래스를 사용하므로 이를 통일하였습니다.

2019-08-10 06:18 UTC, CODEMCD commented on src/main/java/techcourse/myblog/application/CommentService.java
>          Article article = articleRepository.findById(articleId)
피드백 감사합니다!

```CommentService```가 자신이 필요한 ```CommentRepository```를 제외하고 다른 repository를 의존하는 것에 대해 생각해보았습니다. 이를 구현할 때 생각은 service가 repository보다 변경 가능성이 크기 때문에 repository를 사용하는 것이 좋겠다는 생각을 하였습니다. 그뿐아니라 현재 service는 DTO를 반환하고 있기 때문에 다른 service에서 이를 다시 변환해야하는 비용이 발생한다고 생각하여 repository를 사용하게 되었습니다.

하지만 피드백을 받고 다시 생각해본 결과 
- ```CommentService``` 클래스에서 ```UserService```가 아닌 ```UserRepository``` 클래스를 의존한다면 새로운 의존관계가 생겨 전체적으로 의존관계가 더욱 복잡해진다고 느껴졌습니다.
- 위에서 말한 DTO 클래스를 사용하는 부분은 Service와 Controller 사이에서 필요한 메서드만 DTO를 사용하고 그 외에는 도메인을 사용하므로 변환해야하는 비용은 필요하지 않았습니다.

마지막으로 Facade 패턴을 사용하는 것은 현재 크기의 Service에서는 사용하지 않아도 된다고 생각하였습니다. Facade 패턴은 여러 의존관계에서 호출해야할 메서드가 많을 때 이를 하나의 클래스로 추상화하여 하나의 메서드만 호출하도록 만드는 것으로 이해하였습니다. 하지만 현재 서비스에서는 최대 2개의 의존관계가 존재하고 그에 따라 2개의 메서드를 호출하고 있습니다. 현재 2개 정도는 아직까지 필요성을 느끼지 못하였습니다.

2019-08-10 07:04 UTC, CODEMCD commented on src/main/java/techcourse/myblog/application/CommentService.java
>      public List<Comment> findCommentsByArticle(Article article) {
피드백 감사합니다!

제공해주신 링크를 참고하여 DB와 중복되지 않는 용어를 사용하도록 하였습니다. (```save, modify, remove```)그리고 Article, User, Comment가 중복되는 이름은 모두 제거하였습니다.

2019-08-10 13:28 UTC, CODEMCD commented on src/main/java/techcourse/myblog/application/CommentService.java
> +        commentResponse.setAuthor(modelMapper.map(author, UserResponse.class));
피드백 감사합니다!

```ModelMapper```를 사용할 때 단점을 공부할 수 있었습니다. 특히 Entity에서 ```setter```가 생기는 문제점이 저에게는 크게 다가왔습니다. 그래서 따로 ```Assembler```를 만들어 여기서 DTO와 Entity를 변환하도록 변경하였습니다.

그리고 Controller와 Service사이에서 통신할 때와 Controller에서 View로 데이터를 보낼 때 User의 비밀번호가 없는 것이 보안상 좋다고 생각하여 DTO로 만들어 주고받도록 변경하였습니다.

2019-08-11 05:13 UTC, CODEMCD commented on src/main/java/techcourse/myblog/web/CommentController.java
> +    public CommentController(CommentService commentService, ObjectMapper objectMapper) {
피드백 감사합니다!

네 사용하지 않는 부분인데, 확인하지 못했습니다. 죄송합니다. 지웠습니다!

2019-08-11 05:16 UTC, CODEMCD commented on src/test/java/techcourse/myblog/web/CommentControllerTests.java
> +import techcourse.myblog.application.dto.CommentRequest;
피드백 감사합니다!

네 저도 테스트가 매우 오래 걸린다고 생각하였습니다. 테스트는 빠르게 동작하다는 것이 중요하다는 것을 알게 되었고, 이부분을 수정하였습니다. ```DritiesContext```를 초기에 사용한 이유는 게시글 id를 어떻게 줄지 고민하다가 서버를 계속 재시작해주면 이를 신경 쓸 필요가 없다고 생각했습니다.

```DiritesContext```를 삭제하고 게시글 id는 response 헤더에서 가지고 오고, 댓글 id는 ```@AfterEach```를 통해 한 메소드가 실행될 때마다 1을 증가시키는 방식으로 변경하였습니다.

2019-08-11 05:46 UTC, CODEMCD commented on deploy.sh
> +    echo "> 현재 구동중인 애플리케이션이 없으므로 종료하지 않습니다."
피드백 감사합니다!

현재 스크립트는 새로 받은 버전의 서버 코드를 바탕으로 애플리케이션을 재시작해주기 위한 스크립트입니다.따라서 현재 동작중인 애플리케이션이 존재한다면 이를 종료하고 새로 서버를 시작하고, 그렇지 않다면 종료 로직 없이 바로 서버를 재시작하고 있습니다. 위의 ```if```문은 현재 애플리케이션이 동작중인지 아닌지를 판단하는 조건문이고 조건의 결과와 관계없이 서버를 실행해야 하므로 계속해서 스크립트를 진행해야 한다고 생각합니다.

2019-08-11 06:00 UTC, CODEMCD commented on deploy.sh
> +JAR_NAME=$(ls $REPOSITORY/jwp-blog/ | grep 'myblog' | tail -n 1)
피드백 감사합니다!

배포 파일이 여러 개가 있을 수 있다고 생각하여 가장 최근에 만들어진 날짜를 실행하도록 변경하였습니다.

2019-08-11 06:53 UTC, CODEMCD commented on src/main/java/techcourse/myblog/web/CommentController.java
> +        return commentService.save(commentRequest, articleId, user.getId());
피드백 감사합니다!

```ResponseEntity<>```를 사용해보았습니다.

2019-08-12 08:13 UTC, woowahanCU commented on src/test/java/techcourse/myblog/web/CommentControllerTests.java
> +    private static int commentId = 1;
Junit 테스트간에는 영향을 서로 주어서는 안됩니다. static 변수를 사용하여 테이블을 조작할 경우 다른 Class의 테스트에서 Comment를 사용하여 테스트하는 경우 영향이 미칠 수도 있습니다.

2019-08-12 08:13 UTC, woowahanCU commented on src/main/java/techcourse/myblog/application/CommentService.java
> +        commentResponse.setAuthor(modelMapper.map(author, UserResponse.class));
흠.. 혹시 리뷰어가 누구이셨나요? Controller단에 이미 HttpServletRequest 등의 클래스들이 있어서 조는 의미가 상당히 모호하다고 느껴져서요.

2019-08-12 08:28 UTC, woowahanCU commented on src/main/java/techcourse/myblog/application/CommentService.java
>          Article article = articleRepository.findById(articleId)
아, 뭔가 오해가 있군요. 저희가 지난 시간에 논했던 'service layer를 facade 패턴의 일종으로 바라봤던 시각'에 대한 출처가 아래인데요. 한번 참고해보세요.

http://www.informit.com/articles/article.aspx?p=1398617&seqNum=4

_"In the domain facade approach a Service Layer is implemented as a set of thin facades over a Domain Model (116). The classes implementing the facades don't implement any business logic. Rather, the Domain Model (116) implements all of the business logic. The thin facades establish a boundary and set of operations through which client layers interact with the application, exhibiting the defining characteristics of Service Layer."_

```
도메인 파사드 방식에서는 서비스 계층을 도메인 모델 위에서 thin facade의 집합으로 구현한다. 파사드를 구현하는 클래스는 비즈니스 논리를 전혀 구현하지 않으며, 도메인 모델이 모든 비즈니스 논리를 구현한다. thin facade는 클라이언트 계층이 애플리케이션과 상호작용하기 위한 작업 집합과 경계를 형성하며 서비스 계층의 근본적 특성을 나타낸다. 
```

2019-08-12 08:31 UTC, woowahanCU commented on src/main/java/techcourse/myblog/application/CommentService.java
> +        commentResponse.setAuthor(modelMapper.map(author, UserResponse.class));
아래 링크도 한번 같이 읽어보세요~ 

http://redutan.github.io/2016/04/15/poeaa-distribution-pattern

2019-08-12 08:55 UTC, woowahanCU approved these changes
미션 진행하느라 고생 많았어요! 👍 
팀 프로젝트하면서 지난 5주동안 고민했던 것들을 같이 나눠보고 적용해보는 시간 가지길 바래요.
몇가지 피드백 남겼는데 궁금한 부분 있으면 DM 남겨주시구요. 이번 미션은 여기서 Merge할게요 😀

2019-08-12 08:55 UTC, woowahanCU commented on logFile.log
> +395  [restartedMain] DEBUG o.s.b.c.l.ClasspathLoggingApplicationListener - Application started with classpath: [file:/Users/sungbum/Documents/GIT/Woowahantechcourse/level-2/jwp-blog/out/production/cl
이런 파일들은 .gitignore를 통해 제외해주세요

2019-08-12 08:55 UTC, woowahanCU commented on src/main/java/techcourse/myblog/DemoApplicationRunner.java
> +@Profile("!test")
```suggestion
@Profile("test")
```
왜 느낌표가 붙어 있는 것이지요..?

2019-08-12 08:55 UTC, woowahanCU commented on src/main/java/techcourse/myblog/application/ArticleService.java
> +        article.updateArticle(articleAssembler.convertToArticle(articleDto, author));
```suggestion
        article.update(articleAssembler.convertToArticle(articleDto, author));
```
그리고 convert의 결과가 무엇인지 지역변수로 두는 것도 의미가 있다고 생각합니다.

2019-08-12 08:55 UTC, woowahanCU commented on src/main/java/techcourse/myblog/application/ArticleService.java
> +        return articleDto;
전달받은 인자를 그대로 다시 리턴하기보다는 요청처리한 결과 entity를 가지고 dto로 매핑하여 리턴하는 것이 좋다고 생각합니다.
현재 메서드는 아래 테스트와 input/output 기준으로 테스트했을시에 차이가 없습니다.
```java
    public ArticleDto modify(ArticleDto articleDto, Long articleId, UserResponse userResponse) {
        articleDto.setId(articleId);
        return articleDto;
    }
```

2019-08-12 08:55 UTC, woowahanCU commented on src/main/java/techcourse/myblog/application/ArticleService.java
> +    private Article findByUser(Long articleId, UserResponse userResponse) {
checkAuthenticatedAuthor 메서드와 상당부분 구현이 같은데요. 중복으로 작성한 이유가 따로 있을까요?

2019-08-12 08:55 UTC, woowahanCU commented on src/main/java/techcourse/myblog/application/CommentService.java
> +                    return commentAssembler.convertToResponse(comment, author);
1. 현재 Comment를 조회해오면 Author을 알수가 없나요?
2. 이 부분도 method를 분리하는 것이 좋을 거 같아요. 단일 책임원칙위반이라고 생각합니다.

```java
    public List<CommentResponse> findAllByArticle(Long articleId) {
        Article article = articleService.findById(articleId);
        return findAllBy(article).stream()
                .map(this::getCommentResponse)
                .collect(toList())
```

2019-08-12 08:55 UTC, woowahanCU commented on src/main/java/techcourse/myblog/application/CommentService.java
> +            throw new NotSameAuthorException("해당 작성자만 댓글을 수정할 수 있습니다.");
Exception을 흘려보내고 있네요. Exception chaining을 하려면 어떤 방식이 좋을지도 한번 고민해보세요.

https://www.slipp.net/questions/350

2019-08-12 08:55 UTC, woowahanCU commented on src/test/java/techcourse/myblog/MyblogApplicationTests.java
> +    void contextLoads() {
사용하지 않는 코드는 제거해주세요.

2019-08-12 08:55 UTC, woowahanCU commented on src/test/java/techcourse/myblog/application/CommentServiceTests.java
>      @Mock
mock과 mockbean의 차이는 무엇일까요?

https://stackoverflow.com/questions/44200720/difference-between-mock-mockbean-and-mockito-mock

2019-08-12 08:56 UTC, merged