[비동기 댓글 기능] 규동 미션 제출합니다.
woowacourse/jwp-blog pull request #174
Opened 2019-08-06 08:33 UTC by kmdngyu

안녕하세요! 
배포 관련 스크립트는 최상위 폴더 deploy.sh에 작성하였습니다.
많은 지적 부탁드립니다.
감사합니다!

2019-08-07 08:57 UTC, gracefulBrown requested changes
안녕하세요. 리뷰어 브라운입니다.
ResponseEntity를 사용한 부분 인상깊네요 👍 
추가적으로 댓글 조회 하는 API도 만들어서 테스트 코드에서도 사용해보면 좋을 것 같아요.
몇가지 코멘트 남겼으니 확인해보시고 반영할 부분 반영해보시면 좋을 것 같아요!
궁금한 점 있으면 언제든 DM 주세요 :)

2019-08-07 08:57 UTC, gracefulBrown commented on deploy.sh
> +CURRENT_PID=$(lsof -t -i:8080 -s TCP:LISTEN)
👍

2019-08-07 08:57 UTC, gracefulBrown commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +    public ResponseEntity<ResponseMessage> delete(@PathVariable long articleId,
ResponseEntity를 이용한 응답 👍 
ResponseMessage에 대해서도 조금 더 고민해보면 좋을 것 같습니다 :)

2019-08-07 08:57 UTC, gracefulBrown commented on src/main/java/techcourse/myblog/service/dto/ResponseMessage.java
> +    private String message;
응답 결과가 메시지 뿐만이 아니라 객체일 수 있지 않을까요?

2019-08-07 08:57 UTC, gracefulBrown commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +@RequestMapping("/articles/{articleId}/comments")
댓글 조회에 대해서도 ajax로 요청해보면 어떨까요?
이에 따른 테스트 코드도 구현해보면 다른 테스트 결과를 확인할 때 좋을 것 같습니다.

2019-08-07 08:57 UTC, gracefulBrown commented on src/test/java/techcourse/myblog/controller/CommentControllerTest.java
> +            assertThat(commentReopsitory.findAll().size()).isEqualTo(1);
결과를 repository로 확인하는 방법 대신 직접 요청해서 확인해보면 어떨까요?

2019-08-07 08:57 UTC, gracefulBrown commented on src/main/resources/logback-access.xml
> +    <appender name="roll-by-time-and-size" class="ch.qos.logback.core.rolling.RollingFileAppender">
👍

2019-08-07 08:57 UTC, gracefulBrown commented on src/test/java/techcourse/myblog/controller/ArticleControllerTest.java
> +        webTestClient.post().uri("/users")
테스트 중복 코드를 줄일 수 있을 것 같아요 :)

2019-08-11 15:53 UTC, kmdngyu commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +    public ResponseEntity<ResponseMessage> delete(@PathVariable long articleId,
메시지에 data를 제너릭으로 만들어 다른 객체를 메시지 내부에 json으로 매핑 할 수 있게 하였습니다.

2019-08-11 15:54 UTC, kmdngyu commented on src/main/java/techcourse/myblog/service/dto/ResponseMessage.java
> +    private String message;
반영하였습니다!

2019-08-11 15:54 UTC, kmdngyu commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +@RequestMapping("/articles/{articleId}/comments")
댓글 조회(로드)를 ajax 구현으로 변경하였습니다.

2019-08-11 15:54 UTC, kmdngyu commented on src/test/java/techcourse/myblog/controller/CommentControllerTest.java
> +            assertThat(commentReopsitory.findAll().size()).isEqualTo(1);
수정하였습니다!

2019-08-11 15:55 UTC, kmdngyu commented on src/test/java/techcourse/myblog/controller/ArticleControllerTest.java
> +        webTestClient.post().uri("/users")
테스트 유틸 클래스로 분리하였습니다 :)

2019-08-11 15:57 UTC, kmdngyu commented
리뷰 정말 감사드립니다! 내일 안 바쁘실 때 오프라인으로 몇 가지 질문드려도 괜찮을까요?

2019-08-12 07:57 UTC, gracefulBrown approved these changes
피드백 반영 잘 해주셨네요 👍 
질문있다 하셨는데 
오프라인으로 궁금한거 많이 질문해주세요 ^^
수고많으셨습니다. 머지할게요~

2019-08-12 07:57 UTC, gracefulBrown commented on src/main/java/techcourse/myblog/controller/CommentController.java
> +        return new ResponseEntity<>(responseMesage, HttpStatus.OK);
응답 코드로 Created를 내려주어도 좋을 것 같아요! 
(location 값도 같이)

2019-08-12 07:57 UTC, merged