[비동기 댓글 기능] 김고래 미션 제출합니다.
woowacourse/jwp-blog pull request #176
Opened 2019-08-06 08:41 UTC by ep1stas1s

2019-08-07 07:42 UTC, woowahan-pjs requested changes
전체적인 설계와 깔끔한 코드 구현이 좋았습니다. 👍 
간단한 생각거리를 남겼으니 코드에 반영해 주셔도 좋습니다.
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

2019-08-07 07:42 UTC, woowahan-pjs commented on build.gradle
> +    implementation group: 'org.mindrot', name: 'jbcrypt', version: '0.3m'
`group`, `name`, `version` 방식과 `group:name:version` 방식 중 하나로 통일 부탁해요.

2019-08-07 07:42 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/service/dto/CommentsResponse.java
> +        return comments;
새로운 컬렉션에 담아 외부에 의한 변조를 막는 것은 습관처럼 사용하는 것이 좋습니다.

2019-08-07 07:42 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/web/CommentController.java
> +    public ResponseEntity<Comment> saveComment(@RequestBody @Valid CommentRequest commentRequest, HttpSession httpSession) {
`ResponseEntity` 👍

2019-08-07 07:42 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/web/CommentController.java
> +        Comment comment = commentService.save(commentRequest, (User) httpSession.getAttribute("user"));
`HandlerMethodArgumentResolver`를 구현하여 중복 코드를 제거해 보면 어떨까요?

2019-08-09 01:28 UTC, woowahan-pjs requested changes
간단한 생각거리를 남겼으니 코드에 반영해 주셔도 좋습니다.
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

2019-08-09 01:28 UTC, woowahan-pjs commented on build.gradle
> +    implementation 'com.h2database:h2'
`implementation` 대신 `runtimeOnly`를 사용하면 어떨까요? 왜일까요?

2019-08-09 01:28 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/Comment.java
> +        return Objects.hash(id, contents, createdDate, modifiedDate, commenter, article);
`equals()`처럼 `id`만 가지고 안 될까요?

2019-08-09 01:28 UTC, woowahan-pjs commented on src/test/java/techcourse/myblog/web/CommentControllerTest.java
> +                // TODO: 2019-08-04 아래꺼 안 써도 잘 됨
주석 제거! 왜 잘 될까요?

2019-08-11 03:50 UTC, ep1stas1s commented on src/test/java/techcourse/myblog/web/CommentControllerTest.java
> +                // TODO: 2019-08-04 아래꺼 안 써도 잘 됨
몇 가지 테스트를 해봤는데... 정확히 어느 부분에서 설정을 해줘야 할지 모르겠어서 produces, consumes와 함께 설정해 주었습니다.

2019-08-11 03:50 UTC, ep1stas1s commented on src/main/java/techcourse/myblog/domain/Comment.java
> +        return Objects.hash(id, contents, createdDate, modifiedDate, commenter, article);
당연히 가능하죠! 감사합니다😓

2019-08-11 03:53 UTC, ep1stas1s commented on build.gradle
> +    implementation 'com.h2database:h2'
complie땐 사용하지 않고, runtime에 때만 사용하기 때문입니다.

2019-08-12 04:46 UTC, woowahan-pjs approved these changes
REST Docs에 다국어 지원까지 많은 것을 구현하였네요. 💯 
블로그 미션을 수행하느라 대단히 고생 많으셨습니다.
좋은 개발자가 되기 위한 소중한 밑거름이 되었길 바랍니다.
이만 Merge 하겠습니다.

2019-08-12 04:46 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/CommentRepository.java
> +    List<Comment> findByArticleId(Long articleId);
메서드 이름은 메서드의 정확한 동작을 구체적으로 나타내는 것이 좋겠죠?

```suggestion
    List<Comment> findAllByArticleId(Long articleId);
```

2019-08-12 04:46 UTC, woowahan-pjs commented on src/main/resources/messages.properties
> +name=default\uAC00 \uD544\uC218\uC778\uAC00?
다국어 지원 👍

2019-08-12 05:03 UTC, merged