[비동기 댓글 기능] 히브리 미션 제출합니다.
woowacourse/jwp-blog pull request #181
Opened 2019-08-06 08:46 UTC by yk1028

안녕하세요. 히브리입니다:)
이번 미션에는 백앤드 코드를 바꾼 부분은 많지 않았지만 프론트쪽이 익숙하지 않아서 조금 어려웠습니다.
배포를 위한 쉘 스크립트 코드는 resources에 저장했습니다.
잘 부탁드립니다.

2019-08-09 15:54 UTC, phs1116 requested changes
안녕하세요. 히브리! 
상당히 적은 변경으로 기능을 잘 구현해주셨네요! 👍 
그러다보니 피드백 줄 부분이 많지 않아 간단한 피드백 추가하였습니다.
참고 부탁드리고 궁금한 점 있으시면 언제든지 연락주세요!

2019-08-09 15:54 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/RestCommentController.java
> +@RestController
기존 웹 컨트롤러와 구분되게 api path를 추가하면 좋을 것 같습니다. :)

2019-08-09 15:54 UTC, phs1116 commented on src/main/resources/deploy.sh
> +git pull
어느 브랜치에 대한 배포인지 명확하게 명시하는게 좋을 것 같습니다. :)

2019-08-09 15:54 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/RestCommentController.java
>          Long userId = getLoggedInUser(httpServletRequest).getId();
getLoggedInUser 
한 세션에 대한 로그인 정보를 가져오는 로직이 반복 될 것 같네요.
Argument Resolver를 활용해봐도 좋을 것 같습니다. :)

2019-08-10 05:35 UTC, yk1028 commented on src/main/java/techcourse/myblog/web/RestCommentController.java
> +@RestController
앞에 api path를 추가했습니다.
``` java
@RestController
@RequestMapping(path = "/api/comments")
public class RestCommentController {
   ...
    @GetMapping("/{id}")
    public List<CommentResponseDto> readComments(@PathVariable("id") Long id) {
        return commentService.findCommentsByArticleId(id);
    }
   ...
```
위 코드 처럼 공통된 부분을 묶고 싶은데 404페이지가 나오면서 동작하지 않습니다. 아예 경로설정이 잘못되는것 같은데 원인을 찾지 못해서 질문드립니다.

2019-08-10 05:53 UTC, yk1028 commented on src/main/resources/deploy.sh
> +git pull
명시했습니다!

2019-08-10 06:43 UTC, yk1028 commented on src/main/java/techcourse/myblog/web/RestCommentController.java
>          Long userId = getLoggedInUser(httpServletRequest).getId();
Argument resolver를 활용하여 중복을 제거할 수 있었습니다.

2019-08-10 06:49 UTC, yk1028 commented
좋은 리뷰 감사합니다:)

2019-08-10 15:21 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
피드백 반영 매우 잘해주셨어요 👍 
몇가지 놓치신 게 있는 것 같아서 피드백 조금 추가했습니다.
확인 부탁드리고 궁금하신 점 있으시면 연락주세요. :)

2019-08-10 15:21 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/RestCommentController.java
> +@RestController
말씀하신대로 변경하여 확인해봤는데 큰 문제가 없네요. :)
다시 한번 수정해서 확인해봐도 좋을 것 같아요.

2019-08-10 15:21 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/RestCommentController.java
> +@RestController
기존에 변경 사항이 없어서 코멘트를 달 수 없어 여기에 추가로 달게요. :)
현재 CommentService에서 articleService.findById(articleId)를 호출시 발생하는 예외가 
redirect (status code : 302)로 보내버리는데요,
Web에 특화된 처리다보니 api에서는 다르게 처리하는게 좋을 것 같습니다.  :)

2019-08-10 15:21 UTC, phs1116 commented on src/main/resources/templates/article.html
> +        fetch('/comments/' + articleId)
comment api 주소가 전체적으로 틀린 것 같아요. :)

2019-08-10 15:21 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/RestCommentController.java
> +    @GetMapping("/api/comments/{id}")
`/api/comments/{id}`에서 id가 rest 관점에서는 comments의 id로 보는데요. 현재는 article의 id로 받고있네요. :)
제대로된 URL 설계라면 특정 article이 가지고있는 모든 comment 자원을 가져오라는 의미에서 `/api/articles/{articleId}comments`가 맞습니다. :)

2019-08-10 15:38 UTC, yk1028 commented on src/main/resources/templates/article.html
> +        fetch('/comments/' + articleId)
수정했습니다.

2019-08-10 15:39 UTC, yk1028 commented on src/main/java/techcourse/myblog/web/RestCommentController.java
> +    @GetMapping("/api/comments/{id}")
`/api/articles/{articleId}/comments` 로 수정했습니다!

2019-08-10 17:11 UTC, yk1028 commented on src/main/java/techcourse/myblog/web/RestCommentController.java
> +@RestController
web과 api 패키지를 분리하여 패키지 별로 다른 Exception Advice를 사용해서 서로 다르게 처리하도록 수정했습니다. api에서는 400 BadRequest와 함께 에러메세지를 보내도록 구현했습니다.

2019-08-11 11:25 UTC, phs1116 approved these changes
안녕하세요! 히브리
패키지 분리 👍 
정말 구현 잘해주셨습니다.
이번 단계 머지할게요 :)
개발하시느라 정말 수고 많으셨어요!

2019-08-11 11:25 UTC, phs1116 commented on src/main/java/techcourse/myblog/controller/web/ArticleController.java
> +    private ArticleService articleService;
final로 nonnull을 보장해주는게 좋을 것 같아요 :)

2019-08-11 11:25 UTC, merged