[비동기 댓글 기능] 슬로스 미션 제출합니다.
woowacourse/jwp-blog pull request #184
Opened 2019-08-06 08:53 UTC by soojinroh

2019-08-07 01:12 UTC, ssosso requested changes
안녕하세요, 슬로스~ 쏘쏘입니다:)
깜끔하게 작성하셨네요:) 몇 가지 피드백 드리니 확인 부탁드립니다.

2019-08-07 01:12 UTC, ssosso commented on src/main/java/techcourse/myblog/application/dto/CommentResponse.java
> +    public static class CommentDto {
class를 외부로 분리하면 어떨까요~?
CommentResponse 필드로 위치하는 다른 dto들도 이곳에 중첩되기 시작하면 클래스가 뚱뚱해지고 필요이상으로 복잡해질 가능성이 있습니다:)

2019-08-07 01:12 UTC, ssosso commented on src/main/resources/templates/article.html
> +        // document.getElementById("commentForm").submit();
주석 제거

2019-08-07 01:12 UTC, ssosso commented on src/main/resources/templates/article.html
> +                        </li>`;
별도 메서드로 분리하면 어떨까요~?
수기로 작성하는 것보다 좋은 방법이 있을까요~?

2019-08-07 01:12 UTC, ssosso commented on src/main/java/techcourse/myblog/web/UserController.java
> +
interceptor 처리에서 왜 제거된걸까요~?

2019-08-07 08:05 UTC, soojinroh commented on src/main/resources/templates/article.html
> +        // document.getElementById("commentForm").submit();
삭제했습니다!

2019-08-08 02:00 UTC, soojinroh commented on src/main/java/techcourse/myblog/application/dto/CommentResponse.java
> +    public static class CommentDto {
CommentDto를 외부 클래스로 분리했습니다!

한 가지 여쭤보고 싶은 게 지금 dto 패키지 안에 있는 dto클래스 이름에 dto를 붙이지 않고 있습니다. 예를 들어 LoginReqeust의 경우 LoginRequestDto가 아닌 LoginRequest로 파일명을 해두었습니다. 

그런데 ArticleDto와 CommentDto의 경우에는 이미 Article 클래스와 Comment클래스가 있어 파일명 뒤에 Dto를 뺄 수가 없었는데 이 경우에는 패키지 안에 있는 모든 dto 클래스 이름 뒤에 dto를 붙이는 게 좋을까요 아니면 Article과 Comment의 경우에만 예외라고 생각해 그 두 파일에만 dto를 붙여주는 게 좋을까요...?

2019-08-08 02:06 UTC, soojinroh commented on src/main/resources/templates/article.html
> +                        </li>`;
CommentHTML을 추가하는 기능을 별도의 메서드로 분리했습니다. saveComment() 안에서  모든 작업을 작업을 다 처리하던 기존의 코드에 비해 가독성이 훨씬 좋아진 것 같습니다.

그런데 수기로 작성하는 것보다 좋은 방법이 있을지 질문하신 게
javascript function에 HTML코드를 직접 작성해서 innerHTML로 추가하는 것보다 좋은 방법이 있는지 고민해보면 좋겠다는 건가요...? 수기로 작성한다는 게 어떤 건지 잘 모르겠습니다ㅜ

2019-08-08 02:16 UTC, soojinroh commented on src/main/java/techcourse/myblog/web/UserController.java
> +
interceptor에서 로그인 여부에 따라 경로에 접근 가능한지를 다 정해주다보니 interceptor의 코드가 복잡해져서 
각 controller에서 로그인 확인을 해주는 것으로 수정했는데 그 과정에서 위의 코드도 interceptor에서 제거했습니다.

interceptor에서 모든 처리를 해주자니 interceptor가 복잡해지는 것 같고
각 controller에서 처리하는 것으로 수정을 하니 interceptor의 역할이 무의미해지는 것 같다는 생각이 듭니다...

2019-08-08 02:17 UTC, soojinroh commented on src/main/java/techcourse/myblog/web/UserController.java
> +
interceptor에서 로그인 여부에 따라 경로에 접근 가능한지를 다 정해주다보니 interceptor의 코드가 복잡해져서
각 controller에서 로그인 확인을 해주는 것으로 수정했는데 그 과정에서 위의 코드도 interceptor에서 제거했습니다.

interceptor에서 모든 처리를 해주자니 interceptor가 복잡해지는 것 같고
각 controller에서 처리하는 것으로 수정을 하니 interceptor의 역할이 무의미해지는 것 같다는 생각이 듭니다...

2019-08-09 00:21 UTC, ssosso commented on src/main/resources/templates/article.html
> +                        </li>`;
네네, 슬로스가 생각하시는 그거 맞습니다ㅠ 수기로 작성이라기 보다는 string으로 작성이 더 맞는데 제가 단어 선택을 잘못했어요ㅠㅎㅎ 죄송합니다.
js 안에 string으로 작성하지 않고 진행하는 방법에는 handlebar를 사용할 수 있는데요, handlebar 말고도 handlebar와 같이 템플릿팅을 지원해주는 것을 사용하게 되면 html 태그의 문법을 확인할 수 있는 파일 내에 html을 작성하여 사용할 수 있습니다:) 지금은 참고만 해주시고 나중에 이런 요구사항이 생겼을 때 한번 도전해보시면 좋겠습니다:)

2019-08-09 00:24 UTC, ssosso commented on src/main/java/techcourse/myblog/application/dto/CommentResponse.java
> +    public static class CommentDto {
컨벤션의 문제인 것 같은데요, 다른 개발자가 보아도 일관성만 있다면 둘다 공존해도 된다고 생각합니다:) Article에는 Request를 붙이지 못하는 이유가 있을까요~? Response로도 사용되기 때문일까요~?

2019-08-09 00:27 UTC, ssosso commented on src/main/java/techcourse/myblog/web/UserController.java
> +
Interceptor를 여러 개 만들어서 해결할 수 없을까요~?

2019-08-09 00:33 UTC, ssosso approved these changes
안녕하세요, 슬로스~ :)
댓글 주신 내용에 답변달았습니다~ 반영잘해주셨네요:)
답변달은 내용은 merge 조건에 해당하지 않고 지금 코드로도 충분히 좋다고 생각하여 merge하겠습니다.
다만 더 개발해서 반영하고 싶은 부분이 있으시면 다시 한번 동일하게 pr주시면 됩니다:)
고생많으셨습니다~

2019-08-09 00:33 UTC, merged

2019-08-11 09:50 UTC, soojinroh commented on src/main/java/techcourse/myblog/application/dto/CommentResponse.java
> +    public static class CommentDto {
Aritlce에 Request를 붙이지 않은 건 말씀해주신대로 Response로도 사용될 수 있기 때문에 Request가 아닌 그냥 ArticleDto라고만 했습니다!