[비동기 댓글 기능] 지노 미션 제출합니다.
woowacourse/jwp-blog pull request #188
Opened 2019-08-06 08:59 UTC by hyunssooo

2019-08-06 17:09 UTC, jihan805 requested changes
안녕하세요 지노~!
몇가지 피드백 남겼으니 확인해주세요 :)

2019-08-06 17:09 UTC, jihan805 commented on src/test/java/techcourse/myblog/presentation/controller/CommentControllerTest.java
> +        CommentDto commentDto = new CommentDto();
테스트가 깨지는 것 같아요!
확인 부탁드려요!

2019-08-06 17:09 UTC, jihan805 commented on src/main/java/techcourse/myblog/presentation/controller/CommentController.java
> +        return "{\"editedContents\":\"" + commentDto.getContents() + "\"}";
응답을 위한 dto를 만드는 것이 더 좋을 것 같아요!

2019-08-06 17:09 UTC, jihan805 commented on src/main/java/techcourse/myblog/presentation/controller/CommentController.java
> +@RestController
RestController 사용 👍

2019-08-06 17:09 UTC, jihan805 commented on src/main/java/techcourse/myblog/presentation/controller/CommentController.java
> +        return commentService.save(commentDto, email, articleId);
return 값에 바로 사용하는 대신 변수에 받아서 반환하는 것이 더 좋을 것 같아요!

2019-08-08 09:37 UTC, hyunssooo commented on src/main/java/techcourse/myblog/presentation/controller/CommentController.java
> +        return "{\"editedContents\":\"" + commentDto.getContents() + "\"}";
요청 응답에 사용되는 dto를 나눴습니다 :) 감사합니다! 👍

2019-08-08 09:39 UTC, hyunssooo commented
안녕하세요 써머! 리뷰이 지노입니다! 레벨1 첫 미션에 리뷰 해주시고 너무 오랜만인거 같아요! 
이번에도 리뷰해주셔서 감사합니다 :)

2019-08-08 09:40 UTC, hyunssooo commented on src/test/java/techcourse/myblog/presentation/controller/CommentControllerTest.java
> +        CommentDto commentDto = new CommentDto();
죄송합니다! 테스트 수정, 추가 했습니다!

2019-08-09 14:02 UTC, jihan805 approved these changes
안녕하세요 지노!
피드백 반영 잘해주셨어요 💯 
지금까지 미션 구현하느라 고생 많았어요 :)
머지할게요 !!

2019-08-09 14:02 UTC, merged