[게시글 생성/조회/수정/삭제] 에이든 미션 제출합니다.
woowacourse/jwp-blog pull request #28
Opened 2019-07-12 05:42 UTC by hyperpace

안녕하세요. 에이든입니다.

이번에 spring boot 는 낯선부분이 많아 공부할게 많다는 것을 느꼈습니다.

리뷰 요청드릴게요.

2019-07-12 17:25 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
전체적으로 깔끔하게 잘 구현해주셨습니다. 👍 
간단한 피드백 몇가지 추가했는데요, 참고 부탁드리고
궁금하신 점 있으시면 언제든지 DM주세요 :)

2019-07-12 17:25 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public void setTitle(String title) {
setter를 꼭 써야할까요? :)

2019-07-12 17:25 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +    public int size() {
Repository가 데이터 소스의 리소스를 사용한다는 점에서 count 등의 이름이 더 적합한 네이밍일것 같아요 :)

2019-07-12 17:25 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/ArticleController.java
>      @Autowired
DI시에는 field inejction보다는 constructor injection이 권장됩니다.
아래 블로그 참고해보시면 좋을 것 같네요. :)
https://zorba91.tistory.com/entry/Spring%ED%95%84%EB%93%9C-%EC%A3%BC%EC%9E%85Field-Injection-%EB%8C%80%EC%8B%A0-%EC%83%9D%EC%84%B1%EC%9E%90-%EC%A3%BC%EC%9E%85Constructor-Injection%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%B4%EC%95%BC-%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0

2019-07-12 17:25 UTC, phs1116 commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +                .expectStatus().is3xxRedirection()
테스트코드에 전체적으로 중복되는 부분이 많아보이는데 추상화하여 분리해보면 어떨까요?

2019-07-12 17:25 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +    public void add(Article article) {
일단 해당 클래스에 대해서도 테스트를 작성해보면 어떨까요?

2019-07-12 17:25 UTC, phs1116 commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +        testArticle.setTitle("title");
세터가 아닌 생성자를 통해 값을 설정할 수 있지 않을까요??

2019-07-14 13:48 UTC, hyperpace commented on src/main/java/techcourse/myblog/web/ArticleController.java
>      @Autowired
이 부분이 아직 이해가 힘드네요. 더 참고할 수 있는 자료가 있을까요?

2019-07-15 14:02 UTC, phs1116 approved these changes
안녕하세요! 리뷰어 화투입니다.
피드백 잘 반영해주셔서 감사합니다. 👍 
질문주신 사항의 답변과 간단한 피드백 추가했습니다.
다음 단계 진행하시면서 참고 부탁드릴게요 :)

2019-07-15 14:02 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/ArticleController.java
>      @Autowired
https://ohjongsung.io/2017/06/02/%ED%95%84%EB%93%9C-%EC%A3%BC%EC%9E%85-field-injection-%EC%9D%84-%ED%94%BC%ED%95%98%EC%9E%90

스프링 DI 컨테이너가 각 빈에게 의존성을 어떻게 주입하는지를 공부해보시면 더욱 이해하기 쉬우실 것 같습니다.
관련한 내용이 레벨3에서 진행하는것으로 알고있는데요, 일단 여러 주입 방식이 있고, 장단점이 있다는 점을 참고 해보시면 좋을 것 같아요 :)

2019-07-15 14:02 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +        model.addAttribute("article", articleRepository.get(articleId));
articleRepository.get(articleId)이 null인 경우에 대해서도 처리해주면 좋을것 같네요 :)

2019-07-15 14:02 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +        articles.remove(articleId);
List의 인덱스값에 의존하며, 리스트 내 객체를 remove 할 경우 원래 알고있던 id값과 달라질 위험도 있어보이네요!
특정 엔티티에 대해서 최초 생성된 식별자는 변경되지 않는 편이 좋습니다. :)

2019-07-15 14:02 UTC, merged