[게시글 생성/조회/수정/삭제] 에헴 미션 제출합니다.
woowacourse/jwp-blog pull request #34
Opened 2019-07-12 09:12 UTC by dasistHYOJIN

안녕하세요, 에헴입니다!

스프링 부트는 처음 사용해보지만 강의 덕분에 큰 어려움 없이 미션을 진행할 수 있었습니다.
리뷰 잘 부탁드립니다~

2019-07-13 01:28 UTC, kang-hyungu requested changes
안녕하세요 에헴님 리뷰어 강현구입니다.
처음이라 스프링 적용이 어려우셨을텐데 코드 잘 작성하셨어요
그런데 로컬 환경에서 index 페이지를 못찾네요. 실패하는 테스트도 있구요.
피드백 확인해보시고 다시 점검 부탁드려요!

2019-07-13 01:28 UTC, kang-hyungu commented on build.gradle
> +	compile('org.springframework.boot:spring-boot-devtools')
compile 대신 implementation을 사용하도록 변경하는건 어떨까요

2019-07-13 01:28 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public void setArticleId(Long articleId) {
setter 대신 생성자를 사용해보아요!

2019-07-13 01:28 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +    public Long generateNewId() {
```java
        long currentId = articles.stream()
                .mapToLong(Article::getArticleId)
                .max()
                .orElse(0L);

        return currentId + NEXT_ID;
```

Math.max를 계속 호출하는 것보단 스트림으로 값을 비교하게 하는건 어떨까요

2019-07-13 01:28 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +            targetArticleIndex = articles.get(i).getArticleId().equals(article.getArticleId()) ? i : targetArticleIndex;
1. getter 사용을 줄일 방법은 없을까요?
2. articles.indexOf() 메서드를 활용하면 어떨까요?

2019-07-13 01:28 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +        articles.set(targetArticleIndex, updatedArticle);
collection의 set을 쓰면 지금은 문제 없겠지만 나중에 jpa 도입할 때는 수정해야겠네요
List에서 객체를 교체해버리면 jpa가 감지를 못해서 update 구문이 동작하지 않아요

2019-07-13 01:28 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/web/ArticleController.java
>      private ArticleRepository articleRepository;
field injection을 사용하면 테스트하기 힘들 수 있어요.
constructor injection으로 변경하면 테스트 코드 작성도 용이하고 final 선언도 가능해져요.
더 자세한 내용은 아래 링크 참고하세요.
https://stackoverflow.com/questions/39890849/what-exactly-is-field-injection-and-how-to-avoid-it

2019-07-13 01:28 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +    @PutMapping("/update")
1. uri에 update라고 쓸 필요는 없어요. 이미 http method에서 put으로 어떤 작업인지 알 수 있어요
2. Article 객체 id를 uri에 같이 보내면 어떨까요?

깔끔한 uri 생성을 위해 rest api 디자인 가이드를 참고해보시고 다른 메서드들의 경로도 같이 수정해보아요!
https://meetup.toast.com/posts/92

2019-07-13 01:28 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +        article.setArticleId(latestId);
addArticle 메서드에서 처리할 수 있는 로직 아닐까요?
컨트롤러에 로직 노출하지 않도록 하는게 유지보수 관점에서 더 좋아요

2019-07-13 01:28 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +        articleRepository.findArticleById(articleId).ifPresent(a -> model.addAttribute("article", a));
```suggestion
        articleRepository.findArticleById(articleId)
                         .ifPresent(a -> model.addAttribute("article", a));
```

2019-07-13 01:28 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +        articleRepository.findArticleById(articleId).ifPresent(a -> model.addAttribute("article", a));
```suggestion
        articleRepository.findArticleById(articleId)
                         .ifPresent(a -> model.addAttribute("article", a));
```

2019-07-13 01:28 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +        return new ModelAndView("redirect:/articles/" + latestId);
ModelAndView 객체를 만들 필요는 없지 않나요?

2019-07-13 01:28 UTC, kang-hyungu commented on src/main/resources/templates/article-edit.html
> +    <link rel="stylesheet" href="https://uicdn.toast.com/tui-editor/latest/tui-editor-contents.css">
다른 페이지에서도 중복으로 호출하고 있는 태그가 있네요
thymeleaf의 include 기능을 활용해서 중복을 제거해보아요

2019-07-13 01:28 UTC, kang-hyungu commented on src/main/resources/templates/login.html
> +    <link rel="shortcut icon" href="/images/logo/favicon.ico">
맨 첫번째에 /를 붙일 필요가 있나요?

2019-07-13 01:28 UTC, kang-hyungu commented on src/test/java/techcourse/myblog/domain/ArticleRepositoryTest.java
> +        articleRepository.addArticle(article);
매번 add 하는것 보다 setUp 메서드에서 Article 객체 하나를 미리 저장해두는게 어떨까요?
조회하는 테스트인데 저장을 하는게 이상하기도 하고, 계속 중복해서 테스트마다 add를 호출하고 있네요

2019-07-13 01:28 UTC, kang-hyungu commented on src/test/java/techcourse/myblog/web/ArticleControllerTest.java
> +                .exchange();
응답이 성공했는지 http status 체크도 추가해보아요

2019-07-13 01:28 UTC, kang-hyungu commented on src/test/java/techcourse/myblog/web/ArticleControllerTest.java
> +    private ArticleRepository articleRepository;
article repository bean을 사용하는 방법도 있지만 게시글 추가 api를 호출하는 방법도 있어요. 이 테스트는 인수테스트니 api를 활용해서 게시글을 추가해보아요!

2019-07-13 01:28 UTC, kang-hyungu commented on src/test/java/techcourse/myblog/web/ArticleControllerTest.java
> +        assertThat(articleRepository.findAll().contains(article)).isTrue();
인수테스트니 repository로 똑같은 객체가 있는지 찾지 말고 api로 조회 결과에 등록한 내용이 있는지 찾도록 바꿔보아요

2019-07-13 01:28 UTC, kang-hyungu commented on src/test/java/techcourse/myblog/web/ArticleControllerTest.java
> +        assertThat(articleRepository.findAll().contains(article)).isTrue();
아래 테스트랑 겹치니 이건 테스트 안해도 되겠네요
http status만 체크하거나 아래 게시물_작성_테스트로 충분해보이네요

2019-07-14 06:45 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +    public Long generateNewId() {
오 스트림으로 할 수 있는 방법이었네요!

하지만 생각해보니 이렇게  id 값을 부여하는 방법이 중복이나 게시글 관리할 때 혼선을 줄 수도 있겠다는 생각이 들었습니다. (가장 최근 게시글을 삭제하는 경우, 다음에 등록되는 게시글은 같은 id를 공유하게 되니까요)
그래서 클래스에 멤버변수로 id를 저장하고 하나씩 증가시키도록 하는 것으로 변경했습니다!

2019-07-14 07:07 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +    @PutMapping("/update")
오호!
덕분에 URI와 HTTP 메서드의 역할을 구분지어 표현할 수 있다는 걸 알게 되었습니다.
URI에 articleId를 보내면 repository에서도 선택된 게시글을 탐색하는 연산을 제거할 수 있겠네요!

2019-07-14 09:52 UTC, dasistHYOJIN commented on src/test/java/techcourse/myblog/domain/ArticleRepositoryTest.java
> +        articleRepository.addArticle(article);
넵 수정했습니다!

2019-07-14 10:21 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +        return new ModelAndView("redirect:/articles/" + latestId);
코드를 짤 때 여러 리턴타입을 활용해 본다고 사용했다가 고치는 걸 깜빡했네요ㅠㅠ
다음 미션 때는 꼼꼼하게 확인하겠습니다..!

2019-07-14 16:00 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +        articles.set(targetArticleIndex, updatedArticle);
몰랐던 부분인데 알려주셔서 감사합니다!

2019-07-14 16:10 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +        article.setArticleId(latestId);
지적 감사합니다!
로직을 Service 클래스로 분리시키기에는 컨트롤러에 있는 로직이 단순하다 싶어서 더 이상 고치지 않았었는데,
그럼에도 컨트롤러에 로직을 두는 건 좋지 않은 결정이었네요 :D

2019-07-15 06:00 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +            targetArticleIndex = articles.get(i).getArticleId().equals(article.getArticleId()) ? i : targetArticleIndex;
getter의 사용을 줄이기 위해 hasSameArticleId() 메서드를 선언해서 메시지를 보내도록 바꿨습니다.

그런데 여기에서 드는 의문점이,
**Article 클래스 안에** setter 및 getter뿐만 아니라 메시지를 보내는 것 같이 **로직이 포함되어도 괜찮은건가요?**

이를 피하기 위해서 indexOf() 메서드를 사용하려고 하니 equals() 메서드를 articleId를 기준으로 재정의하는 건 맞지 않는 방법이라고 생각이 들어서요...!

2019-07-15 09:02 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public void setArticleId(Long articleId) {
DTO 클래스를 추가하여 수정해보았습니다!

2019-07-15 09:24 UTC, dasistHYOJIN commented on build.gradle
> +	compile('org.springframework.boot:spring-boot-devtools')
compile이 이제는 사용되지 않는다는 건 처음 알았어요.
의존성 옵션을 compile로 하면 그래들 버전에 따라 실패할 수도 있겠네요.
효율적인 빌드를 위해서 api와 implementation을 구분해서 선택하도록 고민해보겠습니다!

2019-07-15 14:38 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public void setArticleId(Long articleId) {
setter는 아직 남겨두셨군요 :crying_cat_face: 
레벨 1 과정을 떠올리며 setter를 제거해보아요!

2019-07-15 14:38 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +                        .ifPresent(i -> articles.remove(i)));
이것도 일종의 2중 들여쓰기 같네요
코드가 복잡해보여요 :eyes:

2019-07-15 14:38 UTC, kang-hyungu commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +            targetArticleIndex = articles.get(i).getArticleId().equals(article.getArticleId()) ? i : targetArticleIndex;
저라면 hasSameArticleId를 만들지 않고 equals를 사용했을거에요.

그리고 메시지를 보내는 것 같이 로직이 포함되어도 괜찮은건가요? <== 이 내용이 정확히 어떤 걸 말하는건지 잘 이해가 안돼서... 조금만 더 상세히 써주시면 추가 답변 남길게요
hasSameArticleId를 추가한 걸 뜻하는거라면.. 비즈니스 로직을 도메인 객체로 격리시키는게 변경을 최소화시킬 수 있는 방법이니 hasSameArticleId를 추가하는 것도 나쁜 방법은 아니라 생각해요

2019-07-15 14:44 UTC, kang-hyungu requested changes
에헴님 작업하신 내용 확인했어요
article, articleRepository에 코멘트랑 답변 남겼어요
그리고 ArticleControllerTest에 인수테스트로 변경한게 아직 반영 안된 것 같아요! 요부분도 같이 봐주세요

2019-07-15 14:45 UTC, kang-hyungu commented on src/test/java/techcourse/myblog/web/ArticleControllerTest.java
> +    private ArticleRepository articleRepository;
articleRepository 제거하는 작업을 해보시고, 시간이 여의치 않으면 패스하고 재반영 요청 주세요!

2019-07-16 14:36 UTC, dasistHYOJIN commented on src/test/java/techcourse/myblog/web/ArticleControllerTest.java
> +    private ArticleRepository articleRepository;
아항 ArticleController 테스트에서는 Repository를 사용하지 않는 게 좋다는 말씀이셨군요..!

게시글_삭제_테스트 메서드에서도 말씀하신대로 고쳐보았습니다!
문제는 테스트 결과를 위해서 **1. 게시글 등록 -> 2. 게시글 삭제 -> 3. 게시글 삭제 확인** 과정을 모두 거치니 메서드의 길이가 너무 길어진 것 같다고 느꼈습니다.
그래서 **1. 게시글 등록 -> 2. 게시글 삭제(~126번줄)** 까지만 테스트를 해도 충분한 것인지 고민을 했는데요
결과적으로는 **게시글이 삭제됐는지 인덱스 페이지에서 확인하는 것까지가 완전한 테스트** 라고 생각해서 이렇게 작성했지만
현구님께서는 어떻게 생각하시는지 의견을 여쭤보고 싶습니다!

2019-07-16 14:41 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +                        .ifPresent(i -> articles.remove(i)));
스트림을 사용하면 좀 더 간결해지지 않을까해서 고쳐보았는데 그렇지 못했네요ㅜ.ㅜ
다시 수정했습니다!

2019-07-16 15:25 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public void setArticleId(Long articleId) {
앗 여러 방법을 찾아보다가 지적해주신 내용을 적용했다고 생각했는데 아니었네요ㅠㅠ
변경 완료했습니다!

2019-07-16 15:32 UTC, dasistHYOJIN commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +            targetArticleIndex = articles.get(i).getArticleId().equals(article.getArticleId()) ? i : targetArticleIndex;
제가 하고자 했던 말은 비즈니스 로직이 Article 객체에 포함되어도 문제가 없는지 확인하고 싶었던 것이었어요!

equals() 메서드를 오버라이드하려고 보니
ArticleRepository 테스트에서 로직 테스트를 할 때 contains()를 사용하는 메서드가 여러 개 있었는데, articleId만을 비교해서 boolean을 리턴하니까 테스트의 정확성이 떨어질 수 밖에 없었습니다.
그래서 indexOf() 메서드를 사용하는 데에 문제가 있다고 생각해서 Article 객체 내에서 데이터를 변경해주는 update() 메서드를 선언해 문제를 해결했습니다!

2019-07-19 00:58 UTC, kang-hyungu commented on src/test/java/techcourse/myblog/web/ArticleControllerTest.java
> +    private ArticleRepository articleRepository;
게시글 삭제 결과가 어떤가에 따라 달라질거에요
게시글 삭제하고 첫 페이지로 리다이렉트 시킨다면 http status 302 체크만 할거에요
삭제하고 인덱스 페이지에 추가적으로 동작하는 기능이 있다면 테스트를 추가해야겠죠. 없으면 302 체크로 충분하다고 생각합니다!

2019-07-19 00:59 UTC, kang-hyungu approved these changes
피드백 늦어서 죄송해요!
제가 알람을 놓쳤었네요 😭 
수정하신 부분 확인하고 질문 주신 내용에 코멘트 남겼어요
코드 구현하느라 고생하셨어요! 머지 처리할게요

2019-07-19 00:59 UTC, merged

2019-07-19 06:24 UTC, pobiconan commented on src/main/java/techcourse/myblog/domain/Article.java
> +
:cake