[게시글 생성/조회/수정/삭제] 김고래 미션 제출합니다.
woowacourse/jwp-blog pull request #35
Opened 2019-07-12 09:22 UTC by ep1stas1s

꼼꼼한 리뷰 항상 감사합니다!!:+1+

2019-07-13 09:05 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
전체적으로 구현 및 테스트 잘해주셨어요 👍 
간단한 피드백 몇가지 추가했습니다.
참고 부탁드리구요, 궁금하신 점 있으시면 DM주세요!

2019-07-13 09:05 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public boolean isSameId(int id) {
메시지 전달 👍

2019-07-13 09:05 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public void setId(int id) {
모델 객체에 꼭 setter가 필요할까요?
없이 작성할 순 없을까요?

2019-07-13 09:05 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +    private static int lastId = 0;
여러 쓰레드가 공유할 수 있는 공유 자원으로 보이네요 :)
아래 블로그 내용 혹은
이펙티브 자바 item 66 변경 가능 공유 데이터에 대한 접근은 동기화하라를 공부해보고 적용해보면 어떨까요?
http://redutan.github.io/2016/03/13/effective-java2-chapter10

아래 글도 확인해보세요 :)
https://stackoverflow.com/questions/9278764/are-primitive-datatypes-thread-safe-in-java

2019-07-13 09:05 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +        return articles.stream()
orElseThrow로 예외를 던지는것이 아니라 Optional을 리턴으로 제공해서,
사용하는 측에서 예외를 던질지, 별도 처리를 할 지 결정하도록 하면 어떨까요?

2019-07-13 09:05 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +        Optional.of(getArticleById(id)).orElseThrow(IllegalArgumentException::new);
getArticleById에서의 피드백의 연장입니다.
애초에 없을경우 예외를 던지기 때문에 불필요한 작업으로 보이네요 :)
getArticleById이 Optional을 리턴으로 제공하고, 여기서 이를 받아서 처리하면 더 깔끔 할 것 같아요!

2019-07-13 09:05 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/MethodType.java
> +public enum MethodType {
이미 스프링에서 RequestMethod 혹은 HttpMethod라는 enum을 제공합니다. :)
@PostMapping, @GetMapping등 내부 코드를 보면 RequestMethod enum을 사용하구요!

2019-07-13 09:05 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +    @Autowired
생성자 주입에선  @Autowired를 생략해도 됩니다 :)

2019-07-13 09:05 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/ArticleController.java
>      private ArticleRepository articleRepository;
꼭 있어야하는 객체임을 표현하기 위해서 final로 선언하면 어떨까요?

2019-07-13 09:05 UTC, phs1116 commented on src/main/resources/application.properties
> +server.port=80
보통 스프링 어플리케이션을 상용에서 사용을 할 때, nginx같은 웹서버와 같이 사용을 합니다.
웹서버에서 요청을 받고 스프링 어플리케이션으로 프록시하는 형태로 많이 사용하는데요,
이 경우 80포트를 사용하면 포트가 겹칠 수가 있어요 :)
참고 하시면 좋을 것 같네요!

2019-07-13 09:05 UTC, phs1116 commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +        webTestClient.post().uri("/articles")
테스트 전체적으로 잘 작성해주셨어요 👍

2019-07-13 14:56 UTC, ep1stas1s commented on src/main/resources/application.properties
> +server.port=80
localhost 뒤에 포트를 안 붙이는게 편해서 그렇게 했었는데 거기까진 생각을 못 했었네요😅 조언 감사합니다!!

2019-07-13 14:57 UTC, ep1stas1s commented on src/main/java/techcourse/myblog/web/ArticleController.java
>      private ArticleRepository articleRepository;
사실... setter injection을 사용했었는데, 다른 자료 참고하여 위 피드백과 함께 적용하였습니다.

2019-07-13 14:57 UTC, ep1stas1s commented on src/main/java/techcourse/myblog/domain/MethodType.java
> +public enum MethodType {
두 군데나 있군요...😅  반영하였습니다ㅎㅎ

2019-07-15 05:14 UTC, ep1stas1s commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public void setId(int id) {
setter를 제거하고 DTO 객체를 생성하였습니다.

2019-07-16 01:01 UTC, pobiconan approved these changes
피드백 반영하느라 수고했어요. 💯

2019-07-16 01:01 UTC, merged