[게시글 생성/조회/수정/삭제] 코나스 미션 제출합니다.
woowacourse/jwp-blog pull request #42
Opened 2019-07-13 11:38 UTC by Conatuseus

안녕하세요 제이슨~ ✋ 
공부한거 늦게라도 sample.md에 적었는데 궁금한 점도 적어놨을 수도 있으니 확인 부탁드릴게요.
풀리퀘 날려놓고 html 중복제거 작업 등 할 예정이에요.
더 좋은 방법이나 더 좋은 코드에 대해 갈구하는게 커서 
리뷰 빡시게 부탁드릴게요 💯 
하루종일 코드 봐주시고 코멘트 한 100개정도만 주세요^^

2019-07-15 02:11 UTC, woowahan-pjs requested changes
IntelliJ IDEA의 코드 자동 정렬 기능(⌥⌘L, Ctrl+Alt+L)을 사용하면 더 깔끔한 코드를 볼 수 있을 거예요.
그 외에도 몇 가지 의견을 남겨 놓았으니 충분히 고민하고 도전해 보세요!
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

2019-07-15 02:11 UTC, woowahan-pjs commented on build.gradle
> +	compile('org.springframework.boot:spring-boot-devtools')
`compile` 대신 `implementation`을 사용하면 어떨까요? 왜일까요?

2019-07-15 02:11 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/HelloWorldController.java
>  @Controller
`@RestController`라는 것이 있어요. `@RestController`는 `@Controller`와 `@ResponseBody`를 합친 것으로, 흔히 Restful 웹 서비스를 구현할 때 사용합니다.

2019-07-15 02:11 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +        article.setId(++articleId);
`AUTO_INCREMENT` 👍

2019-07-15 02:11 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +    public boolean update(Article editedArticle) {
REPOSITORY에는 DB와의 연계성을 제거한다는 이유로 `save`, `modify`, `remove` 등을 사용하고 있어요.

2019-07-15 02:11 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +//        위가 좋은지 아래가 좋은지 궁금해요 json :D
둘 다 다음 미션에서 JPA를 사용하면 사장될 코드지만, 아래의 코드는 `Article`에 새로운 멤버 변수가 추가되면 계속 수정을 해야겠죠?

2019-07-15 02:11 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +    public ArticleController(ArticleRepository articleRepository) {
생성자 주입 👍

2019-07-15 02:11 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +    public String showUpdatedArticle(@PathVariable Long articleId,@ModelAttribute Article article) {
IntelliJ IDEA의 코드 자동 정렬 기능(⌥⌘L, Ctrl+Alt+L)을 사용하면 더 깔끔한 코드를 볼 수 있을 거예요.

2019-07-15 02:11 UTC, woowahan-pjs commented on src/test/java/techcourse/myblog/domain/ArticleRepositoryTest.java
> +//@ExtendWith(SpringExtension.class)
주석 제거!

2019-07-15 02:11 UTC, woowahan-pjs commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +                .expectStatus().is3xxRedirection();
`WebTestClient.ResponseSpec#expectHeader()`를 사용하여 헤더에 대한 테스트도 해보면 어떨까요?

2019-07-15 02:11 UTC, woowahan-pjs commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +                .expectStatus().is3xxRedirection();
중복 제거!

2019-07-15 02:11 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public void setTitle(String title) {
아래의 코드로 개선해 보면 어떨까요? setter 메서드는 도메인의 핵심 개념이나 의도를 코드에서 사라지게 해요.

```suggestion
    public void changeTitle(String title) {
```

2019-07-15 11:14 UTC, Conatuseus commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +    public boolean update(Article editedArticle) {
아하, 감사합니다 👍 
 REPOSITORY에 대해서 좀 더 공부해야겠네요...!

2019-07-15 11:15 UTC, Conatuseus commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +//        위가 좋은지 아래가 좋은지 궁금해요 json :D
아... 거기까지 생각하지 못했는데 그렇겠군요...
역시 고수;;

2019-07-15 11:17 UTC, Conatuseus commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +    public String showUpdatedArticle(@PathVariable Long articleId,@ModelAttribute Article article) {
맥북으로 바꾸면서 자동 정렬하는 습관이 없어진거같아요ㅎㅎ.
다시 신경써서 자주 해야겠네요! 💯

2019-07-15 11:18 UTC, Conatuseus commented on src/test/java/techcourse/myblog/domain/ArticleRepositoryTest.java
> +//@ExtendWith(SpringExtension.class)
👍

2019-07-15 11:22 UTC, Conatuseus commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +                .expectStatus().is3xxRedirection();
수정했습니다.
제이슨이 의도한 바가 맞는지 확인 부탁드려요.

2019-07-15 11:30 UTC, Conatuseus commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public void setTitle(String title) {
핵심 개념이나 의도를 코드에서 사라지게 만든다...음 ...맞는 말씀입니다.
질문)
만약 다른 곳에서 setter 메서드를 사용하고 있는 상황에서, 의도를 위해 setter메소드와 역할은 같지만 이름만 다른 changeTitle 메서드를 만드는건 어떻게 생각하시나요?
ex) 
public void setTitle(String title){
   this.title=title;
}
public void changeTitle(String title){
  this.title=title;
}

2019-07-16 01:01 UTC, Conatuseus commented
REST와 헤더 테스트 공부하고 할려고했는데... 😢

2019-07-16 01:32 UTC, woowahan-pjs approved these changes
스프링의 세계에 온 것을 환영합니다. 👍 
이만 Merge 하겠습니다.

2019-07-16 01:32 UTC, merged