[게시글 생성/조회] 닉 미션 제출합니다.
woowacourse/jwp-blog pull request #5
Opened 2019-07-11 05:39 UTC by wbluke

안녕하세요 :) 잘 부탁드립니다.
ArticleRepository는 나중에 DB를 연결할 것을 고려하여 articleId 가 auto-increment 될 것으로 생각하고 구현해 보았습니다.
ArticleContorllerTest에서는 테스트를 전체실행할 때마다 특정 테스트가 상황에 따라 성공할 때도 있고 실패할 때도 있어서 고민했는데,
테스트 간 순서가 보장되지 않고, async하게 요청이 날아간다는 점을 고려하여,
조회 관련한 메소드들은 아티클을 하나 생성한 후 1번 글을 조회하게 하였고,
삭제 관련한 메소드에서는 아티클을 두개 생성한 후 2번 글을 삭제하게 하였습니다.
감사합니다!

2019-07-11 07:12 UTC, woowahan-pjs requested changes
`AUTO_INCREMENT`를 사용한 것이 인상 깊었습니다. 👍 
고민해 보면 좋을 것 같은 의견을 남겨 놓았으니 충분히 고민하고 도전해 보세요!
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

2019-07-11 07:12 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/Article.java
> +    private int articleId;
`Article`의 식별자니깐 아래의 변수 이름은 어떨까요?

```suggestion
    private int id;
```

2019-07-11 07:12 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
>          return articles;
`articles`에 대한 주솟값을 그대로 외부에 전달하면 어떤 문제가 발생할까요?

2019-07-11 07:12 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/domain/ArticleRepository.java
> +        article.setArticleId(++articleId);
`AUTO_INCREMENT` 👍

2019-07-11 07:12 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/web/ArticleController.java
>      private ArticleRepository articleRepository;
Spring에서 필드 주입을 권장하지 않는 이유가 무엇일까요?

1. 단일 책임의 원칙(Single Responsibility Principle)을 위반할 수 있다.
2. 의존성이 클래스 내부로 숨는다.
3. 인스턴스화가 어려워 테스트하기 어렵다.
4. final을 쓸 수 없어 불변성이 보장되지 않는다.

위의 이유로 스프링 공식 문서에서도 생성자 주입을 권장하고 있습니다.

2019-07-11 07:12 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +    public FilterRegistrationBean httpMethodFilter() {
Bean 등록은 `@Configuration`가 작성된 클래스에서 하는 것이 일반적입니다. 여기에 첨언을 하면 스프링 부트에는 `OrderedHiddenHttpMethodFilter`가 기본으로 등록되어 있어요.

2019-07-11 07:12 UTC, woowahan-pjs commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +    public String fetchArticle(@PathVariable long articleId, Model model) {
`Article#articleId`의 자료형은 `int`입니다. 자료형을 통일하면 어떨까요?

2019-07-11 08:44 UTC, wbluke commented
스프링 DI의 여러가지 방식이 있다는 것을 알 수 있었던 시간이었습니다.
[필드 주입 대신 생성자 주입 사용](https://zorba91.tistory.com/entry/Spring%ED%95%84%EB%93%9C-%EC%A3%BC%EC%9E%85Field-Injection-%EB%8C%80%EC%8B%A0-%EC%83%9D%EC%84%B1%EC%9E%90-%EC%A3%BC%EC%9E%85Constructor-Injection%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%B4%EC%95%BC-%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0) 링크를 참조하여 수정하였습니다.
\+ 어노테이션 공부를 그때그때 착실하게 해야할 것 같습니다....! 
다시한번 리뷰 부탁드립니다. 감사합니다 :)

2019-07-12 06:11 UTC, woowahan-pjs approved these changes
스프링의 세계에 온 것을 환영합니다. 👍 
이만 Merge 하겠습니다.

2019-07-12 06:11 UTC, merged