[게시판 회원 기능] 션 미션 제출 합니다.
woowacourse/jwp-blog pull request #62
Opened 2019-07-20 08:39 UTC by os94

안녕하세요 썸머~!! 처음으로 피드백을 받게된 션이라고 합니다 :)
일단 시간이 지체되면서 PR을 보내는데, 곧 부족한 테스트들 추가 예정입니다!
열심히 해보긴 했는데 괜찮을지 모르겠습니다..! 거침없는 지적 부탁드립니다! 👍

2019-07-20 16:37 UTC, jihan805 requested changes
안녕하세요 션!
전체적으로 잘 구현했어요 👍 
몇가지 피드백 남겼으니 아직 완성하지 않은 코드를 작성하면서 같이 반영해주세요 :)

2019-07-20 16:37 UTC, jihan805 commented on src/main/java/techcourse/myblog/domain/dto/UserRequestDto.java
> +    public static final String NAME_LENGTH_ERROR = "2자이상 10자미만으로 작성해야 합니다.";
전체적으로 굉장히 꼼꼼하게 validation 체크 👍 
다만, 해당 validation은 dto가 아닌 domain 클래스에서 하는 것이 더 적합할 것 같아요.
dto 클래스는 비즈니스 로직등을 가지지 않는 것이 좋아요!

2019-07-20 16:37 UTC, jihan805 commented on src/main/java/techcourse/myblog/domain/service/UserService.java
> +        return userRepository.findUsersByEmail(email).size() != 0;
상수!

2019-07-20 16:37 UTC, jihan805 commented on src/main/java/techcourse/myblog/domain/service/UserService.java
> +    public boolean notExistUserEmail(String email) {
login과 관련된 코드는 loginService 로 분리하면 어떨까요?

2019-07-20 16:37 UTC, jihan805 commented on src/main/java/techcourse/myblog/domain/service/UserService.java
> +        user.setName(name);
비록 name 뿐이지만 setter보다는 updateName (추가로 이메일등도 업데이트 될 수 있지 않을까요?)

2019-07-20 16:37 UTC, jihan805 commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public void setId(long id) {
setter 제거!

2019-07-20 16:37 UTC, jihan805 commented on src/main/java/techcourse/myblog/web/UserController.java
> +        httpSession.setAttribute("user", userService.findUserByEmail(requestEmail));
session의 키로 사용하는 "user"를 class등으로 분리하여 관리하면 어떨까요? (static)
지금과 같이 사용시 변경이 발생하면,
session을 사용하는 모든 곳에서 변경해주어야 하는 불편함이 있거나,
몇군데 수정을 깜빡하게 되는일이 발생할 수 있게 되지 않을까요?

2019-07-20 16:37 UTC, jihan805 commented on src/main/java/techcourse/myblog/domain/dto/UserRequestDto.java
> +package techcourse.myblog.domain.dto;
dto는 도메인 패키지에서 분리하는게 좋을 것 같아요~!

2019-07-24 09:39 UTC, os94 commented on src/main/java/techcourse/myblog/domain/dto/UserRequestDto.java
> +    public static final String NAME_LENGTH_ERROR = "2자이상 10자미만으로 작성해야 합니다.";
이 부분은 많은 크루,코치분들과 이야기 해봤는데 생각보다 사람마다의 의견이 다양했어요.
하지만 저도 생각해보니 개인적으로는 dto에 비즈니스 로직이 들어가지않는것이 좋은것같아요!
이번 미션에는 다른 피드백 반영과 리팩토링 할것들이 많아서 고치지 못했는데, 다음번엔 이런 dto validation 역할의 일부를 도메인클래스로 덜어줘도 괜찮을거같아요! 꽤 오래 생각해볼만한 주제를 던져주셔서 감사합니다 👍 

+ 관련해서 질문이 하나 있는데요, 현재 이렇게 UserRequestDto에서 값의 길이, 패턴 등을 spring validation annotation을 이용해서 검증하고 있어요. 이 부분을 도메인으로 옮기려고 몇번 시도해보긴 했는데, @Entity 클래스에서 이런 검증 어노테이션들이 사용되다보니 DB에 들어갈때가 되서야 오류가 잡아지더라구요. 이렇게 늦게 오류를 잡는건 당연히 안좋을것같아서, validation annotation을 trigger?fork?(적절한 단어가 생각안나네요ㅜ) 직접 돌려서 오류를 잡고싶었는데, 아무리 찾아봐도 방법이 안나오더라구요.. (현재는 검증 어노테이션이 dto에 있어서, 컨트롤러에서 dto와 bindingResult를 파라미터로 설정해 자동으로 오류를 잡아내고있어요)
그래서 고민하다가 이 방법은 포기했고, 지금은 레벨1때 하던것처럼 domain객체의 생성자에서 validate하는 기본적인 방법이 낫겠다 생각하고 있어요. 또는 다른 크루의 피드백에서 봤는데, 지금 String으로 설정한 name 등의 각 필드를 객체로 포장해서, 그곳에서 예외처리를 하고 argument resolver(?)라는 개념으로 연결시키는 방법도 있다고 하더라구요.
이런 제 생각의 흐름에 틀린부분 있거나, 맞는 방향으로 생각하고 있는걸까요? 😃

2019-07-24 09:41 UTC, os94 commented on src/main/java/techcourse/myblog/domain/service/UserService.java
> +        return userRepository.findUsersByEmail(email).size() != 0;
0이 다른 곳에서 사용되거나, 중복확인 메서드에서 0이라는 수치가 변경될 가능성은 없다고 생각되어서 남겨놓았었는데, 리팩토링하다보니 최종적으론 해당 메서드가 사라지게 되었습니다ㅎㅎ 피드백 감사합니다! :)

2019-07-24 09:42 UTC, os94 commented on src/main/java/techcourse/myblog/domain/service/UserService.java
> +    public boolean notExistUserEmail(String email) {
User 서비스와 컨트롤러가 비대해져서 걱정이었는데, 분리하니 훨씬 코드가 좋아진것같아요!

2019-07-24 09:43 UTC, os94 commented on src/main/java/techcourse/myblog/domain/service/UserService.java
> +        user.setName(name);
다른 필드들을 대비해, updateUserInfo()와 같이 바꿨어요~!

2019-07-24 09:44 UTC, os94 commented on src/main/java/techcourse/myblog/domain/Article.java
> +    public void setId(long id) {
전체적으로 setter를 최대한 없애보았습니다!

2019-07-24 09:46 UTC, os94 commented on src/main/java/techcourse/myblog/web/UserController.java
> +        httpSession.setAttribute("user", userService.findUserByEmail(requestEmail));
기존의 형태론 유지보수에 문제가 있는게 맞는거같아요!
키가 모든 컨트롤러에서 사용되어서, 특정한 한곳에 종속시키는게 이상해
상수하나뿐이지만 별도 클래스 하나로(SessionManager.class) 분리했는데, 혹시 어색하게 보이신다면 코멘트 부탁드립니다..ㅎ

2019-07-24 09:47 UTC, os94 commented on src/main/java/techcourse/myblog/domain/dto/UserRequestDto.java
> +package techcourse.myblog.domain.dto;
패키지 구조도 나름 정리해보았습니다!

2019-07-24 09:59 UTC, os94 commented
피드백 반영이 늦어져서 죄송해요 !!!
코드를 이렇게 저렇게 바꿔보고 방향을 좀 헤매서 조금 힘들었습니다ㅠ
다른 크루들과 얘기하며 알게된 interceptor와 exception handler도 한번 적용해보았습니다!
그나마 좀 정리된 production code에 반해,
test code도 계속해서 이런저런 방법을 시도해봤는데 쉽지가 않네요..ㅠㅠ
컨트롤러테스트에서 Repository를 사용하고싶지않았는데 결국 일단은 포기하고 코드를 제출했어요.
로그인상태를 유지해야하는 세션테스트는 강의를 듣고 JSessionId를 다루는법을 알게되었는데,
여전히 테스트 전후가 DB에 영향을 주지않게(테스트 몇번 돌려도 DB에 데이터가 추가되지 않도록)하는게 어렵네요,,,,;; 매번 삽입과삭제를 반복할수도없고 😂 테스트가 많이 부족한데 계속 고민해보겠습니다...ㅜ
감사합니다 ! 👍

2019-07-24 12:57 UTC, jihan805 commented on src/main/java/techcourse/myblog/domain/dto/UserRequestDto.java
> +    public static final String NAME_LENGTH_ERROR = "2자이상 10자미만으로 작성해야 합니다.";
앗... 괜히 너무 많이 고민하게 했네요 ㅜㅜ그래도 고민해줘서 고마워요 ~!
저도 관련해서 조금더 생각해보았는데, 1차적으로 dto에서 확인할 수 있는 부분들은 dto의 어노테이션을 사용하도록 하고, 이후에 추가로 도메인 로직에서 validation method를 작성하거나 혹은 @Column의 속성을 이용해 검증하는 것이 가장 좋을 것 같아요!

이 부분에 대해서 제가 도메인에도 필요할 것 같다고 생각했던 가장 큰 이유는 혹시 validation이 있는 dto를 거치지 않고 다른 곳에서 해당 클래스를 사용할 경우 아무런 검증을 할 수 없지 않을까?때문이었어요!

말씀하신대로 사람마다 의견이 당연히 다를 수 있고, 다른게 당연하다고 생각해요. 방법이 정해진 것이 아니고, 매번 코드를 작성하다보면 다른 방법들이 떠오를 수 있으니 앞으로 고민해보고 좋은 의견이 생기면(?) 공유할게요!!

이렇게 필드에 대한 검증을 꼼꼼하게 하기 위해 고민하는 것 👍
다만 너무 과하면(복잡하거나 등) 좋지 않을 것 같아요!!

2019-07-24 13:28 UTC, jihan805 approved these changes
안녕하세요 션!
피드백 반영 잘 해주셧어요 :)
머지할게요 👍 그동안 고생 많았어요!

2019-07-24 13:28 UTC, jihan805 commented on src/test/java/techcourse/myblog/web/controller/UserControllerTests.java
> +public class UserControllerTests {
이야기한 것처럼 테스트를 조금 더 추가해도 좋을 것 같아요!
예를들면, 비밀번호가 8자리 이하인 경우 -> 실패 
제대로 된 비밀번호인 경우 status ok와 같이요. 

또한 말씀하신 것처럼 controller에서 repository를 조회하면 절대 안되지는 않겠지만 그보다는 요청에 대해 기대한 응답을 주는지 까지만 테스트 해도 충분하다고 생각합니다.

controller를 통해 요청을 받지만, 대부분 service/domain 의 로직으로 처리되고 있습니다.
요청에 대해 실제 처리가 제대로 되는지(값이 업데이트되는지)에 대해서는 service/domain등에서 테스트하는 것도 대안이 될 수 있을 것 같아요!

추가로 @DataJpaTest 에 대해 읽어보면 어떨까요?
https://jojoldu.tistory.com/33

2019-07-24 13:28 UTC, merged