[게시판 회원 기능] 이바 미션 제출합니다.
woowacourse/jwp-blog pull request #66
Opened 2019-07-20 11:57 UTC by seonghun127

안녕하세요 화투님 리뷰이 이바입니다.

이번 미션을 진행하면서 Http 통신, Session에 대한 이해가 많이 부족하여 많이 애먹었습니다.

로그인 유무에 따라 다른 페이지로 이동하는 분기 로직을 구현하는데 중복이 많이 발생하여 코드를 구현하면서도
상당히 찝찝했습니다. interceptor를 사용하면 이러한 문제를 해결할 수 있다고 들었지만 미션 요구사항을 구현하는데
시간을 대부분 할애하여 interceptor에 공부조차 못했습니다 ㅠ

테스트 코드 작성 또한 부족한 실력으로 쉽지 않았습니다. session을 요구하는 api에 대한 테스트 코드 구현 시
session을 생성하고 설정하는데 정확한 방법으로 했다고 생각되어지지 않습니다. 꾸역꾸역 구현한 느낌이 가득하네요;

PR을 먼저 보내고 interceptor를 공부하면서 적용시켜보려고합니다.

부족한 부분을 신랄하게 지적해주시면 감사하겠습니다.

2019-07-21 07:44 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
전체적으로 고민 많이하시며 작성하신게 보여요 👍 
컨트롤러 어드바이스 활용 👍 
몇가지 피드백 좀 추가했는데요,
한번 확인 부탁드리고 궁금하신 점 있으시면 DM주세요!!

2019-07-21 07:44 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +        return articleRepository.save(updatedArticle).getId();
Transactional 어노테이션과 JPA 영속성 컨텍스트에 대해서 공부해보고 적용해보면 어떨까요?
JPA에서는 한 트랜잭션 내에 있을 경우 엔티티에 대한 영속성이 유지가 되기 때문에 굳이 다시 save를 하지 않아도 변경이 반영이 되거든요 :)

https://medium.com/@SlackBeck/jpa-%EB%B3%80%EA%B2%BD-%EA%B0%90%EC%A7%80%EC%99%80-%EC%8A%A4%ED%94%84%EB%A7%81-%EB%8D%B0%EC%9D%B4%ED%84%B0-2e01ad594b82

2019-07-21 07:44 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/Article.java
>      private Article(long id, String title, String coverUrl, String contents) {
Builder를 사용하면서 private 생성자를 또 사용하는 이유가 있을까요?

2019-07-21 07:44 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +    private boolean checkSession(HttpServletRequest request) {
네 말씀하신대로 해당 부분은 인터셉터로 수정하는 공부를 해보시면 좋을 것 같네요. :)

2019-07-21 07:44 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/LoginController.java
> +        HttpSession session = request.getSession(false);
로그인 여부 파악을 세션이 존재하는지로만 판단하면,
로그인 외에 대한 다른 기능을 세션으로 활용할 경우 문제가 생길수도 있지 않을까요?

2019-07-21 07:44 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/UserController.java
> +        if (bindingResult.hasErrors()) {
JSR-303 활용 👍

2019-07-21 07:44 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/UserController.java
> +package techcourse.myblog.web;
패키지가 다 web에 들어있는데, 도메인 별로 패키지를 분리해보면 어떨까요?

2019-07-21 07:44 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/UserController.java
> +        HttpSession session = request.getSession(false);
ArticleController와 달리 UserController, LoginController는 세션 체크하는 부분이 다 중복으로 존재하네요 :)

2019-07-21 07:44 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/UserController.java
> +        UserDto.Response sessionUser = (UserDto.Response) session.getAttribute("user");
세션에서 직접 꺼내쓰는 방법도 있지만,
Argument Resolver를 공부해서 인자로 전달받도록 수정해보면 어떨까요?

2019-07-21 07:44 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/UserController.java
> +        session.invalidate();
로그아웃 기능이 중복으로 이루어지는 것 같은데요, 로그아웃으로 리다이렉트하거나 별도 서비스를 분리해보면 어떨까요?

2019-07-21 07:44 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/UserExceptionAdvice.java
> +public class UserExceptionAdvice {
컨트롤러 어드바이스 활용 👍

2019-07-21 07:44 UTC, phs1116 commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +        cookie = webTestClient.post().uri("/login")
유저 생성, 로그인 부분이 현재 대부분의 테스트 및 앞으로 추가될 테스트에서도 계속 중복으로 사용될 것으로 보이네요.
이를 별도 유틸클래스나 추상클래스로 분리하여 공통으로 사용할 수 있도록 해보면 어떨까요?

2019-07-21 07:44 UTC, phs1116 commented on src/test/java/techcourse/myblog/service/ArticleServiceTest.java
> +class ArticleServiceTest {
ArticleServiceTest, UserServiceTest가 현WO 외부 자원에 의존하는 형태인데요(Repository 등)
그렇기 때문에 articleId등 id값을 공유하며 증가시키도록 하신 것 같습니다.

굳이 어플리케이션 컨텍스트까지 사용하지 않고, Mockito등을 사용하여 Repository를 Mock으로 격리시켜 서비스 그 자체만 테스트를 해보도록 하면 어떨까요?

2019-07-21 07:44 UTC, phs1116 commented on src/main/java/techcourse/myblog/dto/UserDto.java
> +    public static class Create {
DTO 클래스들의 이름이 명확하지가 않습니다. 일반적으로 클래스 명은 명사형으로 작성하는게 컨벤션이에요!

2019-07-21 07:44 UTC, phs1116 commented on src/main/java/techcourse/myblog/dto/UserDto.java
> +public class UserDto {
해당 클래스는 단일 책임 원칙에 위배됩니다. 클래스를 수정할 때에는 오직 하나의 이유에 의해서만 수정이 되야하는데요,
너무 성격이 다른 DTO들이 하나의 클래스로 묶여있는 것 같습니다.
클래스가 아닌 패키지 단위로 관리해보면 어떨까요?

2019-07-21 07:44 UTC, phs1116 commented on src/main/java/techcourse/myblog/dto/UserDto.java
> +        private String email;
Login에서는 validate가 없네요 :)

2019-07-21 07:44 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/UserService.java
> +public class UserService {
서비스에서 트랜잭션 관리도 같이 해주시면 좋을 것 같습니다. :)

2019-07-21 07:44 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/User.java
> +    private String email;
엔티티에서는 email, password 등에 대한 검증이 보이네요.
현재 User는 꼭 UserDTO에 의해서가 아니더라도 생성이 가능합니다. 
(특히 도메인이 점점 더 커지면 어디서 생성될지 알 수 없습니다.)
사이드이펙트 방지를 위해 여기서도 밸리데이션을 추가하는게 좋을 것 같네요. :)

2019-07-22 07:00 UTC, seonghun127 commented on src/main/java/techcourse/myblog/domain/Article.java
>      private Article(long id, String title, String coverUrl, String contents) {
위와같은 생성자가 없으면 Aritcle 클래스 내부 Builder 중첩 클래스의 `build()` 메서드에서 Article의 기본 생성자밖에 호출하지 못해 객체 생성이 제대로 되지 않는 오류가 일어나더군요.
우선 Article 도메인 클래스를 Bean으로 등록하기 위한 기본 생성자와 빌더 패턴 적용을 위한 내부 필드 값 주입 생성자를 같이 만들어줬습니다.
혹시 제가 잘못한 이해한 부분이 있나요?
우선은 생성자에 `@Builder` 어노테이션을 적용시켜줬습니다. 생성자에 어노테이션을 달아서 생성자에 선언된 파리미터에 대해서만 빌더 패턴을 적용하기 위함입니다.

2019-07-22 07:01 UTC, seonghun127 commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +    private boolean checkSession(HttpServletRequest request) {
알겠습니다! 👍 
수정해나가겠습니다!

2019-07-22 07:01 UTC, seonghun127 commented on src/main/java/techcourse/myblog/web/UserController.java
> +        if (bindingResult.hasErrors()) {
감사합니다 ㅎㅎㅎ 👍

2019-07-22 07:03 UTC, seonghun127 commented on src/main/java/techcourse/myblog/web/UserExceptionAdvice.java
> +public class UserExceptionAdvice {
감사합니다! 👍

2019-07-22 07:08 UTC, seonghun127 commented on src/main/java/techcourse/myblog/web/UserController.java
> +        session.invalidate();
로그아웃으로 리다이렉트하는 방식으로 변경해줬습니다!

2019-07-22 07:21 UTC, seonghun127 commented on src/main/java/techcourse/myblog/web/UserController.java
> +package techcourse.myblog.web;
수정했습니다! 👍

2019-07-23 05:24 UTC, seonghun127 commented on src/main/java/techcourse/myblog/web/LoginController.java
> +        HttpSession session = request.getSession(false);
Interceptor를 적용하면서 `session.getAttribute("user")`로 로그인 여부를 확인하는 방식으로 수정했습니다!

2019-07-23 05:25 UTC, seonghun127 commented on src/main/java/techcourse/myblog/web/UserController.java
> +        HttpSession session = request.getSession(false);
Interceptor로 해결했습니다 👍

2019-07-23 05:28 UTC, seonghun127 commented on src/main/java/techcourse/myblog/web/UserController.java
> +        UserDto.Response sessionUser = (UserDto.Response) session.getAttribute("user");
수정했습니다!

적용해보면서 궁금한게 생겼습니다.
Argument Resolver를 사용하면서 새롭게 생성한 `UserSession` 클래스가 있습니다.
이는 session에 저장된 로그인 정보를 담는 클래스인데 해당 클래스를 어느 패키지로 분류해야할지 
정확히 모르겠습니다.

현재 패키지는 도메인을 기준으로 분류했는데 `UserSession`을 도메인으로 봐야하나요?

2019-07-23 05:47 UTC, seonghun127 commented on src/main/java/techcourse/myblog/dto/UserDto.java
> +    public static class Create {
명사 형태로 수정했습니다!

2019-07-23 06:03 UTC, seonghun127 commented on src/main/java/techcourse/myblog/dto/UserDto.java
> +public class UserDto {
중첩 클래스를 사용하면서 단일 책임 원칙까지 생각하지 못했네요.

저는 원래 `User`와 관련된 dto를 만들면서 
```
UserCreateDto
UserUpdateDto
UserResponseDto
```
위와 같이 만들었었는데요. 간단한 프로젝트에선 상관없겠지만 기능들이 복잡해지면 그에따라 dto 또한 많이 늘어날거란 생각이 들었습니다. 이를 효과적으로 관리할 수 있는 방법이 없을까 하다가 중첩 클래스 개념을 적용시켜보았습니다.

물론 `UserDto`가 여러가지 이유로 수정될 수 있겠지만 수정되는 내용이 결국 기능에 변경에 따른 것이라고 생각합니다. 즉, update와 관련되서 요구되는 정보가 바뀐다면 `UserDto.Updation` 중첩 클래스에만 변경이 일어날 것입니다. `UserDto` 클래스 내부에 중첩 클래스들은 각각 static이면서 다른 중첩 클래스들에 영향을 주지 않기 때문에 `UserUpdateDto` 클래스를 수정하는 것과 똑같다고 생각합니다.

그리고 User 도메인에 대한 기능별 dto를 `UserDto` 하나로 묶었다는 점에서 여러 dto를 패키지로 묶은 것과 비슷하게 볼 수 있지 않을까요?

2019-07-23 06:26 UTC, seonghun127 commented on src/main/java/techcourse/myblog/dto/UserDto.java
> +        private String email;
추가했습니다!! 👍

2019-07-23 15:14 UTC, seonghun127 commented on src/main/java/techcourse/myblog/domain/User.java
> +    private String email;
밸리데이션 추가했습니다!

2019-07-23 15:41 UTC, seonghun127 commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +        return articleRepository.save(updatedArticle).getId();
수정했습니다!
좋은 자료(링크) 감사합니다 👍

2019-07-23 15:41 UTC, seonghun127 commented on src/main/java/techcourse/myblog/service/UserService.java
> +public class UserService {
추가했습니다 👍

2019-07-24 09:42 UTC, seonghun127 commented on src/test/java/techcourse/myblog/service/ArticleServiceTest.java
> +class ArticleServiceTest {
Mockito를 공부하고 적용해보려 했는데 시간적으로 여유가 되질 않아 다음에 적용해보려고합니다 ㅠ
위 피드백을 제외한 나머지 반영한 부분에 대해서 피드백 해주시면 감사하겠습니다!

2019-07-24 09:52 UTC, seonghun127 commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +        cookie = webTestClient.post().uri("/login")
`UserUtilForTest` 클래스로 따로 추출했습니다!

2019-07-24 09:59 UTC, seonghun127 commented
안녕하세요. 화투님!
주신 피드백 반영하기까지 오랜 시간이 걸렸네요;

다양한 피드백을 남겨주셔서 감사했습니다. 그래서 저도 최대한 반영하려고 노력했습니다.

이번에도 Mockito를 비롯한 더 나은 테스트 코드를 위한 여러 라이브러리를 공부하게 되었는데
정확히 알고 쓰고싶은 욕심에 이론적으로 찾아 공부하다보니 시간이 너무 많이 소요되는 것 같아 
끝내 반영하지 못하고 다시 리뷰 요청 보냅니다. 좋은 테스트 코드 작성하기가 정말 어렵더라구요 ㅎㅎ;

아 물론, 이번에 처음 해보는 Interceptor와 Argument Resolver에 대해서도 
완전히 이해하고 적용시킨건 아닙니다.
블로그 보면서 적용해보고 간략하게 공부한게 전부여서 하면서도 살짝 찝찝한(?) 느낌입니다.
앞으로 계속 공부해야겠습니다.

이번에도 부족한 부분을 신랄하게 지적해주시면 감사하겠습니다! 👍

2019-07-24 15:48 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
전체적인 피드백 반영 👍 
간단한 피드백 몇가지 추가했는데요.
마지막으로 한번만 더 확인 부탁드릴게요 :)
궁금하신 점 있으시면 DM주세요!

2019-07-24 15:48 UTC, phs1116 commented on src/main/java/techcourse/myblog/dto/UserDto.java
> +public class UserDto {
네. 근데 해당 역할은 패키지가 할 일이지 클래스가 할 일은 아니라고 생각됩니다 :)
내부 클래스의 용도는 외부 클래스의 기능적인 확장을 위해서 사용되지
별도의 자료구조로 외부에서 사용하기에는 적합하지 않아보여요 :)

2019-07-24 15:48 UTC, phs1116 commented on src/main/java/techcourse/myblog/user/domain/User.java
> +    private String validatePassword(final String password) {
name, password 와 email validate를 User에서 직접하는것이 아니라
별도 VO를 만들어서 해당 클래스 내부에서 하도록 수정해보면 어떨까요?
AttributeConverter를 공부해봐도 좋을 것 같습니다. :)

2019-07-24 15:48 UTC, phs1116 commented on src/test/java/techcourse/myblog/user/controller/UserControllerTests.java
> +                .expectStatus().isFound();
Found만 체크하고 끝내는 테스트가 많은데, 예외 상황에 따라서 redirect도 발생 할 수 있을것 같은데요.
Location 체크 및 실제로 변경이 반영했는지까지 검증해보면 어떨까요?

2019-07-25 07:15 UTC, seonghun127 commented on src/main/java/techcourse/myblog/user/domain/User.java
> +    private String validatePassword(final String password) {
AttributeConverter를 적용했습니다! 👍 
VO에 대한 개념을 공부할 수 있었습니다.

2019-07-25 08:07 UTC, seonghun127 commented on src/test/java/techcourse/myblog/user/controller/UserControllerTests.java
> +                .expectStatus().isFound();
반영했습니다!! 👍

2019-07-25 08:24 UTC, seonghun127 commented on src/main/java/techcourse/myblog/dto/UserDto.java
> +public class UserDto {
이펙티브 자바 아이템 24에서 보면
```
정적 멤버 클래스는 흔히 바깥 클래스와 함께 쓰일 때만 유용한 public 도우미 클래스로 쓰인다. 
계산기가 지원하는 연산 종류를 정의하는 열거 타입을 예로 생각해보자. 
Operation 열거타입은 Calculator 클래스의 public 정적 멤버 클래스가 되어야 한다. 
그러면 Calculator의 클라이언트에서 Calculator.Operation.PLUS 나 
Calculator.Operation.MINUS 같은 형태로 원하는 연산을 참조할 수 있다.
```
라는 내용이 있습니다.

저는 위 이펙티브 자바의 내용을 보고 상황에 맞게 dto를 따로 분리하기 보단 `User` 도메인에 관한 dto라면 `UserDto` 클래스내부에 도우미 클래스의 역할로 사용할 수 있는 정적 멤버 클래스로 만들어 봤는데요. 그리고 `User` 도메인에 대한 dto가 뭐가 있는지 찾아보기 보단 `UserDto` 다음에 . 을 찍으면 사용할 수 있는 dto를 바로 찾아 볼 수 있으니 여러 이점을 가질 수 있을 거란 생각을 했습니다.

그렇다면 화투님께서 말씀해주시는 부분이랑 같이 생각했을 때 현재 제가 구현한 dto의 경우는
중첩 클래스들은 접근자 메서드를 제외하면 필드(자료구조) 외에 별다른 로직이 없기 때문에 public 도우미 클래스의 역할도 못하고 있다고 말씀이신건가요?

2019-07-25 08:29 UTC, seonghun127 commented
화투님 안녕하세요. 리뷰이 이바입니다.

이번에도 피드백을 최대한 반영하려고 노력했습니다.
특히 Attribute Converter를 적용해보는 것이 매우 흥미로웠습니다.

우테코 1단계에서 객체 지향적으로 프로그래밍하기 위해 값을 포장하는 클래스를 수없이 만들어보았는데
이번 2단계부터 스프링을 배우면서 스프링을 공부하느라 객체 지향적으로 프로그래밍해야겠다는 생각을 
많이 못했었습니다. 그렇지만 Attribute Converter를 적용해면서 잠시 잊었던 1단계의 내용을 다시 
되새길 수 있어서 좋았습니다.

피드백에 대해 정말 감사하고 이번에도 개선해야할 사항이 있다면 많이 지적해주세요. 👍

2019-07-25 16:26 UTC, phs1116 approved these changes
안녕하세요. 리뷰어 화투입니다.
피드백 반영 👍 
이번 단계 머지할게요.
간단한 피드백 하나 남겼는데 다음 단계 진행하시면서 참고 부탁드리겠습니다.
개발 하시느라 수고 많으셨습니다!

2019-07-25 16:26 UTC, phs1116 commented on src/test/java/techcourse/myblog/interceptor/LoginInterceptorTest.java
> +                .contentType(MediaType.APPLICATION_FORM_URLENCODED)
작성하신 유틸을 활용 할 수 있지 않았을까요?

2019-07-25 16:26 UTC, merged