[게시판 회원 기능] 비모 미션 제출 합니다.
woowacourse/jwp-blog pull request #69
Opened 2019-07-20 12:52 UTC by SEOKHYOENCHOI

잘 부탁드립니다!

2019-07-21 15:12 UTC, ssosso requested changes
안녕하세요, 비모~ 쏘쏘입니다:) (저와의 코드리뷰에서는 '님' 어미를 사용하지 않으셔도 되요~)
코드가 깔끔합니다:) 몇 가지 피드백 남기니 확인 부탁드립니다~

2019-07-21 15:12 UTC, ssosso commented on src/main/java/techcourse/myblog/application/dto/LoginDto.java
> +    @Pattern(regexp = "^([a-zA-Z0-9!@#$%^&*]{8,})$", message = "8자리 이상의 글자, 숫자, 특수문자를 입력해야합니다.")
Pattern, NotBlank에 대한 테스트는 어떻게 할 수 있을까요~?

2019-07-21 15:12 UTC, ssosso commented on src/main/java/techcourse/myblog/application/service/ArticleService.java
> +        return articleRepository.save(new Article.ArticleBuilder()
ArticleDto에 Article로 변환하는 메서드가 있으면 어떨까요~?

2019-07-21 15:12 UTC, ssosso commented on src/main/java/techcourse/myblog/application/service/UserService.java
> +        User user = new User(userDto.getEmail(), userDto.getName(), userDto.getPassword());
UserDto에 User로 변환하는 메서드가 있는건 어떨까요~?

2019-07-21 15:12 UTC, ssosso commented on src/main/java/techcourse/myblog/presentation/controller/UserController.java
> +        if (user.getEmail().equals(email)) {
email이 같은지 물어보는 메서드를 작성하면 어떨까요~?

2019-07-21 15:12 UTC, ssosso commented on src/test/java/techcourse/myblog/presentation/controller/ArticleControllerTests.java
> +                .exchange()
request를 보내는 부분을 별도 메서드로 구현하면 어떨까요~?

2019-07-21 15:12 UTC, ssosso commented on src/test/java/techcourse/myblog/presentation/controller/UserControllerTests.java
> +    }
UserController에 @ExceptionHandler(DuplicatedIdException.class)로 구현한 로직들을 테스트할 수 있으려면 어떻게 해야할까요~?

2019-07-24 12:00 UTC, SEOKHYOENCHOI commented on src/main/java/techcourse/myblog/application/service/UserService.java
> +        User user = new User(userDto.getEmail(), userDto.getName(), userDto.getPassword());
Converter Pattern을 활용해서 Dto <-> Domain Entity 간 변환 클래스를 만들었습니다!

2019-07-24 12:01 UTC, SEOKHYOENCHOI commented on src/main/java/techcourse/myblog/presentation/controller/UserController.java
> +        if (user.getEmail().equals(email)) {
User Entity에 Email이 같은지 물어보는 메소드를 만들었습니다!

2019-07-24 12:08 UTC, SEOKHYOENCHOI commented on src/main/java/techcourse/myblog/application/dto/LoginDto.java
> +    @Pattern(regexp = "^([a-zA-Z0-9!@#$%^&*]{8,})$", message = "8자리 이상의 글자, 숫자, 특수문자를 입력해야합니다.")
Domain Entity에서  javax.validation.Validator를 이용해 테스트했습니다!

2019-07-24 13:34 UTC, SEOKHYOENCHOI commented on src/test/java/techcourse/myblog/presentation/controller/UserControllerTests.java
> +    }
ControllerAdvice 적용 후 테스트 코드에서 ArticleController를 예로

@WebMvcTest(ArticleController.class)
public class ArticleControllerTests {
    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private ArticleService articleService;

    @Test
    void index() throws Exception {
        given(articleService.findById(1L)).willThrow(NotExistArticleIdException.class);
        mockMvc.perform(get("/articles/1"))
                .andExpect(status().isBadRequest());
    }
}

이런식으로 구현하면 검증가능한 것을 확인했습니다.

2019-07-24 13:40 UTC, SEOKHYOENCHOI commented
Converter Pattern, Controller Advice 등을 적용해봤습니다.
이번 주 페어가 3명인데 다른 페어들의 피드백도 모두 반영하느라 시간이 오래걸렸어요ㅠㅠ

추가로 UserService와 MainController에 Mockito를 적용해봤어요.
UserController와 ArticleController에도 적용하고 있는데 처음이라 좀 오래 걸릴 것 같네요ㅠㅠ
Mockito 적용 후 ExceptionHandlingTest와 Test 코드 중복제거도 빠른 시일 내에 구현하겠습니다

2019-07-25 13:51 UTC, ssosso approved these changes
페어들의 피드백까지 반영하기에 힘들겠네요, 머지 조건으로 테스트코드 중복 제거와 세션에 대한 테스트코드 여부가 있는데 오늘로써 머지기간이 끝나기에 이만 마무리 하려 해요:) 다음 단계에 꼭 구현할 수 있으셨으면 좋겠습니다. 혹시 질문 있으시면 연락주세요:) 고생하셨습니다!

2019-07-25 13:51 UTC, merged