[게시판 회원 기능] 제이엠 미션 제출합니다.
woowacourse/jwp-blog pull request #70
Opened 2019-07-20 13:11 UTC by kimjungmin-developer

2019-07-21 08:35 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
전체적으로 테스트도 꼼꼼하게 잘 작성하신 것 같아요 👍 
몇가지 피드백 추가했는데요, 확인해보시고 궁금하신 점 있으시면 연락주세요!

2019-07-21 08:35 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/User.java
> +    private String email;
Email 주소같이 사용자가 설정할수 있는 문자열을 키로 가져갈 경우 데이터 삽입시에 성능이 상당히 저하될 수 있습니다.
auto increment로 시퀀스를 키로 가져가도록 수정하면 좋을 것 같네요 :)

2019-07-21 08:35 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/User.java
> +    private String password;
email과 password에 대한 검증이 DTO외에는 없는 것 같네요 :)
해당 검증을 엔티티에 추가해보면 어떨까요?

기왕 하는김에 별도 VO로 분리하고 AttributeConverter를 공부해서 적용해봐도 좋을 것 같네요!

2019-07-21 08:35 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/Article.java
>  public class Article {
Article같은 Entity에선 일반적으로 ID를 기반으로 동일성을 검사합니다.
현재 해당 엔티티에서  equals를 보면 전체 필드를 가지고 비교를 하고있네요. :) 
수정해보면 어떨까요?

2019-07-21 08:35 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/User.java
> +public class User {
해당 엔티티에선 equals,hascode가 구현되어있지 않네요. :)

2019-07-21 08:35 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/ArticleAssembler.java
> +    public ArticleDto convertToDto(final Article article) {
상태가 전혀 없는 클래스라 static 메서드로 가져가도 될 것 같네요 :)

2019-07-21 08:35 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +            articleRepository.save(articleToUpdate);
Transactional 어노테이션과 JPA 영속성 컨텍스트에 대해서 공부해보고 적용해보면 어떨까요?
JPA에서는 한 트랜잭션 내에 있을 경우 엔티티에 대한 영속성이 유지가 되기 때문에 굳이 다시 save를 하지 않아도 변경이 반영이 되거든요 :)

https://medium.com/@SlackBeck/jpa-%EB%B3%80%EA%B2%BD-%EA%B0%90%EC%A7%80%EC%99%80-%EC%8A%A4%ED%94%84%EB%A7%81-%EB%8D%B0%EC%9D%B4%ED%84%B0-2e01ad594b82

2019-07-21 08:35 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +public class ArticleService {
트랜잭션에 대해서 공부하고 서비스 전체적으로 트랜잭션을 적용하면 좋을 것 같습니다. :)

2019-07-21 08:35 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +        Optional<Article> article = articleRepository.findById(id);
기왕 옵셔널을 사용하시니 체이닝을 통해서 풀어보면 어떨까요?
map, orElseThrow를 사용할 수 있을것 같네요 :)
아니면 다른 서비스에서도 해당 메서드를 사용할 수 있으니 map만하고 옵셔널을 넣어도 좋을 것 같아요 :)

2019-07-21 08:35 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/UserService.java
> +    public UserService(UserRepository userRepository) {
다른 서비스에서는 @Autowired 없이 빈에는 final로 선언되어있던데 다른 서비스와 컨벤션 맞춰주시면 좋을 것 같아요.

2019-07-21 08:35 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/UserService.java
> +        if (userOpt.isPresent()) {
마찬가지로 Optional 체이닝과 트랜잭션을 활용해보시면 좋을 것 같습니다. :)

2019-07-21 08:35 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/UserService.java
> +    public void checkPasswordAndRepassword(UserRequestDto userRequestDto) {
빈으로 같이 생성되어 호출 될 필요가 없는 메서드인 것 같네요.
해당 검증은 서비스가 아닌 Password라는 별도 도메인 객체를 만들고 거기서 검증하도록 해보면 어떨까요?

2019-07-21 08:35 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/UserController.java
> +        if (!Objects.isNull(session.getAttribute("user"))) {
Interceptor를 공부하고 로그인 체크에 대한 부분을 그에 위임해보면 어떨까요?
또한 현재 전체 기능에 대해 로그인 여부와 상관 없이 동작하는데 
인터셉터를 활용하여 권한 또찬 체크하도록 수정해보면 좋을 것 같네요. :)

2019-07-21 08:35 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/UserController.java
> +            userService.checkPasswordAndRepassword(userRequestDto);
processLogin와 마찬가지로, 예외를 그냥 발생시키고 ContorllerAdvice, ExceptionHandler를 공부해서 이를 활용해보면 어떨까요?

2019-07-21 08:35 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/UserController.java
> +            userService.checkEmail(userRequestDto);
현재 checkEmail, checkPasswordAndRepassword등은 하나의 비즈니스 로직입니다.
컨트롤러가 아닌 서비스 레이어에서 처리하도록 해보면 어떨까요?

2019-07-21 08:35 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/UserController.java
> +        UserResponseDto user = (UserResponseDto) session.getAttribute("user");
Argument Resolver 공부후 활용! ㅎ

2019-07-21 08:35 UTC, phs1116 commented on src/test/java/techcourse/myblog/service/ArticleServiceTest.java
> +    private ArticleService service;
현재 해당 Service는 외부 의존을 가지고있는데요. (Repository 등)
따라서 테스트가 쉽지 않을 수 있습니다.
굳이 어플리케이션 컨텍스트까지 사용하지 말고 해당 서비스의 로직만 확인하도록 유닛테스트로 작성해보면 어떨까요?
Mockito등을 공부하여 적용해봐도 좋을 것 같네요. :)

2019-07-21 08:35 UTC, phs1116 commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +                    webTestClient.get()
consumeWith후 체이닝이 너무 길어 가독성이 좋지 않습니다.
expectBody().returnResult();로 체이닝을 끊어가며 작성해보면 어떨까요?

2019-07-21 08:35 UTC, phs1116 commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
>                  .consumeWith(response -> {
굳이 consumeWith내에서 작성할 이유는 없을 것 같아요 :)
expectBody().returnResult()를 사용하여
실행/검증을 분리하면 더욱 더 가독성이 좋지 않을까요?

2019-07-21 08:35 UTC, phs1116 commented on src/test/java/techcourse/myblog/web/UserControllerTests.java
> +        webTestClient.post().uri("/users")
로그인 테스트 부분에 대한 중복이 상당히 많은 것 같습니다.
공통으로 사용하도록 분리해보면 어떨까요?

또한 앞으로 로그인부가 아닌 다른 기능들에도 로그인을 추가해야할텐데
이를 대비하여 다른 인수테스트에서도 활용하도록 분리해보면 좋을 것 같네요 :)

2019-07-23 10:23 UTC, kimjungmin-developer commented on src/main/java/techcourse/myblog/domain/User.java
> +    private String email;
수정했습니다!

2019-07-30 01:03 UTC, pobiconan commented
@kimjungmin-developer 
이 pr은 merge가 되지 않고 있는데요. 
그냥 다음 단계로 진행하는 건가요?

2019-07-30 08:28 UTC, merged