[게시판 회원 기능] 효오 미션 제출합니다.
woowacourse/jwp-blog pull request #90
Opened 2019-07-21 10:56 UTC by hyojaekim

안녕하세요. 2주차 과제를 제출하게 된 효오라고 합니다.

페어를 진행하면서 새로운 것도 많이 배워서 복습하는 겸 혼자 다시 만들어 봤는데
많이 부족하다는 것을 느끼네요....ㅠ

많은 지적을 해주시면 감사하겠습니다!

2019-07-22 01:01 UTC, ssosso requested changes
안녕하세요, 효오~ 쏘쏘입니다:) (저와의 코드리뷰에서는 '님' 어미를 사용하지 않으셔도 되요~)
페어 코딩 이후로 다시 코딩해보는 방법을 취해서 그런지 코드가 깔끔하네요:) 정말 고생하셨어요~
몇 가지 피드백 남기니 확인 부탁드립니다!

2019-07-22 01:01 UTC, ssosso commented on src/main/java/techcourse/myblog/domain/Article.java
> +        return article;
ArticleDto가 Article을 받아서 ArticleDto를 만들도록 하면 어떨까요~?
도메인 객체는 Dto의 존재는 모르면 어떨까요~?

2019-07-22 01:01 UTC, ssosso commented on src/main/java/techcourse/myblog/domain/Article.java
>      public void updateArticle(ArticleDto articleDto) {
Article을 파라미터로 받으면 어떨까요~?

2019-07-22 01:01 UTC, ssosso commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +    public void update(Long articleId, ArticleDto articleDto) {
반환값이 있으면 어떨까요~?

2019-07-22 01:01 UTC, ssosso commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +        articleRepository.save(findArticle);
@transactional 어노테이션을 붙이면 save하지 않아도 update하는 즉시 새로운 필드값이 반영됩니다.

2019-07-22 01:01 UTC, ssosso commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +    public void setActionOfArticle(Model model, String actionRoute, String formMethod) {
반환값이 있으면 어떨까요~?

2019-07-22 01:01 UTC, ssosso commented on src/main/java/techcourse/myblog/service/LoginService.java
> +        if (!userPassword.equals(loginDto.getPassword())) {
User에게 패스워드 같은지 물어보면 어떨까요~? 패스워드 null check도 들어가면 좋아요~

2019-07-22 01:01 UTC, ssosso commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +    public void setActionOfArticle(Model model, String actionRoute, String formMethod) {
다른 메서들중에서도 반환형식이 void인 것은 반환값이 있도록 변경해보면 어떨까요~?

2019-07-22 01:01 UTC, ssosso commented on src/main/java/techcourse/myblog/service/UserService.java
> +        if (!userDto.getPassword().equals(userDto.getPasswordConfirm())) {
password null check + dto에게 equal한지 물어보면 어떨까요~?

2019-07-22 01:01 UTC, ssosso commented on src/main/java/techcourse/myblog/service/UserService.java
> +        session.removeAttribute(LOGIN_SESSION_KEY);
👍

2019-07-22 01:01 UTC, ssosso commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +        } catch (CouldNotFindArticleIdException e) {
ControllerAdvice를 만들어 처리하면 어떨까요~?

2019-07-22 01:01 UTC, ssosso commented on src/main/java/techcourse/myblog/web/ControllerUtil.java
> +public class ControllerUtil {
잘 분리하셨네요~ 이 부분이 조금 더 발전하면 interceptor가 될 수 있습니다:)

2019-07-22 01:01 UTC, ssosso commented on src/test/java/techcourse/myblog/domain/ArticleTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
도메인 객체는 해당 구문을 넣을 필요가 없습니다~

2019-07-22 01:01 UTC, ssosso commented on src/test/java/techcourse/myblog/web/LoginControllerTest.java
> +                .exchange()
request를 보내는 부분에서 반복되는 코드를 좀 더 범용적으로 만들어서 모든 controller Test의 상위에 위치하는 클래스를 만들어보는 것은 어떨까요~? 모든 contoller Test는 그 클래스를 상속하게 하면 어떨까요~?

2019-07-22 01:01 UTC, ssosso commented on src/test/java/techcourse/myblog/web/UserControllerTest.java
> +    }
세션없을 때 원하는 페이지로 이동하는지 테스트하는 부분이 포함되어 있나요~?

2019-07-22 03:16 UTC, hyojaekim commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +        articleRepository.save(findArticle);
오 감사합니다! 👍 
@transactional 어노테이션에 대해 알아보겠습니다.

2019-07-22 03:22 UTC, hyojaekim commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +    public void update(Long articleId, ArticleDto articleDto) {
궁금한게 있습니다!
업데이트를 하고 난 뒤에 반영한 내용에 대해서 확인하고 싶은 경우가 있을 수 있기 때문에 반환하는 것이 낫다고 생각하는데 혹시 다른 이유가 있나요??

2019-07-22 03:56 UTC, hyojaekim commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +    public void update(Long articleId, ArticleDto articleDto) {
궁금한게 있습니다!

업데이트 한 내용에 대해 확인이 필요한 경우가 있을 수 있기 때문에 업데이트 한 Article을 반환하는 것이 낫다고 생각해서 반영해 봤는데 혹시 다른 이유가 있나요????

2019-07-22 08:07 UTC, hyojaekim commented on src/test/java/techcourse/myblog/web/LoginControllerTest.java
> +                .exchange()
공통된 메서드를 어느 컨트롤러에서 위치해야 할지 고민했었는데
상속을 이용하니까 편해졌습니다!

2019-07-22 08:26 UTC, hyojaekim commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +    public void setActionOfArticle(Model model, String actionRoute, String formMethod) {
게시물을 새로 작성할 때와 게시물을 수정할 때에 Form action과 method를 달리 해야해서 
Model에 Form action과 method를 때에 따라 넣어주려고 메서드를 분리했습니다.

이러한 행동을 하는 메소드에도 반환 값이 있어야 하는지 궁금합니다.

2019-07-25 09:45 UTC, ssosso commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +    public void update(Long articleId, ArticleDto articleDto) {
말씀하신 의도도 분명히 포함됩니다:) 테스트할 때도 반환값이 있는게 더 좋지 않을까요~?

2019-07-25 10:03 UTC, ssosso commented on src/main/java/techcourse/myblog/service/ArticleService.java
> +    public void setActionOfArticle(Model model, String actionRoute, String formMethod) {
상기 코멘트에서 답변했던 바와 같습니다:) 메서드를 설계할 때는 반환값이 있는 메서드를 기본으로 하는 것이 좋습니다:) 그리고 다시 보니 해당 메서드는 controller에 있어야 할 것 같은데 어떻게 생각하시나요~?

2019-07-25 10:24 UTC, ssosso approved these changes
효오~ 안녕하세요:) 작성해주신 코드 확인했어요~
부족했던 기능도 많이 채워넣으셨네요:) 고생하셨습니다~
몇 가지 코멘트 남겼으니 확인부탁드리며, 이번 단계는 이만 마무리하겠습니다:)

2019-07-25 10:24 UTC, merged