[게시판 회원 기능] 닉 미션 제출합니다.
woowacourse/jwp-blog pull request #91
Opened 2019-07-21 11:47 UTC by wbluke

안녕하세요~ Summer!
이번주 수목금 예비군 다녀오느라 제출이 늦었습니다ㅜㅜ!
주말에 급하게 혼자 뚝딱뚝딱 구현해서 보내봅니다...! 부족하지만 많은 조언 부탁드립니다.

그리고 구현하면서 궁금했던 부분들, 문제였던 부분들 적어보겠습니다.

1. Test 상황에서 이해가 될듯말듯 한 문제가 있습니다.
- 현재 ArticleControllerTests 의 상황
```
* 1주차 
- Test 간 순서가 보장되지 않아서, 단순히 article을 조회하는 메소드와 article을 삭제하는 메소드 테스트 간의 혼선이 생김
- 조회 Test는 1번 article을, 삭제 Test는 2번 article만을 목표하게 하여 문제 해결
- 전체 Test 실행 후 DB에는 1, 3, 4, 5, 6 article이 남아있음

* 2주차
- ArticleControllerTests만을 실행시키면 문제 없이 모든 Test 통과
- 그런데 web 패키지 하위에 있는 모든 ControllerTests 를 실행시키면, 이상하게도 articleControllerTests의 fetchArticle, editArticle에서만 문제가 생김
- web 패키지 하위 모든 Test 실행 후 DB에는 3, 4, 5, 6 article이 남아있음 (1번 article이 사라짐)
```

아직 ATDD 상황에서의 Test에 대해 자세하게 배우지 않아 견고한 Test들을 못짜고 있어서 이런 문제가 발생하는 듯 합니다. 정확한 원인을 모르겠네요ㅠㅠ

2. Service Test도 만드려고 했는데, 아직 Mocking Test에 대해서 배우지를 못했고, Mockito 등에 대해서도 공부하려고 해봤으나 아직 이해가 잘 되지 않아서 구현하지는 못했습니다. 

늦었지만 잘 부탁드려요...! :)

2019-07-21 14:09 UTC, jihan805 requested changes
안녕하세요 닉~!
시간이 많이 없었을텐데 정말 잘 구현했어요 💯 
몇가지 피드백 남겼으니 확인해주세요 :)

2019-07-21 14:09 UTC, jihan805 commented on src/main/java/techcourse/myblog/domain/User.java
> +    @Id
User에 대한 validation도 구현하면 어떨까요?

2019-07-21 14:09 UTC, jihan805 commented on src/main/java/techcourse/myblog/repository/ArticleRepository.java
> +    @Query(value = "update Article a set a.title = :#{#article.title}, a.coverUrl = :#{#article.coverUrl}"
이번 단계에서는 Jpa를 공부/사용하고 있어요!
위와같이 네이티브 쿼리를 사용하는 대신 어떻게 update를 구현할 수 있을지 찾아보면 어떨까요?

2019-07-21 14:09 UTC, jihan805 commented on src/main/java/techcourse/myblog/service/UserService.java
> +    }
User 정보 업데이트도 구현해보면 좋을 것 같아요 :)

2019-07-21 14:09 UTC, jihan805 commented on src/main/java/techcourse/myblog/service/UserService.java
> +        if (existsEmail(user.getEmail())) {
@Column의 unique에 대해서도 알아두면 좋을 것 같아요!

2019-07-21 14:09 UTC, jihan805 commented on src/main/java/techcourse/myblog/service/UserService.java
> +    public void checkLogin(String email, String password) {
로그인 관련 서비스는 loginService등의 클래스로 분리하면 어떨까요?

2019-07-21 14:09 UTC, jihan805 commented on src/main/java/techcourse/myblog/web/UserController.java
> +        return httpSession.getAttribute("user") != null;
session의 키로 사용하는 "user"를 class등으로 분리하여 관리하면 어떨까요? (static)
Interceptor클래스도 구현해보면 어떨까요!?

2019-07-21 14:09 UTC, jihan805 commented on src/main/java/techcourse/myblog/web/UserController.java
> +        try {
예외처리를 위해  controller advice에 대해 찾아보면 좋을 것 같아요!

2019-07-21 14:09 UTC, jihan805 commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +class ArticleControllerTests {
테스트를 꼼꼼하게 실행해서 실패하는 경우를 찾았네요 👍 
시퀀스 때문에 발생하는 것 같아요.  @GeneratedValue(strategy = GenerationType.IDENTITY)로 변경해주세요!

2019-07-21 14:18 UTC, jihan805 commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
>      void fetchArticle() {
해당 테스트 메서드는 몇번째로 실행될지 알수 없어요!
테스트 메서드는 
1. article insert 
2. id가 1인 article을 가지고와요.
만약, 해당 테스트 메서드가 1번째가 아닌 5번째로 실행된다면 autoincrement에 의해 직전에  insert한 id가 1이 아닐 수도 있지 않을까요!?

2019-07-24 16:06 UTC, wbluke commented
1. https://jojoldu.tistory.com/295 참고해서 Spring JPA 2.0 부터 변경된 시퀀스 생성전략에 대해 알게 되었습니다!
AUTO로 해놓으면 알아서 IDENTITY로 매핑해줄줄 알고있었던 게 화근이었네요ㅜㅜ

2. 새로고침 시에 에러가 난다든지, 같은 http콜이 계속 날아간다든지 하는 에러들이 있었습니다. 알고보니 redirect를 잘 몰라서 소극적으로 사용해 벌어지는 문제들이었는데, 꼭 필요한 중요 로직에 적용해가며 취약점들을 보완해보았습니다!

3. Interceptor에 대해 새롭게 알게 되었습니다. 확실히 session에 있는 user를 미리 체크하여 controller가 훨씬 가벼워진 느낌을 받을 수 있었습니다!

4. 주신 피드백은 모두 반영하였지만... 시간이 모자라 추가로 반영하고 싶었던 두 가지 부분을 아직 하지 못했습니다ㅜㅜ
`slf4j로 로그 남기기` 와 `ServiceTest, InterceptTest 등 작성하지 못한 테스트 짜기` 이 두 가지 인데요,
PR드린 후에도 계속 진행해볼 예정입니다...! ㅜㅜ

2019-07-25 13:47 UTC, jihan805 approved these changes
안녕하세요 닉 ~! 피드백 반영 잘해주셨어요 💯 
몇가지 코멘트 남겼으니 확인해주세요!
머지할게요 :)

2019-07-25 13:47 UTC, jihan805 commented on src/main/java/techcourse/myblog/domain/Article.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
남긴 피드백에 대해 적용하고 추가 학습까지 했네요 👍 👍

2019-07-25 13:47 UTC, jihan805 commented on src/main/java/techcourse/myblog/domain/User.java
> +    @Column(unique = true)
적용 💯 
Column에 다른 여러가지 추가 속성들이 있으니 찾아보고 사용해도 좋을것 같아요 :)

2019-07-25 13:47 UTC, jihan805 commented on src/main/java/techcourse/myblog/dto/ArticleSaveParams.java
> +public class ArticleSaveParams {
요청을 위한 dto로 사용할거라면 ~Params보다는 ~RequestDto 등의 네이밍이 조금 더 적합할 것 같아요!
또한 dto 패턴 체크에 대해서도 찾아보면 좋을 것 같아요!

2019-07-25 13:47 UTC, jihan805 commented on src/main/java/techcourse/myblog/repository/UserRepository.java
> +    void deleteByEmail(String email);
사용하지 않는것 같은데, 사용하지 않으면 제거해요!

2019-07-25 13:47 UTC, jihan805 commented on src/main/java/techcourse/myblog/service/LoginService.java
> +        return userRepository.findByEmail(email);
만약 나중에 유저 관려 이메일로 조회해야하는 경우 아래 로직이 UserService에도 추가되어야해요. 
이런 경우 로그인 서비스가 유저 서비스의 메서드를 사용하도록 하는 것도 방법이에요!

2019-07-25 13:47 UTC, jihan805 commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +        log.info("save edited article post request params={}", articleSaveParams);
log의 info, debug 레벨 사용 👍 
error에 대해서도 찾아보고 추후에 적용해봐요!

2019-07-25 13:51 UTC, jihan805 commented on src/test/java/techcourse/myblog/service/LoginServiceTest.java
> +class LoginServiceTest {
서비스 레이어 테스트도 추가했네요 :) 
@DataJpaTest에 대해서도 찾아봐요!!
https://jojoldu.tistory.com/33

2019-07-25 13:51 UTC, merged