[게시판 회원 기능] 러너덕 미션 제출합니다
woowacourse/jwp-blog pull request #97
Opened 2019-07-22 03:35 UTC by Deocksoo

2019-07-23 04:20 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
전체적인 구현 👍 테스트에 정말 많은 공을 들이신것 같아요. 👍 
몇가지 피드백 추가했는데요,
참고 부탁드리고 궁금하신 점 있으시면 연락주세요!

2019-07-23 04:20 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/LogInService.java
> +        if (logInUser == null) {
.orElseThrow로 null에 대해서 처리하고 있기 때문에 null체크를 굳이 다시 안해주셔도 될 것 같습니다. :)

2019-07-23 04:20 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/UserService.java
> +            validate(userDto);
validate에 대해서 서비스가 책임지는것이 아닌,

User를 생성하면서 validate를 체크할 수 있지 않을까요?
그리고 JSR-303에 대해서 공부해보시고 적용하시면 DTO단에서도 선으로 체크도 가능하니 검색해보시고 적용해보면 좋을 것 같습니다. :)

2019-07-23 04:20 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/UserService.java
> +            throw new SignUpException(e.getMessage());
예외를 다시 잡고 던지는 이유가 있을까요?

2019-07-23 04:20 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/UserService.java
> +            checkValidName(name);
마찬가지로 validate 로직은 서비스에서 책임지지 않아도 될 것 같습니다.
또한 setter가 아닌 메시지를 보내서(UserDTO 등으로) 객체를 수정하는 방향으로 수정해보면 어떨까요?

2019-07-23 04:20 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/UserService.java
> +        articleRepository.deleteByUserId(id);
UserService인데 Article에 대한 의존이 있네요.
해당 객체의 책임에 적합하지 않은 것 같습니다.

2019-07-23 04:20 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +        HttpSession httpSession = httpServletRequest.getSession();
세션에서 사용자 정보를 체크하는 로직이 상당히 많이 중복될것으로 보이는데
Interceptor를 통해서 한곳에서 관리해보면 어떨까요?

2019-07-23 04:20 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +    @ExceptionHandler(NotFoundArticleException.class)
ControllerAdvice를 알아보고 거기서 모두 처리해도 될 것 같습니다 :)

2019-07-23 04:20 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +    private boolean isLoggedInUserArticle(HttpServletRequest httpServletRequest, Article article) {
해당 메서드가 너무 많은 책임을 가지고 있는것 같네요.
세선 체크에 대한 부분은 Interceptor로 분리하고
게시글 삭제 권한만 적용할 수 있지 않을까요?

2019-07-23 04:20 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/UserController.java
> +    private boolean isLoggedInUser(HttpSession httpSession, Long id) {
isLoggedInUserArticle과 마찬가지로 별도로 분리 해보면 좋겠습니다. :)

2019-07-23 04:20 UTC, phs1116 commented on src/test/java/techcourse/myblog/service/UserServiceTest.java
> +    void checkSpecialCharacterInPassword() {
서비스가 전체적으로 validation에 대한 테스트만 들어가있네요.
validation에 대한 로직은 도메인 엔티티와 DTO에서 체크하고
Service 테스트는 서비스 로직 위주로 테스트해보면 어떨까요?

2019-07-23 04:20 UTC, phs1116 commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +                .cookie("JSESSIONID", LogInControllerTest.logInAsBaseUser(webTestClient))
로그인 기능이 전체 테스트에서 전역적으로 사용될 기능으로 보입니다.
LogInControllerTest.logInAsBaseUser(webTestClient)로 특정 테스트에 종속적으로 사용하지말고
유틸, 혹은 추상클래스로 분리해서 사용해보면 어떨까요?

2019-07-23 04:20 UTC, phs1116 commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +                .consumeWith(response -> {
returnResult로 체이닝을 끊어서 테스트하면 더욱 가독성이 좋을 것 같습니다. :)

2019-07-23 04:20 UTC, phs1116 commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +                                assertThat(body.contains(newTitle)).isTrue();
true 여부만 확인하지말고 실제로 원하는 데이터가 들어가있는지 검증을 해보면 어떨까요?

2019-07-23 04:20 UTC, phs1116 commented on src/test/java/techcourse/myblog/web/MyPageControllerTest.java
> +                .expectStatus().isFound();
Redircet 같은 경우 Location을 확인해서 원하는 방향으로 리다이렉트가 되는지도 검증해보면 어떨까요? :)

2019-07-24 05:53 UTC, Deocksoo commented on src/main/java/techcourse/myblog/service/UserService.java
> +            throw new SignUpException(e.getMessage());
회원 가입할 때 던져지는 예외와 회원 정보를 업데이트할 때 던져지는 예외를 구분해주고 싶었습니다. 그런데 회원 가입하는 경우와 업데이트하는 경우에 유효성 검사 로직 일부가 중복되어서 validation check 메서드 중 몇 개를 공유하게 되었는데, 그러면서 한번에 깔끔하게 두 가지 종류 예외로 구분할 수가 없게 되었어요. 그래서 일단 UserArgumentException으로 먼저 예외를 던지고, 회원 가입할 때 생기는 UserArgumentException들을 모아서 SignUpException으로, 회원 정보 수정할 때 생기는 UserArguemntException들을 모아서 UserUpdateException으로 다시 구분해주도록 하였습니다.

2019-07-24 05:53 UTC, Deocksoo commented on src/main/java/techcourse/myblog/service/UserService.java
> +            throw new SignUpException(e.getMessage());
그런데 사실 별로 깔끔하지 못한 방법인 것 같아요.. 말씀해주셨던 것처럼 validate에 대해서 user가 책임지도록 하고 예외 종류를 하나로 모으는게 더 나을거같아서 한번 수정해보려고 합니다!

2019-07-28 03:13 UTC, Deocksoo reviewed
안녕하세요 화투, 
피드백 남겨주신 부분들을 어떻게든 반영해보려고 하다가 제출이 너무 늦어지고 말았네요ㅜㅜ
아직도 부족한 부분이 너무 많은데, 시간이 이미 많이 지나버려서 일단 제출합니다.
저번 피드백이 기억나시지 않을 수도 있을것 같아서 크게 수정한 부분들을 한번 정리해 봤어요.
난리법석인 코드를 보시는 데에 조금이나마 도움이 되었으면 좋겠습니다..

1. Interceptor를 활용해 login 되어있는지 여부를 컨트롤러 앞단에서 체크하도록 수정했습니다.
2. UserService에서 validation 체크하는 부분을 모두 UserFactory를 만들어 옮기고, 비즈니스 로직과 관련된 기능만 수행하도록 수정하였습니다. 그리고 Dto에서 유효성을 검사하도록 하는 JSR-303 빈 검증 방식을 활용해서 체크를 한번 더 해 보았어요. 이렇게 두번씩 체크를 해도 괜찮을까요? 아니면 Dto에서 검증하는 경우에는 따로 domain에서 체크를 하지 않아도 괜찮은건가요?

3. 테스트에서 중복되는 login 코드들을 Utils 클래스로 뽑아내 보았습니다. 하지만 아직도 영 좋지 못한 냄새가 많이 나기는 해서 찝찝한 부분이 많아요. WebTestClient에 이어져있는 chaining도 어떻게 끊는 것이 좋을지 고민입니다. 차차 공부해서 더 수정해보고 싶어요.

피드백 남겨주신 부분들을 수정하면서 많은 공부가 된 것 같아요.
신경써 피드백 남겨주셔서 감사합니다!

2019-07-28 03:13 UTC, Deocksoo commented on src/main/java/techcourse/myblog/service/UserService.java
> +            validate(userDto);
만약에 DTO단에서 체크를 한다면, 선으로 한번 체크 하고 User를 생성하면서 한번 더 체크를 하게 되는 걸까요?

2019-07-28 03:13 UTC, Deocksoo commented on src/main/java/techcourse/myblog/service/UserService.java
> +            validate(userDto);
중복되는 이메일을 체크하는 경우에 repository에 의존성을 갖게 될 것 같은데, 그러면 중복 체크만 service에서 책임치고 나머지 validation체크는 User를 생성할 때 체크하는 방식으로 나눠도 괜찮을까요?

2019-07-28 03:13 UTC, Deocksoo commented on src/main/java/techcourse/myblog/service/UserService.java
> +        articleRepository.deleteByUserId(id);
User를 삭제하는 경우에, 해당 user가 작성한 게시글도 모두 삭제해주려면 결국 ArticleRepository에도 접근해야 할 것 같습니다. 그런데 말씀해주신대로 이곳에서 의존성을 가지면 안 될 것 같아서, 고민 끝에 UserController에서 ArticleService에 의존성을 갖도록 수정하였는데, 이 방법도 결국 의존성을 갖는 방법인것 같아요. 이렇게 해결하는 것이 괜찮을까요..? 아니면 혹시 의존성을 아얘 갖지 않고 문제를 해결할 수도 있을까요?

2019-07-28 03:13 UTC, Deocksoo commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +                                assertThat(body.contains(newTitle)).isTrue();
contains를 활용하면 실제로 원하는 데이터가 들어가있는지 검증한다는 것이 아닌가요..? 제가 이 부분을 확실히 이해하지 못한것 같아요ㅜㅜ 그래도 일단 assertThat의 contains 기능을 활용해서 구현해보았습니다!

2019-07-29 05:17 UTC, phs1116 approved these changes
안녕하세요! 리뷰어 화투입니다.
피드백 반영하시느라 정말 수고 많으셨습니다. :)
질문에 대한 답변 및 몇가지 피드백 추가했는데
다음 단계 진행하시면서 같이 참고 부탁드립니다. :)

2019-07-29 05:17 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/UserService.java
> +            validate(userDto);
네. 해당 객체를 생성할 때 필요한 부분에 대해서는 User에서 책임져도 됩니다.
중복에 대해서는 Repository의 직접 의존이 아닌 별도 Service를 통해 느슨하게 의존을 가져가 체크할 수도 있겠네요. :)

2019-07-29 05:17 UTC, phs1116 commented on src/main/java/techcourse/myblog/service/UserService.java
> +        articleRepository.deleteByUserId(id);
UserService, ArticleService 두가지 도메인 서비스에 대해 모두 의존을 가지고있는 별도 application service(facade)를 생성하시면 될 것 같습니다. :)

2019-07-29 05:17 UTC, phs1116 commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +                                assertThat(body.contains(newTitle)).isTrue();
contains가 아닌 실제 객체로 비교를 해보면 어떨까 싶어서 말씀드렸어요 :)

2019-07-29 05:17 UTC, phs1116 commented on src/main/java/techcourse/myblog/domain/User.java
> +    public User(String name, String email, String password) {
Factory로 무조건 생성하게 하려면 User의 생성자도 막아야 할 것 같네요!
현재는 잘못된 객체가 생성될 여지가 있습니다.
Factory가 따로 책임 지게 하지 말고
Password 객체, Eamil 객체 등을 따로 만들어 해당 객체에서 처리하도록 해보면 어떨까요?
AttributeConverter 를 공부해서 적용해도 좋을 것 같습니다.

2019-07-29 05:17 UTC, phs1116 commented on src/main/java/techcourse/myblog/web/ArticleController.java
> +        UserProfileDto user = (UserProfileDto) httpSession.getAttribute(LOGGED_IN_USER);
UserProfileDto user = (UserProfileDto) httpSession.getAttribute(LOGGED_IN_USER);
에 대한 부분을 argumentResolver를 활용해 조금 더 깔끔하게 수정 할 수 있을것 같네요. :)

2019-07-29 05:17 UTC, phs1116 commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +                .consumeWith(response -> {
체이닝 및 콜백이 너무 많은데요
consumeWith 부분을 밖으로 뺼 수 있지 않을까요?

2019-07-29 05:19 UTC, merged

2019-07-29 05:51 UTC, Deocksoo commented on src/main/java/techcourse/myblog/domain/User.java
> +    public User(String name, String email, String password) {
앗 수정했어야하는데 깜빡했네요. 공부해서 적용해보도록 하겠습니다!

2019-07-29 05:58 UTC, Deocksoo commented on src/test/java/techcourse/myblog/web/ArticleControllerTests.java
> +                .consumeWith(response -> {
수정해볼 수 있을거같아요. 한번 해보겠습니다!